const QUESTIONS = {
  "데이터베이스": [
    { id:"db_001", question:"관계 해석에서 '모든 것에 대하여(for all)'의 의미를 나타내는 기호는?", options:["∋","∈","∀","∪"], answer:3 },
    { id:"db_002", question:"트랜잭션의 병행제어 목적으로 옳지 않은 것은?", options:["데이터베이스의 공유 최대화","시스템의 활용도 최대화","데이터베이스의 일관성 최소화","사용자에 대한 응답시간 최소화"], answer:3 },
    { id:"db_003", question:"물리적 저장 장치의 입장에서 본 데이터베이스 구조로서 실제로 데이터베이스에 저장될 레코드의 형식을 정의하고 저장 데이터 항목의 표현방법, 내부 레코드의 물리적 순서 등을 나타내는 스키마는?", options:["외부 스키마","내부 스키마","개념 스키마","슈퍼 스키마"], answer:2 },
    { id:"db_004", question:"순수관계연산자에서 릴레이션의 일부 속성만 추출하여 중복되는 튜플은 제거한 후 새로운 릴레이션을 생성하는 연산자는?", options:["REMOVE","PROJECT","DIVISION","JOIN"], answer:2 },
    { id:"db_005", question:"다음 SQL 문장 중 DML에 해당하지 않는 것은?", options:["SELECT","DELETE","CREATE","INSERT"], answer:3 },
    { id:"db_006", question:"SQL의 분류 중 DDL에 해당하지 않는 것은?", options:["UPDATE","ALTER","DROP","CREATE"], answer:1 },
    { id:"db_007", question:"병행제어(Concurrency Control) 기법에 해당하지 않는 것은?", options:["로킹기법","최적병행수행 기법","타임스탬프 기법","시분할 기법"], answer:4 },
    { id:"db_008", question:"하나의 애트리뷰트가 가질 수 있는 원자값들의 집합을 의미하는 것은?", options:["튜플","릴레이션","도메인","엔티티"], answer:3 },
    { id:"db_009", question:"정규화 과정 중 1NF에서 2NF가 되기 위한 조건은?", options:["1NF를 만족하고 모든 도메인이 원자값이어야 한다","1NF를 만족하고 키가 아닌 모든 애트리뷰트가 기본키에 대해 이행적으로 함수 종속되지 않아야 한다","1NF를 만족하고 키가 다치 종속이 제거되어야 한다","1NF를 만족하고 키가 아닌 모든 속성이 기본키에 대하여 완전 함수적 종속 관계를 만족해야 한다"], answer:4 },
    { id:"db_010", question:"DDL(Data Definition Language)의 기능이 아닌 것은?", options:["데이터베이스의 생성 기능","병행처리시 Lock 및 Unlock 기능","테이블의 삭제 기능","인덱스(Index) 생성 기능"], answer:2 },
    { id:"db_011", question:"참조 무결성을 유지하기 위하여 부모 테이블의 항목 값을 삭제할 경우 자동적으로 자식 테이블의 해당 레코드를 삭제하기 위한 옵션은?", options:["CLUSTER","CASCADE","SET-NULL","RESTRICTED"], answer:2 },
    { id:"db_012", question:"해싱함수(Hashing Function)에 해당되지 않는 것은?", options:["제곱법(mid-square)","숫자분석법(digit analysis)","체인법(chain)","제산법(division)"], answer:3 },
    { id:"db_013", question:"이행적 함수 종속 관계를 의미하는 것은?", options:["A→B이고 B→C일 때, A→C를 만족하는 관계","A→B이고 B→C일 때, B→A를 만족하는 관계","A→B이고 B→C일 때, C→A를 만족하는 관계","A→B이고 B→C일 때, C→B를 만족하는 관계"], answer:1 },
    { id:"db_014", question:"뷰(View)에 대한 설명으로 옳지 않은 것은?", options:["뷰 위에 또 다른 뷰를 정의할 수 있다","DBA는 보안 측면에서 뷰를 활용할 수 있다","뷰의 정의는 ALTER문을 이용하여 변경할 수 없다","SQL을 사용하면 뷰에 대한 삽입, 갱신, 삭제 연산 시 제약사항이 없다"], answer:4 },
    { id:"db_015", question:"데이터베이스 설계 순서로 옳은 것은?", options:["요구 조건 분석 → 개념적 설계 → 논리적 설계 → 물리적 설계 → 구현","요구 조건 분석 → 논리적 설계 → 개념적 설계 → 물리적 설계 → 구현","요구 조건 분석 → 논리적 설계 → 물리적 설계 → 개념적 설계 → 구현","요구 조건 분석 → 개념적 설계 → 물리적 설계 → 논리적 설계 → 구현"], answer:1 },
    { id:"db_016", question:"관계형 데이터베이스에서 기본키(Primary Key)에 대한 설명으로 옳지 않은 것은?", options:["유일성을 가져야 한다","NULL 값을 가질 수 없다","하나의 테이블에 여러 개의 기본키를 설정할 수 있다","최소성을 만족해야 한다"], answer:3 },
    { id:"db_017", question:"Linear Search의 평균 검색 횟수는?", options:["n-1","(n+1)/2","n","n/2"], answer:2 },
    { id:"db_018", question:"관계 데이터베이스 제약조건 중 한 릴레이션의 기본키를 구성하는 어떠한 속성 값도 NULL 값이나 중복 값을 가질 수 없다는 조건은?", options:["키 제약 조건","참조 무결성 제약 조건","참여 제약 조건","개체 무결성 제약 조건"], answer:4 },
    { id:"db_019", question:"해싱에서 동일한 홈 주소로 인하여 충돌이 일어난 레코드들의 집합을 의미하는 것은?", options:["Synonym","Collision","Bucket","Overflow"], answer:3 },
    { id:"db_020", question:"뷰에 대한 설명으로 옳지 않은 것은?", options:["뷰는 삽입, 삭제, 갱신 연산에 제약사항이 없다","뷰는 데이터 접근 제어로 보안을 제공한다","뷰는 독자적인 인덱스를 가질 수 없다","뷰는 데이터의 논리적 독립성을 제공한다"], answer:1 },
    { id:"db_021", question:"n개의 노드로 구성된 무방향 그래프의 최대 간선수는?", options:["n-1","n(n-1)/2","n/2","n(n+1)"], answer:2 },
    { id:"db_022", question:"동시성 제어를 위한 직렬화 기법으로 트랜잭션 간의 순서를 미리 정하는 방법은?", options:["로킹 기법","타임스탬프 기법","검증 기법","배타 로크 기법"], answer:2 },
    { id:"db_023", question:"SQL 문장 중 DDL문이 아닌 것은?", options:["CREATE","DELETE","ALTER","DROP"], answer:2 },
    { id:"db_024", question:"해싱 테이블의 오버플로우 처리 기법이 아닌 것은?", options:["개방 주소법","폐쇄 주소법","로그 주소법","재해싱"], answer:3 },
    { id:"db_025", question:"데이터베이스 설계 단계 중 저장 레코드 양식 설계, 레코드 집중의 분석 및 설계, 접근 경로 설계와 관계되는 것은?", options:["논리적 설계","요구 조건 분석","물리적 설계","개념적 설계"], answer:3 },
    { id:"db_026", question:"어떤 릴레이션 R에 속한 모든 도메인이 원자값(Atomic Value)만으로 되어 있는 정규형은?", options:["제1정규형(1NF)","제2정규형(2NF)","제3정규형(3NF)","보이스/코드 정규형(BCNF)"], answer:1 },
    { id:"db_027", question:"관계 데이터 모델에서 릴레이션(Relation)에 관한 설명으로 옳지 않은 것은?", options:["튜플들의 순서는 중요하지 않다","모든 속성값은 원자값이어야 한다","각 속성의 이름은 릴레이션 내에서 유일해야 한다","한 릴레이션에서 동일한 튜플이 중복될 수 있다"], answer:4 },
    { id:"db_028", question:"관계 대수(Relational Algebra)의 순수 관계 연산자가 아닌 것은?", options:["SELECT","PROJECT","JOIN","UNION"], answer:4 },
    { id:"db_029", question:"트랜잭션(Transaction)의 특성이 아닌 것은?", options:["원자성(Atomicity)","일관성(Consistency)","고립성(Isolation)","효율성(Efficiency)"], answer:4 },
    { id:"db_030", question:"데이터베이스의 3단계 스키마 구조에서 전체 데이터베이스의 논리적 구조를 정의하는 스키마는?", options:["외부 스키마","내부 스키마","개념 스키마","물리 스키마"], answer:3 },
    { id:"db_031", question:"로킹(Locking) 기법에서 2단계 로킹 프로토콜(2PL)의 단계가 올바르게 나열된 것은?", options:["확장 단계 → 축소 단계","축소 단계 → 확장 단계","공유 단계 → 배타 단계","배타 단계 → 공유 단계"], answer:1 },
    { id:"db_032", question:"B-Tree 인덱스에 대한 설명으로 옳지 않은 것은?", options:["균형 트리 구조를 유지한다","검색, 삽입, 삭제 연산의 시간 복잡도가 O(log n)이다","순차 접근이 용이하지 않다","데이터베이스 인덱스에 널리 사용된다"], answer:3 },
    { id:"db_033", question:"다음 중 DCL(Data Control Language)에 해당하는 것은?", options:["SELECT","INSERT","GRANT","CREATE"], answer:3 },
    { id:"db_034", question:"관계형 데이터베이스에서 후보키(Candidate Key)에 대한 설명으로 옳은 것은?", options:["NULL 값을 가질 수 있다","유일성과 최소성을 만족한다","반드시 하나의 속성으로만 구성된다","외래키가 될 수 없다"], answer:2 },
    { id:"db_035", question:"데이터 웨어하우스(Data Warehouse)의 특성이 아닌 것은?", options:["주제 지향적(Subject-Oriented)","통합적(Integrated)","비휘발적(Non-Volatile)","실시간 갱신(Real-Time Update)"], answer:4 },
    { id:"db_036", question:"분산 데이터베이스의 투명성(Transparency)에 해당하지 않는 것은?", options:["위치 투명성","중복 투명성","병행 투명성","성능 투명성"], answer:4 },
    { id:"db_037", question:"SQL에서 GROUP BY 절과 함께 사용하는 집계 함수가 아닌 것은?", options:["COUNT","SUM","AVG","BETWEEN"], answer:4 },
    { id:"db_038", question:"데이터베이스 회복(Recovery) 기법 중 체크포인트(Checkpoint) 기법에 대한 설명으로 옳은 것은?", options:["트랜잭션 실패 시 처음부터 재수행한다","일정 시점마다 체크포인트를 설정하여 회복 시간을 단축한다","모든 로그를 삭제하는 방식이다","하드웨어 장애에만 적용된다"], answer:2 },
    { id:"db_039", question:"SQL의 SELECT문에서 중복된 튜플을 제거하기 위해 사용하는 키워드는?", options:["UNIQUE","DISTINCT","ONLY","SINGLE"], answer:2 },
    { id:"db_040", question:"관계 데이터베이스에서 외래키(Foreign Key)에 대한 설명으로 옳지 않은 것은?", options:["다른 릴레이션의 기본키를 참조한다","NULL 값을 가질 수 없다","참조 무결성 제약조건과 관련된다","두 릴레이션 간의 관계를 표현한다"], answer:2 },
    { id:"db_041", question:"postfix로 표현된 연산식 '3 4 * 5 6 * +'의 연산 결과는?", options:["35","42","81","360"], answer:2 },
    { id:"db_042", question:"스택(Stack)의 삭제 알고리즘에서 스택이 비어있을 때 삭제를 시도할 경우 발생하는 오류는?", options:["Overflow","Top=Top+1","Underflow","Top=Top"], answer:3 },
    { id:"db_043", question:"DBMS(Database Management System)의 필수 기능이 아닌 것은?", options:["정의 기능","조작 기능","제어 기능","컴파일 기능"], answer:4 },
    { id:"db_044", question:"데이터 무결성(Data Integrity)을 보장하기 위한 제약 조건이 아닌 것은?", options:["도메인 제약 조건","키 제약 조건","참조 무결성 제약 조건","정렬 제약 조건"], answer:4 },
    { id:"db_045", question:"데이터 독립성(Data Independence)에서 논리적 데이터 독립성이란?", options:["물리적 구조 변경이 응용프로그램에 영향을 미치지 않는 것","논리적 구조 변경이 응용프로그램에 영향을 미치지 않는 것","데이터 중복을 최소화하는 것","데이터 보안을 유지하는 것"], answer:2 },
    { id:"db_046", question:"SQL에서 HAVING 절에 대한 설명으로 옳은 것은?", options:["개별 행에 대한 조건을 지정한다","GROUP BY로 그룹화된 결과에 조건을 지정한다","ORDER BY와 함께만 사용할 수 있다","WHERE 절을 대체한다"], answer:2 },
    { id:"db_047", question:"관계 대수에서 두 릴레이션의 공통 속성을 기준으로 합치는 연산은?", options:["UNION","INTERSECTION","JOIN","DIFFERENCE"], answer:3 },
    { id:"db_048", question:"데이터베이스에서 트리거(Trigger)에 대한 설명으로 옳은 것은?", options:["사용자가 명시적으로 호출해야 실행된다","특정 이벤트 발생 시 자동으로 실행되는 프로시저이다","SELECT문에서만 사용 가능하다","인덱스 생성에만 사용된다"], answer:2 },
    { id:"db_049", question:"BCNF(Boyce-Codd Normal Form)에 대한 설명으로 옳은 것은?", options:["3NF보다 완화된 정규형이다","모든 결정자가 후보키인 정규형이다","다치 종속을 제거한 정규형이다","조인 종속을 제거한 정규형이다"], answer:2 },
    { id:"db_050", question:"데이터베이스의 인덱스(Index)에 대한 설명으로 옳지 않은 것은?", options:["검색 속도를 향상시킨다","삽입, 삭제, 수정 시 오버헤드가 발생한다","인덱스는 자동으로 최신 상태를 유지한다","반드시 기본키에만 생성할 수 있다"], answer:4 },
    { id:"db_051", question:"SQL에서 NULL 값을 처리하는 함수는?", options:["ISNULL / NVL","NULLCHECK","EMPTYSET","ZEROVALUE"], answer:1 },
    { id:"db_052", question:"관계형 모델에서 슈퍼키(Super Key)에 대한 설명으로 옳은 것은?", options:["최소성을 만족하는 키이다","유일성만 만족하면 되는 키이다","NULL 값을 허용하는 키이다","반드시 단일 속성으로 구성된다"], answer:2 },
    { id:"db_053", question:"데이터베이스에서 저장 프로시저(Stored Procedure)의 장점이 아닌 것은?", options:["네트워크 트래픽 감소","보안 강화","실행 계획 재사용","실시간 동적 SQL 생성에 유리"], answer:4 },
    { id:"db_054", question:"다음 중 비절차적 언어에 해당하는 것은?", options:["COBOL","FORTRAN","SQL","Pascal"], answer:3 },
    { id:"db_055", question:"E-R 다이어그램에서 개체(Entity)를 표현하는 도형은?", options:["마름모","타원","직사각형","삼각형"], answer:3 },
    { id:"db_056", question:"E-R 다이어그램에서 관계(Relationship)를 표현하는 도형은?", options:["마름모","타원","직사각형","삼각형"], answer:1 },
    { id:"db_057", question:"데이터베이스에서 시스템 카탈로그(System Catalog)의 다른 이름은?", options:["데이터 사전(Data Dictionary)","데이터 마트(Data Mart)","데이터 웨어하우스(Data Warehouse)","메타데이터(Metadata)"], answer:1 },
    { id:"db_058", question:"SQL의 JOIN 중 두 테이블에서 조인 조건에 맞지 않는 행도 포함하여 결과를 반환하는 것은?", options:["INNER JOIN","NATURAL JOIN","OUTER JOIN","CROSS JOIN"], answer:3 },
    { id:"db_059", question:"다음 중 데이터 마이닝(Data Mining)에 대한 설명으로 옳은 것은?", options:["데이터를 단순 저장하는 기술이다","대량의 데이터에서 유용한 패턴을 발견하는 기술이다","데이터를 암호화하는 기술이다","데이터를 압축하는 기술이다"], answer:2 },
    { id:"db_060", question:"관계형 데이터베이스에서 REVOKE 명령에 대한 설명으로 옳은 것은?", options:["테이블을 삭제한다","사용자에게 권한을 부여한다","사용자로부터 권한을 회수한다","새로운 사용자를 생성한다"], answer:3 },
    { id:"db_061", question:"데이터베이스 정규화의 목적으로 가장 거리가 먼 것은?", options:["데이터 중복 최소화","삽입, 삭제, 갱신 이상 제거","데이터 무결성 유지","검색 성능 극대화"], answer:4 },
    { id:"db_062", question:"트랜잭션의 원자성(Atomicity)에 대한 설명으로 옳은 것은?", options:["트랜잭션은 분리되어 독립적으로 수행된다","트랜잭션은 전부 수행되거나 전혀 수행되지 않아야 한다","트랜잭션 수행 후 데이터는 일관된 상태를 유지한다","완료된 트랜잭션은 영구적으로 반영된다"], answer:2 },
    { id:"db_063", question:"SQL에서 서브쿼리(Subquery)에 대한 설명으로 옳지 않은 것은?", options:["SELECT문 안에 포함된 SELECT문이다","WHERE절, HAVING절, FROM절에 사용 가능하다","반드시 단일 행을 반환해야 한다","단일 행, 다중 행 서브쿼리가 있다"], answer:3 },
    { id:"db_064", question:"데이터베이스에서 OLAP(Online Analytical Processing)에 대한 설명으로 옳은 것은?", options:["실시간 트랜잭션 처리 시스템이다","다차원 데이터 분석을 위한 시스템이다","데이터 백업 시스템이다","네트워크 관리 시스템이다"], answer:2 },
    { id:"db_065", question:"다음 SQL 중 테이블의 모든 행을 삭제하되 테이블 구조는 유지하는 명령은?", options:["DROP TABLE","DELETE FROM 테이블명","TRUNCATE TABLE","REMOVE TABLE"], answer:3 },
    { id:"db_066", question:"관계 대수에서 합집합 호환(Union Compatible)의 조건이 아닌 것은?", options:["두 릴레이션의 차수(degree)가 같아야 한다","대응되는 속성의 도메인이 같아야 한다","속성의 이름이 같아야 한다","두 릴레이션의 투플 수가 같아야 한다"], answer:4 },
    { id:"db_067", question:"데이터베이스의 동시성 제어에서 팬텀 읽기(Phantom Read)가 발생하는 격리 수준은?", options:["READ UNCOMMITTED","READ COMMITTED","REPEATABLE READ","SERIALIZABLE"], answer:3 },
    { id:"db_068", question:"SQL에서 CREATE VIEW 문으로 생성된 뷰에 대한 설명으로 옳지 않은 것은?", options:["가상 테이블이다","기본 테이블의 데이터를 참조한다","DROP VIEW로 삭제할 수 있다","뷰는 물리적으로 데이터를 저장한다"], answer:4 },
    { id:"db_069", question:"다음 중 4NF(제4정규형)에서 제거하는 종속은?", options:["부분 함수 종속","이행 함수 종속","다치 종속(MVD)","조인 종속"], answer:3 },
    { id:"db_070", question:"데이터베이스 락(Lock)의 종류 중 다른 트랜잭션의 읽기는 허용하지만 쓰기는 허용하지 않는 락은?", options:["공유 락(Shared Lock)","배타 락(Exclusive Lock)","의도 락(Intent Lock)","갱신 락(Update Lock)"], answer:1 },
    { id:"db_071", question:"SQL에서 BETWEEN A AND B 조건의 의미는?", options:["A보다 크고 B보다 작은","A 이상이고 B 이하인","A보다 작거나 B보다 큰","A와 B 중 하나인"], answer:2 },
    { id:"db_072", question:"데이터베이스의 분산 처리에서 데이터의 복제(Replication)의 장점이 아닌 것은?", options:["가용성 향상","장애 복구 용이","데이터 일관성 관리 복잡","응답 시간 단축"], answer:3 },
    { id:"db_073", question:"SQL에서 EXISTS 연산자에 대한 설명으로 옳은 것은?", options:["특정 값이 목록에 존재하는지 검사한다","서브쿼리의 결과가 하나 이상의 행을 반환하면 TRUE이다","두 값이 동일한지 비교한다","NULL 값을 검사한다"], answer:2 },
    { id:"db_074", question:"관계 데이터 모델의 키 중 대체키(Alternate Key)에 대한 설명은?", options:["기본키로 선택된 키이다","기본키로 선택되지 않은 후보키이다","외부 릴레이션을 참조하는 키이다","NULL 값을 허용하는 키이다"], answer:2 },
    { id:"db_075", question:"데이터베이스에서 시스템 장애 발생 시 회복 기법 중 UNDO와 REDO 모두 수행하는 기법은?", options:["지연 갱신 기법","즉시 갱신 기법","그림자 페이지 기법","체크포인트 기법"], answer:2 },
    { id:"db_076", question:"SQL에서 LIKE 연산자에서 임의의 문자 하나를 나타내는 와일드카드는?", options:["%","_","*","?"], answer:2 },
    { id:"db_077", question:"데이터베이스의 함수적 종속에서 완전 함수 종속(Full Functional Dependency)의 의미는?", options:["키의 일부에만 종속되는 것","키 전체에 종속되는 것","이행적으로 종속되는 것","다치 종속되는 것"], answer:2 },
    { id:"db_078", question:"SQL에서 IN 연산자의 기능은?", options:["범위 내의 값 검색","목록 내의 값과 일치 여부 검색","패턴 일치 검색","NULL 값 검색"], answer:2 },
    { id:"db_079", question:"데이터베이스 설계에서 논리적 설계 단계의 결과물은?", options:["E-R 다이어그램","관계 스키마","저장 구조 설계서","요구사항 명세서"], answer:2 },
    { id:"db_080", question:"다음 SQL 실행 결과로 옳은 것은? SELECT COUNT(*) FROM 학생 WHERE 학년 IS NULL;", options:["학년이 NULL인 학생 수를 반환한다","학년이 NULL이 아닌 학생 수를 반환한다","모든 학생 수를 반환한다","0을 반환한다"], answer:1 },
    { id:"db_081", question:"데이터베이스 무결성 제약 조건 중 도메인 무결성(Domain Integrity)이란?", options:["기본키는 NULL 값을 가질 수 없다","외래키는 참조하는 테이블의 기본키 값이어야 한다","속성 값이 해당 도메인에 속해야 한다","테이블의 모든 행은 유일해야 한다"], answer:3 },
    { id:"db_082", question:"관계 데이터베이스에서 자연 조인(Natural Join)에 대한 설명으로 옳은 것은?", options:["공통 속성을 기준으로 조인하며 중복 속성을 제거한다","조인 조건 없이 카테시안 곱을 수행한다","왼쪽 테이블의 모든 행을 포함한다","두 테이블의 모든 행 조합을 반환한다"], answer:1 },
    { id:"db_083", question:"트랜잭션의 지속성(Durability)에 대한 설명으로 옳은 것은?", options:["트랜잭션은 완전히 수행되거나 전혀 수행되지 않는다","트랜잭션 수행 후 데이터베이스는 일관된 상태를 유지한다","완료된 트랜잭션의 결과는 영구적으로 반영된다","트랜잭션은 다른 트랜잭션에 영향을 받지 않는다"], answer:3 },
    { id:"db_084", question:"데이터베이스 설계에서 개념적 설계 단계의 결과물은?", options:["E-R 다이어그램","관계 스키마","저장 구조 설계서","SQL 스크립트"], answer:1 },
    { id:"db_085", question:"SQL에서 ORDER BY 절에 대한 설명으로 옳지 않은 것은?", options:["기본 정렬 순서는 오름차순이다","DESC 키워드로 내림차순 정렬한다","WHERE 절 이후에 위치한다","GROUP BY 없이는 사용할 수 없다"], answer:4 },
    { id:"db_086", question:"데이터 모델링에서 카디널리티(Cardinality)가 의미하는 것은?", options:["릴레이션의 속성 수","릴레이션의 투플 수","두 엔티티 간의 대응 관계 수","도메인의 크기"], answer:3 },
    { id:"db_087", question:"다음 중 데이터 독립성의 종류가 아닌 것은?", options:["논리적 독립성","물리적 독립성","기능적 독립성","응용 독립성"], answer:3 },
    { id:"db_088", question:"SQL에서 UNION과 UNION ALL의 차이점은?", options:["UNION은 중복을 포함하고 UNION ALL은 제거한다","UNION은 중복을 제거하고 UNION ALL은 포함한다","차이가 없다","UNION ALL은 속도가 느리다"], answer:2 },
    { id:"db_089", question:"데이터베이스에서 클러스터 인덱스(Clustered Index)에 대한 설명으로 옳은 것은?", options:["테이블당 여러 개를 만들 수 있다","데이터가 인덱스 순서로 물리적으로 정렬된다","실제 데이터와 분리되어 저장된다","검색 속도가 일반 인덱스보다 항상 느리다"], answer:2 },
    { id:"db_090", question:"데이터베이스에서 연쇄 복귀(Cascading Rollback)란?", options:["트랜잭션 성공 시 변경사항을 영구 반영하는 것","하나의 트랜잭션 실패로 인해 관련된 다른 트랜잭션도 롤백하는 것","데이터를 백업하는 것","인덱스를 재구성하는 것"], answer:2 },
    { id:"db_091", question:"SQL에서 ALTER TABLE 명령으로 할 수 없는 것은?", options:["열 추가","열 삭제","제약 조건 추가","테이블 데이터 수정"], answer:4 },
    { id:"db_092", question:"데이터베이스의 뷰(View) 장점이 아닌 것은?", options:["데이터 보안 향상","복잡한 쿼리 단순화","저장 공간 절약","논리적 데이터 독립성"], answer:3 },
    { id:"db_093", question:"분산 데이터베이스에서 수평 분할(Horizontal Fragmentation)이란?", options:["테이블의 열을 나누어 분산시키는 것","테이블의 행을 나누어 분산시키는 것","테이블 전체를 복제하여 분산시키는 것","인덱스를 분산시키는 것"], answer:2 },
    { id:"db_094", question:"SQL에서 조인(JOIN) 중 카테시안 곱(Cartesian Product)을 구하는 것은?", options:["INNER JOIN","OUTER JOIN","CROSS JOIN","NATURAL JOIN"], answer:3 },
    { id:"db_095", question:"데이터 웨어하우스에서 OLAP의 Roll-up 연산이란?", options:["데이터를 더 세분화하여 보는 것","데이터를 더 높은 수준으로 집계하는 것","특정 차원을 선택하여 분석하는 것","데이터를 회전하여 다른 관점으로 보는 것"], answer:2 },
    { id:"db_096", question:"관계 데이터베이스에서 릴레이션의 차수(Degree)란?", options:["투플의 수","속성의 수","도메인의 크기","인스턴스의 수"], answer:2 },
    { id:"db_097", question:"SQL에서 집계 함수 중 NULL 값을 처리하는 방식으로 옳은 것은?", options:["COUNT(*)는 NULL 행을 제외한다","SUM은 NULL 값을 0으로 처리한다","AVG 계산 시 NULL 값은 무시된다","MAX, MIN은 NULL 값을 포함한다"], answer:3 },
    { id:"db_098", question:"데이터베이스 정규화에서 삽입 이상(Insertion Anomaly)이 발생하는 원인은?", options:["데이터 중복","잘못된 인덱스 설계","부적절한 함수 종속","과도한 정규화"], answer:3 },
    { id:"db_099", question:"데이터베이스에서 파티셔닝(Partitioning)의 목적으로 옳은 것은?", options:["데이터 암호화","대용량 테이블의 관리 및 성능 향상","데이터 압축","트랜잭션 처리 단순화"], answer:2 },
    { id:"db_100", question:"SQL에서 COMMIT과 ROLLBACK에 대한 설명으로 옳은 것은?", options:["COMMIT은 트랜잭션을 취소한다","ROLLBACK은 변경사항을 영구 저장한다","COMMIT은 변경사항을 영구 저장하고 ROLLBACK은 취소한다","둘 다 트랜잭션을 시작한다"], answer:3 }
],

  "전자계산기구조": [
    { id:"ca_001", question:"10진수 -456을 PACK 형식으로 표현한 것은?", options:["45 6D","- 4 56","45 6F","F4 56"], answer:1 },
    { id:"ca_002", question:"8비트 구조에 해당하는 인텔 컴퓨터 프로세서는?", options:["Intel Core i5","Intel 8051","Intel Pentium","Intel Celeron"], answer:2 },
    { id:"ca_003", question:"INTERRUPT의 발생 원인으로 가장 옳지 않은 것은?", options:["일방적인 인스트럭션 수행","수퍼바이저 콜","정전이나 자료 전달의 오류 발생","전압의 변화나 온도 변화"], answer:1 },
    { id:"ca_004", question:"일반적인 컴퓨터 시스템의 바이오스(BIOS)가 탑재되는 곳은?", options:["RAM","I/O port","ROM","CPU"], answer:3 },
    { id:"ca_005", question:"캐시(cache) 액세스 시간 11ns, 주기억장치 액세스 시간이 20ns, 캐시 적중률이 90%일 때 기억장치 평균 액세스 시간은?", options:["1ns","3ns","9ns","13ns"], answer:4 },
    { id:"ca_006", question:"메이저 스테이트 중 하드웨어로 실현되는 서브루틴의 호출이라고 볼 수 있는 것은?", options:["EXECUTE 스테이트","INDIRECT 스테이트","INTERRUPT 스테이트","FETCH 스테이트"], answer:3 },
    { id:"ca_007", question:"중재동작이 끝날 때마다 모든 마스터들의 우선순위가 한 단계씩 낮아지고 가장 우선순위가 낮았던 마스터가 최상위 우선순위를 가지도록 하는 가변우선순위 방식은?", options:["동등 우선순위(Equal Priority) 방식","임의 우선순위(Random Priority) 방식","회전 우선순위(Rotating Priority) 방식","최소-최근 사용(Least Recently Used) 방식"], answer:3 },
    { id:"ca_008", question:"DRAM에 관한 설명으로 옳지 않은 것은?", options:["SRAM에 비해 기억 용량이 크다","쌍안정 논리 회로의 성질을 응용한다","주기억 장치 구성에 사용된다","SRAM에 비해 속도가 느리다"], answer:2 },
    { id:"ca_009", question:"다음 중 오류 검출 코드(Error Detection Code)가 아닌 것은?", options:["Biquinary code","2-out-of-5 code","3-out-of-5 code","Excess-3 code"], answer:4 },
    { id:"ca_010", question:"메모리 인터리빙과 관계없는 것은?", options:["데이터의 저장 공간을 확장하기 위한 방법이다","복수 모듈 기억 장치를 이용한다","기억장치에 접근을 각 모듈에 번갈아 가면서 하도록 한다","각 인스트럭션에서 사용하는 데이터의 주소에 관계가 있다"], answer:4 },
    { id:"ca_011", question:"전가산기를 구성하기 위하여 필요한 소자를 바르게 나타낸 것은?", options:["반가산기 2개, AND 게이트 1개","반가산기 1개, AND 게이트 2개","반가산기 2개, OR 게이트 1개","반가산기 1개, OR 게이트 2개"], answer:3 },
    { id:"ca_012", question:"16개의 플립플롭으로 된 Shift register에 10진수 13이 기억되어 있을 때 3bit 만큼 왼쪽으로 Shift 했을 때의 값은?", options:["26","39","104","52"], answer:3 },
    { id:"ca_013", question:"기억장치 계층구조에서 상위계층 기억장치가 가지는 특징으로 옳은 것은?", options:["기억장치 액세스 속도가 느려진다","CPU에 의한 액세스 빈도가 높아진다","기억장치 용량이 증가한다","기억장치를 구성하는 비트당 가격이 낮아진다"], answer:2 },
    { id:"ca_014", question:"컴퓨터의 메이저 상태에 대한 설명으로 틀린 것은?", options:["EXECUTE 상태가 끝나면 항상 FETCH 상태로만 간다","간접 주소 명령어 형식인 경우 FETCH-INDIRECT-EXECUTE 순서로 진행되어야 한다","EXECUTE 상태는 연산자 코드의 내용에 따라 연산을 수행하는 과정이다","FETCH 상태에서는 기억 장치에서 인스트럭션을 읽어 중앙처리장치로 가져온다"], answer:1 },
    { id:"ca_015", question:"입출력 방법 가운데 I/O를 위한 특별한 명령어를 I/O 프로세서에게 수행토록 하여 CPU 관여 없이 I/O를 수행하는 방법은?", options:["프로그램에 의한 I/O","인터럽트에 의한 I/O","데이지 체인에 의한 I/O","채널에 의한 I/O"], answer:4 },
    { id:"ca_016", question:"기억장치가 1024 워드(word)로 구성되어 있고, 각 워드는 16비트(bit)로 구성되어 있다고 가정할 때, PC, MAR, MBR의 비트수를 옳게 나타낸 것은?", options:["PC:10, MAR:10, MBR:10","PC:10, MAR:10, MBR:16","PC:16, MAR:10, MBR:16","PC:16, MAR:16, MBR:16"], answer:2 },
    { id:"ca_017", question:"0-주소 인스트럭션에 반드시 필요한 것은?", options:["스택","베이스 레지스터","큐","주소 레지스터"], answer:1 },
    { id:"ca_018", question:"누산기(accumulator)에 대한 설명으로 가장 옳은 것은?", options:["연산장치에 있는 레지스터의 하나로 연산 결과를 일시적으로 기억하는 장치이다","주기억장치 내에 존재하는 회로로 가감승제 계산 및 논리 연산을 행하는 장치이다","일정한 입력 숫자들을 더하여 그 누계를 항상 보관하는 장치이다","정밀 계산을 위해 특별히 만들어 두어 유효숫자의 개수를 늘리기 위한 것이다"], answer:1 },
    { id:"ca_019", question:"16개의 입력선을 가진 multiplexer의 출력에 32개의 출력선을 가진 demultiplexer를 연결했을 경우에 multiplexer와 demultiplexer의 선택선은 각각 몇 개를 가져야 하는가?", options:["multiplexer : 4개, demultiplexer : 5개","multiplexer : 4개, demultiplexer : 3개","multiplexer : 8개, demultiplexer : 4개","multiplexer : 4개, demultiplexer : 8개"], answer:1 },
    { id:"ca_020", question:"불 함수식 F=(A+B)·(A+C)를 가장 간소화한 것은?", options:["F=A+BC","F=B+AC","F=A+AC","F=C+AB"], answer:1 },
    { id:"ca_021", question:"하나의 입력 정보를 여러 개의 출력선 중에 하나를 선택하여 정보를 전달하는데 사용하는 것은?", options:["디코더(Decoder)","인코더(Encoder)","멀티플렉서(Multiplexer)","디멀티플렉서(Demultiplexer)"], answer:4 },
    { id:"ca_022", question:"다음 중 명령어 사이클에 대한 설명이 가장 옳지 않은 것은?", options:["간접 사이클은 피연산 데이터가 있는 기억 장치의 유효 주소를 계산하는 과정이다","인터럽트 사이클은 요청된 서비스 프로그램을 수행하여 완료할 때까지의 과정이다","실행 사이클은 연산자 코드의 내용에 따라 연산을 수행하는 과정이다","패치 사이클은 주기억 장치로부터 명령어를 꺼내어 디코딩하는 과정이다"], answer:2 },
    { id:"ca_023", question:"인터럽트의 처리 루틴의 순서로 올바른 것은? (ㄱ.현재 상태 보존 ㄴ.인터럽트 인식 ㄷ.서비스로 분기 및 서비스 ㄹ.사용자 상태 복구 및 재개)", options:["ㄱ→ㄴ→ㄷ→ㄹ","ㄴ→ㄷ→ㄱ→ㄹ","ㄴ→ㄱ→ㄹ→ㄷ","ㄴ→ㄱ→ㄷ→ㄹ"], answer:4 },
    { id:"ca_024", question:"10진수 3을 3-초과 코드(Excess-3 Code)로 표현하면?", options:["0011","0110","0101","0100"], answer:2 },
    { id:"ca_025", question:"데이터를 고속으로 처리하기 위해 연산 장치를 병렬로 구성한 처리 구조로 벡터 계산이나 행렬 계산에 주로 사용되는 프로세서는?", options:["코프로세서","다중 프로세서","배열 프로세서","대칭 프로세서"], answer:3 },
    { id:"ca_026", question:"인터럽트 우선순위를 결정하는 Polling 방식에 대한 설명으로 옳지 않은 것은?", options:["많은 인터럽트 발생 시 처리 시간 및 반응 시간이 매우 빠르다","S/W적으로 CPU가 각 장치 하나하나를 차례로 조사하는 방식이다","조사 순위가 우선순위가 된다","모든 인터럽트를 위한 공통의 서비스 루틴을 갖고 있다"], answer:1 },
    { id:"ca_027", question:"연산 속도가 가장 빠른 주소 지정 방식(Addressing Mode)은?", options:["Direct Addressing Mode","Indirect Addressing Mode","Calculate Addressing Mode","Immediate Addressing Mode"], answer:4 },
    { id:"ca_028", question:"2진수 1011을 그레이 코드(Gray Code)로 변환하면?", options:["1101","1110","1100","1010"], answer:2 },
    { id:"ca_029", question:"파이프라인(Pipeline) 처리에 대한 설명으로 옳지 않은 것은?", options:["여러 단계를 동시에 처리하여 성능을 향상시킨다","명령어 수행 단계를 겹쳐서 실행한다","단일 명령어 수행 시간이 단축된다","데이터 해저드(Data Hazard)가 발생할 수 있다"], answer:3 },
    { id:"ca_030", question:"RISC(Reduced Instruction Set Computer) 구조의 특징으로 옳지 않은 것은?", options:["명령어 수가 적다","고정 길이 명령어를 사용한다","레지스터 수가 많다","마이크로프로그래밍을 주로 사용한다"], answer:4 },
    { id:"ca_031", question:"DMA(Direct Memory Access) 방식에 대한 설명으로 옳지 않은 것은?", options:["CPU의 개입 없이 주기억장치와 I/O 장치 간 데이터를 직접 전송한다","대용량 데이터 전송에 효율적이다","사이클 스틸링(Cycle Stealing) 방식을 사용한다","소량의 데이터 전송에만 사용된다"], answer:4 },
    { id:"ca_032", question:"다음 중 가상 기억장치(Virtual Memory)에 대한 설명으로 옳지 않은 것은?", options:["보조기억장치를 주기억장치처럼 사용한다","프로그램의 크기가 실제 주기억장치 크기보다 클 수 있다","페이징 또는 세그멘테이션 기법을 이용한다","주기억장치의 속도를 높이는 데 사용된다"], answer:4 },
    { id:"ca_033", question:"플립플롭(Flip-Flop) 중 T 플립플롭에 대한 설명으로 옳은 것은?", options:["T=0이면 출력이 변하고, T=1이면 출력이 유지된다","T=1이면 출력이 보수가 되고, T=0이면 상태 유지된다","클록 신호에만 반응한다","두 개의 입력 신호를 사용한다"], answer:2 },
    { id:"ca_034", question:"2의 보수(2's Complement) 표현에서 8비트로 표현할 수 있는 음수의 범위는?", options:["-127 ~ 0","-128 ~ -1","-128 ~ 0","-127 ~ -1"], answer:2 },
    { id:"ca_035", question:"CPU의 구성 요소가 아닌 것은?", options:["ALU(산술논리연산장치)","제어장치","레지스터","보조기억장치"], answer:4 },
    { id:"ca_036", question:"마이크로 오퍼레이션(Micro Operation)에 대한 설명으로 옳지 않은 것은?", options:["레지스터에 저장된 데이터에 대한 기본 동작이다","하나의 클록 펄스 동안 실행되는 기본 동작이다","마이크로 프로그램을 구성하는 기본 단위이다","고급 언어 수준의 명령어이다"], answer:4 },
    { id:"ca_037", question:"캐시 기억장치의 매핑(Mapping) 방식이 아닌 것은?", options:["직접 매핑(Direct Mapping)","연관 매핑(Associative Mapping)","집합 연관 매핑(Set-Associative Mapping)","순차 매핑(Sequential Mapping)"], answer:4 },
    { id:"ca_038", question:"다음 중 입출력 제어 방식을 CPU 개입 정도가 낮은 순서로 올바르게 나열한 것은?", options:["프로그램에 의한 I/O → 인터럽트 I/O → DMA","인터럽트 I/O → 프로그램에 의한 I/O → DMA","DMA → 인터럽트 I/O → 프로그램에 의한 I/O","DMA → 프로그램에 의한 I/O → 인터럽트 I/O"], answer:3 },
    { id:"ca_039", question:"명령어 형식에서 오퍼랜드(Operand) 필드의 수가 가장 많은 것은?", options:["0-주소 명령어","1-주소 명령어","2-주소 명령어","3-주소 명령어"], answer:4 },
    { id:"ca_040", question:"16진수 2AF를 10진수로 변환한 값은?", options:["687","689","691","693"], answer:1 },
    { id:"ca_041", question:"부동소수점(Floating Point) 표현 방식에서 정규화(Normalization)를 수행하는 이유는?", options:["계산 속도를 높이기 위해","표현의 유일성을 보장하고 정밀도를 최대화하기 위해","메모리를 절약하기 위해","오류를 검출하기 위해"], answer:2 },
    { id:"ca_042", question:"마이크로프로세서에서 스택 포인터(Stack Pointer)의 역할은?", options:["다음에 수행할 명령어 주소를 저장","스택의 최상위 주소를 가리킴","현재 수행 중인 명령어를 저장","연산 결과를 임시 저장"], answer:2 },
    { id:"ca_043", question:"다음에 처리할 명령어 주소를 기억하는 레지스터는?", options:["MAR(Memory Address Register)","MBR(Memory Buffer Register)","PC(Program Counter)","IR(Instruction Register)"], answer:3 },
    { id:"ca_044", question:"주기억장치와 보조기억장치 사이에서 데이터를 전송하는 데 사용되는 블록의 단위는?", options:["바이트(Byte)","워드(Word)","페이지(Page)","비트(Bit)"], answer:3 },
    { id:"ca_045", question:"NOR 게이트만으로 구현할 수 없는 논리 연산은?", options:["AND","OR","NOT","NOR 게이트만으로 모든 연산 구현 가능"], answer:4 },
    { id:"ca_046", question:"불 대수(Boolean Algebra)에서 드모르간(De Morgan)의 법칙으로 옳은 것은?", options:["(A+B)' = A'+B'","(A·B)' = A'·B'","(A+B)' = A'·B'","(A·B)' = A'+B' 만 성립"], answer:3 },
    { id:"ca_047", question:"SRAM과 DRAM의 비교 설명으로 옳은 것은?", options:["SRAM이 DRAM보다 집적도가 높다","DRAM이 SRAM보다 속도가 빠르다","SRAM은 캐시 메모리에 주로 사용된다","DRAM은 리프레시가 필요 없다"], answer:3 },
    { id:"ca_048", question:"컴퓨터에서 BCD(Binary Coded Decimal) 코드에 대한 설명으로 옳은 것은?", options:["10진수 한 자리를 3비트로 표현한다","10진수 한 자리를 4비트로 표현한다","오류 검출 기능이 있다","그레이 코드의 일종이다"], answer:2 },
    { id:"ca_049", question:"명령어 파이프라인에서 데이터 해저드(Data Hazard)가 발생하는 경우는?", options:["분기 명령어가 실행될 때","앞의 명령어 결과를 다음 명령어가 사용할 때","인터럽트가 발생할 때","캐시 미스가 발생할 때"], answer:2 },
    { id:"ca_050", question:"컴퓨터 버스(Bus)의 종류 중 CPU와 주기억장치 사이의 데이터 전송에 사용되는 버스는?", options:["시스템 버스","내부 버스","확장 버스","로컬 버스"], answer:2 },
    { id:"ca_051", question:"2진수 덧셈에서 올림수(Carry)가 발생하는 경우는?", options:["0+0","1+0","0+1","1+1"], answer:4 },
    { id:"ca_052", question:"JK 플립플롭에서 J=1, K=1일 때의 동작은?", options:["상태 유지","0으로 리셋","1로 세트","현재 상태의 보수로 반전"], answer:4 },
    { id:"ca_053", question:"컴퓨터 시스템에서 인터럽트 처리 후 돌아올 주소를 저장하는 레지스터는?", options:["PC(Program Counter)","SP(Stack Pointer)","IR(Instruction Register)","MAR(Memory Address Register)"], answer:1 },
    { id:"ca_054", question:"다음 중 순서 논리 회로(Sequential Logic Circuit)가 아닌 것은?", options:["플립플롭","레지스터","카운터","디코더"], answer:4 },
    { id:"ca_055", question:"컴퓨터에서 음수를 표현하는 방법으로 사용하지 않는 것은?", options:["부호-크기(Sign-Magnitude)","1의 보수","2의 보수","3의 보수"], answer:4 },
    { id:"ca_056", question:"캐시 적중률(Cache Hit Ratio)이 높을수록 나타나는 효과는?", options:["메모리 접근 시간 증가","전체 시스템 성능 향상","캐시 용량 증가","전력 소비 감소"], answer:2 },
    { id:"ca_057", question:"CISC(Complex Instruction Set Computer)의 특징으로 옳은 것은?", options:["명령어 수가 적고 단순하다","고정 길이 명령어를 사용한다","레지스터 수가 많다","다양한 주소 지정 방식을 사용한다"], answer:4 },
    { id:"ca_058", question:"다음 중 조합 논리 회로(Combinational Logic Circuit)에 해당하는 것은?", options:["플립플롭","레지스터","멀티플렉서","카운터"], answer:3 },
    { id:"ca_059", question:"컴퓨터에서 주기억장치(Main Memory)의 특징으로 옳은 것은?", options:["비휘발성 메모리이다","보조기억장치보다 용량이 크다","CPU가 직접 접근 가능하다","자기 디스크를 사용한다"], answer:3 },
    { id:"ca_060", question:"2진수 1100에 대한 1의 보수는?", options:["0011","0100","1111","0000"], answer:1 },
    { id:"ca_061", question:"다음 중 내부 버스(Internal Bus)에 해당하지 않는 것은?", options:["데이터 버스","주소 버스","제어 버스","USB 버스"], answer:4 },
    { id:"ca_062", question:"마이크로프로그램(Microprogram) 제어 방식에 대한 설명으로 옳은 것은?", options:["하드웨어로만 구현한다","제어 기억장치(Control Memory)에 저장된 마이크로 명령어로 CPU를 제어한다","RISC 프로세서에서 주로 사용한다","수정이 불가능하다"], answer:2 },
    { id:"ca_063", question:"다음 중 10진수 156을 16진수로 변환한 값은?", options:["9A","9B","9C","9D"], answer:3 },
    { id:"ca_064", question:"컴퓨터에서 페치(Fetch) 사이클에서 수행되는 마이크로 오퍼레이션 순서로 옳은 것은?", options:["MAR←PC, MBR←M[MAR], IR←MBR, PC←PC+1","PC←PC+1, MAR←PC, MBR←M[MAR], IR←MBR","IR←MBR, MAR←PC, MBR←M[MAR], PC←PC+1","MBR←M[MAR], MAR←PC, PC←PC+1, IR←MBR"], answer:1 },
    { id:"ca_065", question:"컴퓨터의 입출력 방식 중 폴링(Polling) 방식의 단점은?", options:["CPU가 장치 상태를 지속적으로 확인해야 한다","인터럽트를 처리할 수 없다","DMA 사용이 불가능하다","멀티태스킹을 지원하지 않는다"], answer:1 },
    { id:"ca_066", question:"다음 중 반가산기(Half Adder)의 출력은?", options:["합(Sum)과 올림수(Carry)","합(Sum)만","올림수(Carry)만","차(Difference)와 올림수"], answer:1 },
    { id:"ca_067", question:"컴퓨터 시스템에서 레지스터(Register)의 특징으로 옳은 것은?", options:["CPU 외부에 위치한다","캐시보다 속도가 느리다","CPU 내부에서 가장 빠른 기억장치이다","용량이 주기억장치보다 크다"], answer:3 },
    { id:"ca_068", question:"10진수 0.625를 2진수로 변환하면?", options:["0.011","0.101","0.110","0.111"], answer:2 },
    { id:"ca_069", question:"다음 중 직접 주소 지정 방식(Direct Addressing)의 특징으로 옳은 것은?", options:["명령어에 오퍼랜드 값이 직접 포함된다","명령어의 주소 필드가 데이터의 실제 주소이다","주소 필드가 다른 주소를 가리킨다","레지스터를 이용하여 주소를 계산한다"], answer:2 },
    { id:"ca_070", question:"컴퓨터에서 인터럽트 벡터(Interrupt Vector)가 하는 역할은?", options:["인터럽트 발생 빈도를 기록한다","인터럽트 서비스 루틴의 주소를 저장한다","인터럽트 우선순위를 결정한다","인터럽트를 마스킹한다"], answer:2 },
    { id:"ca_071", question:"다음 논리 게이트 중 출력이 항상 입력의 반대인 게이트는?", options:["AND","OR","NOT","XOR"], answer:3 },
    { id:"ca_072", question:"컴퓨터에서 명령어 파이프라인의 단계가 4단계일 때 최대 성능 향상 배수는?", options:["2배","4배","8배","16배"], answer:2 },
    { id:"ca_073", question:"다음 중 캐시 교체 알고리즘으로 가장 많이 사용되는 것은?", options:["FIFO","LRU","LFU","Random"], answer:2 },
    { id:"ca_074", question:"컴퓨터에서 슈퍼스칼라(Superscalar) 구조란?", options:["파이프라인 단계가 매우 많은 구조","여러 개의 명령어를 동시에 실행하는 구조","명령어 집합이 복잡한 구조","단일 코어에서 동작하는 구조"], answer:2 },
    { id:"ca_075", question:"8비트로 표현할 수 있는 부호 없는 정수의 최대값은?", options:["127","128","255","256"], answer:3 },
    { id:"ca_076", question:"다음 중 비휘발성(Non-Volatile) 메모리가 아닌 것은?", options:["ROM","Flash Memory","DRAM","EEPROM"], answer:3 },
    { id:"ca_077", question:"컴퓨터에서 버스 중재(Bus Arbitration) 방식이 아닌 것은?", options:["데이지 체인(Daisy Chain)","폴링(Polling)","독립적 요청(Independent Request)","파이프라인(Pipelining)"], answer:4 },
    { id:"ca_078", question:"다음 중 XOR(Exclusive OR) 게이트의 진리표에서 출력이 1이 되는 경우는?", options:["두 입력이 모두 0","두 입력이 모두 1","두 입력이 서로 다를 때","두 입력이 모두 1이거나 모두 0"], answer:3 },
    { id:"ca_079", question:"컴퓨터의 기억장치 계층 구조를 속도가 빠른 순서로 나열한 것은?", options:["레지스터 > 캐시 > 주기억장치 > 보조기억장치","캐시 > 레지스터 > 주기억장치 > 보조기억장치","주기억장치 > 캐시 > 레지스터 > 보조기억장치","레지스터 > 주기억장치 > 캐시 > 보조기억장치"], answer:1 },
    { id:"ca_080", question:"컴퓨터에서 워드(Word) 크기가 32비트일 때 표현 가능한 서로 다른 값의 수는?", options:["2^16","2^32","2^64","2^8"], answer:2 },
    { id:"ca_081", question:"다음 중 스택(Stack) 구조로 동작하는 메모리 영역은?", options:["힙(Heap)","코드 세그먼트","스택 세그먼트","데이터 세그먼트"], answer:3 },
    { id:"ca_082", question:"컴퓨터의 상대 주소 지정 방식(Relative Addressing)에서 유효 주소는?", options:["명령어에 포함된 주소값","PC + 변위(Displacement)","베이스 레지스터 + 변위","인덱스 레지스터 + 변위"], answer:2 },
    { id:"ca_083", question:"다음 중 플립플롭의 클럭(Clock) 신호에 대한 설명으로 옳은 것은?", options:["클럭이 없어도 상태가 변할 수 있다","클럭의 상승 또는 하강 에지에서 상태가 변한다","클럭 주파수는 회로 동작에 영향을 주지 않는다","클럭이 높은 동안에만 입력을 받는다"], answer:2 },
    { id:"ca_084", question:"컴퓨터에서 부동소수점 수의 표현 형식에서 지수부(Exponent)의 역할은?", options:["소수점의 위치를 나타낸다","숫자의 부호를 나타낸다","유효 숫자를 나타낸다","오류 검출 비트이다"], answer:1 },
    { id:"ca_085", question:"다음 중 마이크로프로세서의 레지스터 중 플래그 레지스터(Flag Register)가 나타내는 정보가 아닌 것은?", options:["제로(Zero) 플래그","올림수(Carry) 플래그","오버플로우(Overflow) 플래그","메모리 크기 플래그"], answer:4 },
    { id:"ca_086", question:"컴퓨터에서 RISC와 CISC의 설계 철학 차이로 옳은 것은?", options:["RISC는 복잡한 명령어로 소프트웨어를 단순화","CISC는 단순한 명령어로 컴파일러를 단순화","RISC는 단순한 명령어로 하드웨어를 단순화","CISC는 단순한 명령어로 하드웨어를 복잡화"], answer:3 },
    { id:"ca_087", question:"컴퓨터의 인터럽트 마스킹(Interrupt Masking)이란?", options:["인터럽트를 강제로 발생시키는 것","특정 인터럽트를 무시하도록 설정하는 것","인터럽트 처리 속도를 높이는 것","인터럽트 우선순위를 변경하는 것"], answer:2 },
    { id:"ca_088", question:"다음 중 가산기(Adder)의 올바른 설명은?", options:["반가산기는 이전 단계의 올림수를 처리한다","전가산기는 두 비트만 더할 수 있다","반가산기는 두 비트를 더하고 올림수를 출력한다","전가산기는 세 비트를 더하고 올림수를 출력한다"], answer:4 },
    { id:"ca_089", question:"다음 중 자기 디스크의 접근 시간 구성 요소가 아닌 것은?", options:["탐색 시간(Seek Time)","회전 지연 시간(Rotational Latency)","전송 시간(Transfer Time)","실행 시간(Execution Time)"], answer:4 },
    { id:"ca_090", question:"컴퓨터에서 명령어 집합(ISA: Instruction Set Architecture)에 포함되는 내용이 아닌 것은?", options:["명령어 형식","주소 지정 방식","레지스터 종류","운영체제 커널"], answer:4 },
    { id:"ca_091", question:"다음 중 부호있는 2진수에서 오버플로우(Overflow)가 발생하는 경우는?", options:["양수 + 음수","양수 + 양수 = 음수","음수 - 양수 = 양수","이 중 b와 c"], answer:4 },
    { id:"ca_092", question:"컴퓨터에서 병렬 처리(Parallel Processing)의 Flynn 분류에서 SIMD란?", options:["단일 명령어, 단일 데이터 스트림","단일 명령어, 다중 데이터 스트림","다중 명령어, 단일 데이터 스트림","다중 명령어, 다중 데이터 스트림"], answer:2 },
    { id:"ca_093", question:"다음 중 ROM(Read Only Memory)의 종류가 아닌 것은?", options:["EPROM","EEPROM","SRAM","Mask ROM"], answer:3 },
    { id:"ca_094", question:"컴퓨터에서 TLB(Translation Lookaside Buffer)의 역할은?", options:["캐시 데이터를 저장한다","가상 주소를 물리 주소로 변환하는 페이지 테이블의 캐시이다","인터럽트 벡터를 저장한다","명령어를 미리 가져온다"], answer:2 },
    { id:"ca_095", question:"다음 10진수를 2진수로 변환한 것으로 옳은 것은? 10진수 25 = ?", options:["10101","11001","11010","10110"], answer:2 },
    { id:"ca_096", question:"컴퓨터에서 채널(Channel)의 종류 중 하나의 채널이 여러 개의 저속 장치를 처리하는 것은?", options:["셀렉터 채널(Selector Channel)","멀티플렉서 채널(Multiplexer Channel)","블록 다중화 채널","DMA 채널"], answer:2 },
    { id:"ca_097", question:"다음 중 연산자(Operand)와 연산코드(Operation Code)를 포함하는 것은?", options:["데이터 레지스터","명령어(Instruction)","스택 포인터","프로그램 카운터"], answer:2 },
    { id:"ca_098", question:"컴퓨터에서 디코더(Decoder)의 기능은?", options:["여러 입력 중 하나를 선택하여 출력한다","n개의 입력을 2^n개의 출력 중 하나를 활성화한다","여러 입력을 하나의 출력으로 합친다","입력을 반전하여 출력한다"], answer:2 },
    { id:"ca_099", question:"다음 중 컴퓨터 시스템의 성능을 측정하는 단위 MIPS의 의미는?", options:["초당 메가 명령어 수","초당 메가 연산 수","초당 메가 비트 전송","초당 메가 바이트 전송"], answer:1 },
    { id:"ca_100", question:"컴퓨터에서 해밍 코드(Hamming Code)의 주요 기능은?", options:["데이터 압축","오류 검출 및 수정","데이터 암호화","빠른 정렬"], answer:2 }
],

  "운영체제": [
    { id:"os_001", question:"절대로더에서 각 기능과 수행 주체의 연결이 가장 옳지 않은 것은?", options:["연결-프로그래머","기억장소할당-로더","적재-로더","재비치-어셈블러"], answer:4 },
    { id:"os_002", question:"UNIX 운영체제에 관한 특징으로 가장 옳지 않은 것은?", options:["하나 이상의 작업에 대하여 백그라운드에서 수행 가능하다","Multi-User는 지원하지만 Multi-tasking은 지원하지 않는다","트리 구조의 파일 시스템을 갖는다","이식성이 높으며 장치 간의 호환성이 높다"], answer:2 },
    { id:"os_003", question:"3개의 페이지를 수용할 수 있는 주기억장치에서 FIFO 페이지 교체 알고리즘을 사용할 경우 참조 순서 1,2,3,1,2,4,1,2,5에서 페이지 부재 횟수는?", options:["4","5","6","7"], answer:3 },
    { id:"os_004", question:"빈 기억공간의 크기가 20K, 16K, 8K, 40K일 때 'Worst Fit' 전략으로 17K의 프로그램을 적재할 경우 내부 단편화의 크기는?", options:["3K","23K","44K","67K"], answer:2 },
    { id:"os_005", question:"스레드(Threads)에 관한 설명으로 옳지 않은 것은?", options:["하드웨어, 운영체제의 성능과 응용프로그램의 처리율을 향상시킬 수 있다","스레드는 그들이 속한 프로세스의 자원과 메모리를 공유한다","다중 프로세서 구조에서 각 스레드는 다른 프로세서에서 병렬로 실행될 수 있다","스레드는 동일 프로세스 환경에서 서로 다른 독립적인 다중수행이 불가능하다"], answer:4 },
    { id:"os_006", question:"교착상태의 해결 기법 중 일반적으로 자원의 낭비가 가장 심한 것은?", options:["교착상태의 예방","교착상태의 회피","교착상태의 발견","교착상태의 복구"], answer:1 },
    { id:"os_007", question:"PCB(Process Control Block)가 갖고 있는 정보가 아닌 것은?", options:["할당되지 않은 주변장치의 상태 정보","프로세스의 현재 상태","프로세스의 고유 식별자","스케줄링 및 프로세스의 우선순위"], answer:1 },
    { id:"os_008", question:"가상주소와 물리주소의 대응 관계로 가상주소로부터 물리주소를 찾아내는 것을 무엇이라고 하는가?", options:["스케줄링(Scheduling)","매핑(mapping)","버퍼링(buffering)","스왑-인(swap in)"], answer:2 },
    { id:"os_009", question:"다중처리(Multi-Processing) 시스템에 대한 설명으로 가장 적합한 것은?", options:["요구사항이 비슷한 여러 개의 작업을 모아서 한꺼번에 처리하는 방식이다","동시에 프로그램을 수행할 수 있는 CPU를 여러 개 두고 업무를 분담하여 처리하는 방식이다","시한성을 갖는 자료가 발생할 때마다 즉시 처리하여 결과를 출력하거나, 요구에 응답하는 방식이다","분산된 여러 개의 단말에 분담시켜 통신회선을 통하여 상호간에 교신, 처리하는 방식이다"], answer:2 },
    { id:"os_010", question:"UNIX의 쉘(Shell)에 대한 설명으로 가장 옳지 않은 것은?", options:["시스템과 사용자 간의 인터페이스를 담당한다","프로세스 관리, 파일관리, 입출력 관리, 기억장치 관리 등의 기능을 수행한다","명령어 해석기 역할을 한다","사용자의 명령어를 인식하여 프로그램을 호출한다"], answer:2 },
    { id:"os_011", question:"보안유지기법 중 하드웨어나 운영체제에 내장된 보안 기능을 이용하여 프로그램의 신뢰성 있는 운영과 데이터의 무결성 보장을 하는 기법은?", options:["외부보안","운용보안","사용자 인터페이스 보안","내부보안"], answer:4 },
    { id:"os_012", question:"다음 설명에 해당하는 디렉토리 구조는? [부 디렉토리의 공동 사용 가능, 디스크 공간 절약, 하나의 파일이 여러 경로 이름 가능, 공유 파일 제거 시 Dangling Pointer 문제 발생]", options:["비순환 그래프 디렉토리 시스템","트리구조 디렉토리 시스템","1단계 디렉토리 시스템","2단계 디렉토리 시스템"], answer:1 },
    { id:"os_013", question:"분산 처리 시스템의 네트워크 위상 중 [각 노드가 공평한 서비스를 받고, 새로운 노드 추가 시 통신 회선을 절단해야 하며, 단방향인 경우 최대 N-1개의 노드를 거쳐야 하는] 구조는?", options:["완전 연결 구조","계층 연결 구조","성형 구조","링형 구조"], answer:4 },
    { id:"os_014", question:"교착상태 발생 조건 중 [프로세스가 수행되기 전에 필요한 모든 자원을 할당, 자원이 점유되지 않은 상태에서만 자원 요구]를 제거하는 조건은?", options:["Mutual Exclusion","Hold and Wait","Non Preemption","Circular Wait"], answer:2 },
    { id:"os_015", question:"운영체제의 기능으로 가장 거리가 먼 것은?", options:["사용자의 편리한 환경 제공","처리능력 및 신뢰도 향상","컴퓨터 시스템의 성능 최적화","언어번역기능을 통한 실행 가능한 프로그램 생성"], answer:4 },
    { id:"os_016", question:"UNIX에서 각 파일에 대한 정보를 기억하고 있는 자료구조로서 파일 소유자의 식별번호, 파일 크기, 파일의 최종 수정시간, 파일 링크 수 등의 내용을 가지고 있는 것은?", options:["Super block","i-node","Directory","File system mounting"], answer:2 },
    { id:"os_017", question:"운영체제의 목적으로 적합하지 않은 것은?", options:["Throughput 향상","Turn around time 단축","Availability 감소","Reliability 향상"], answer:3 },
    { id:"os_018", question:"ISAM(Indexed Sequential Access Method)의 물리적 색인 구성 중 3단계 색인에 해당되지 않는 것은?", options:["Cylinder index","Track index","Master index","Volume index"], answer:4 },
    { id:"os_019", question:"라운드 로빈(Round Robin) 스케줄링에서 타임 슬라이스를 4초로 할 때 프로세스 A(실행시간 17초), B(4초), C(5초)의 평균 반환 시간은?", options:["12초","14초","17초","18초"], answer:2 },
    { id:"os_020", question:"교착상태 해결 기법 중 회피(Avoidance) 기법과 가장 밀접한 관계가 있는 것은?", options:["점유 및 대기 방지","비선점 방지","환형 대기 방지","은행원 알고리즘 사용"], answer:4 },
    { id:"os_021", question:"페이지 부재율(Page Fault Ratio)과 스래싱(Thrashing)의 관계에 대한 설명 중 가장 옳은 것은?", options:["페이지 부재율이 크면 스래싱이 많이 일어난 것이다","페이지 부재율과 스래싱은 관계가 없다","다중 프로그래밍의 정도가 높아지면 페이지 부재율과 스래싱이 감소한다","스래싱이 많이 발생하면 페이지 부재율이 감소한다"], answer:1 },
    { id:"os_022", question:"운영체제의 운용 기법 중 중앙 처리 장치의 시간을 각 사용자에게 균등하게 분할하여 라운드 로빈 스케줄링을 사용하는 것은?", options:["Real-Time Processing System","Time Sharing System","Batch Processing System","Distributed Processing System"], answer:2 },
    { id:"os_023", question:"상호배제(Mutual Exclusion)를 사용하여 임계영역을 보호할 때, 옳지 않은 것은?", options:["임계영역 내 명령어 실행 중 인터럽트 발생 시 다른 프로세스가 해당 영역의 명령어를 실행한다","임계영역 내에서 교착상태가 발생하면 해제될 때까지 벗어날 수 없다","무한 반복이 발생하면 임계영역을 탈출할 수 없으므로 임계영역 내에서는 무한 반복이 없어야 한다","하나의 프로세스만 임계영역을 사용하도록 하여 공유 변수 값의 무결성을 보장한다"], answer:1 },
    { id:"os_024", question:"Best Fit 전략으로 17K의 프로그램을 20K, 16K, 8K, 40K인 빈 공간에 배치할 때 내부 단편화의 크기는?", options:["3K","23K","64K","67K"], answer:1 },
    { id:"os_025", question:"시스템 소프트웨어의 역할로 가장 거리가 먼 것은?", options:["프로그램을 메모리에 적재한다","인터럽트를 관리한다","복잡한 수학 계산을 처리한다","기억 장치를 관리한다"], answer:3 },
    { id:"os_026", question:"운영체제의 기능으로 가장 거리가 먼 것은?", options:["사용자 인터페이스 제공","자원 스케줄링","데이터의 공유","원시 프로그램을 목적 프로그램으로 변환"], answer:4 },
    { id:"os_027", question:"프로세스의 상태 전이 순서로 올바른 것은?", options:["생성 → 준비 → 실행 → 대기 → 완료","생성 → 실행 → 준비 → 대기 → 완료","생성 → 대기 → 준비 → 실행 → 완료","생성 → 준비 → 대기 → 실행 → 완료"], answer:1 },
    { id:"os_028", question:"세마포어(Semaphore)에 대한 설명으로 옳지 않은 것은?", options:["임계 구역 문제를 해결하기 위한 동기화 도구이다","P 연산과 V 연산으로 구성된다","busy waiting 문제를 완전히 해결한다","다익스트라(Dijkstra)가 제안하였다"], answer:3 },
    { id:"os_029", question:"디스크 스케줄링 방법 중 헤드의 이동 거리가 가장 짧은 방법은?", options:["FCFS","SSTF","SCAN","LOOK"], answer:2 },
    { id:"os_030", question:"페이지 교체 알고리즘 중 향후 가장 오랫동안 사용되지 않을 페이지를 교체하는 최적 알고리즘은?", options:["FIFO","LRU","OPT","LFU"], answer:3 },
    { id:"os_031", question:"가상 메모리 시스템에서 작업 집합(Working Set) 모델의 목적은?", options:["페이지 테이블 크기를 줄이기 위해","스래싱을 방지하기 위해","디스크 공간을 절약하기 위해","프로세스 우선순위를 결정하기 위해"], answer:2 },
    { id:"os_032", question:"파일 시스템에서 연속 할당(Contiguous Allocation) 방식의 단점은?", options:["순차 접근이 불가능하다","내부 단편화가 발생한다","외부 단편화가 발생한다","파일 크기를 미리 알 수 없다"], answer:3 },
    { id:"os_033", question:"선점형(Preemptive) 스케줄링에 해당하지 않는 것은?", options:["라운드 로빈(Round Robin)","SRT(Shortest Remaining Time)","다단계 큐","FCFS"], answer:4 },
    { id:"os_034", question:"트리구조 디렉토리에 대한 설명으로 옳은 것은?", options:["UNIX에서 사용하는 디렉토리 구조","모든 파일이 하나의 디렉토리에 저장된다","두 개의 레벨로만 구성된다","파일 공유가 불가능하다"], answer:1 },
    { id:"os_035", question:"교착상태(Deadlock)가 발생하기 위한 필요충분조건이 아닌 것은?", options:["상호 배제(Mutual Exclusion)","점유와 대기(Hold and Wait)","선점(Preemption)","순환 대기(Circular Wait)"], answer:3 },
    { id:"os_036", question:"선점 스케줄링 알고리즘으로만 묶인 것은?", options:["FCFS, SJF","Round Robin, SRT","FCFS, Round Robin","SJF, 우선순위 스케줄링"], answer:2 },
    { id:"os_037", question:"캐시 기억장치를 주기억장치보다 먼저 참조하는 이유는?", options:["캐시 기억장치의 용량이 크기 때문에","캐시 기억장치의 접근 속도가 빠르기 때문에","캐시 기억장치의 비용이 저렴하기 때문에","캐시 기억장치가 비휘발성이기 때문에"], answer:2 },
    { id:"os_038", question:"다음 중 비선점(Non-Preemptive) 스케줄링 방법은?", options:["SRT(Shortest Remaining Time)","Round Robin","SJF(Shortest Job First)","다단계 큐"], answer:3 },
    { id:"os_039", question:"페이징(Paging) 기법과 세그멘테이션(Segmentation) 기법의 차이점으로 옳은 것은?", options:["페이징은 논리적 단위, 세그멘테이션은 고정 크기 단위이다","페이징은 고정 크기 단위, 세그멘테이션은 논리적 단위이다","페이징은 외부 단편화, 세그멘테이션은 내부 단편화가 발생한다","두 방법 모두 동일한 단위를 사용한다"], answer:2 },
    { id:"os_040", question:"UNIX 명령어 중 파일의 접근 권한을 변경하는 명령어는?", options:["chown","chmod","chgrp","chfile"], answer:2 },
    { id:"os_041", question:"커널(Kernel)에 대한 설명으로 옳지 않은 것은?", options:["운영체제의 핵심 부분이다","메모리 상주 부분이다","사용자와 직접 상호작용하는 부분이다","프로세스 관리, 메모리 관리 등의 기능을 담당한다"], answer:3 },
    { id:"os_042", question:"내부 단편화(Internal Fragmentation)가 발생하는 원인은?", options:["연속 메모리 할당 방식에서 남은 공간이 너무 작아 사용하지 못할 때","고정 분할 방식에서 할당된 공간이 실제 필요한 공간보다 클 때","페이지 교체 시 적절한 페이지를 찾지 못할 때","프로세스가 메모리를 반환하지 않을 때"], answer:2 },
    { id:"os_043", question:"다음 중 메모리 관리 기법에서 단편화를 줄이는 방법은?", options:["압축(Compaction)","스와핑(Swapping)","페이징(Paging)","세그멘테이션(Segmentation)"], answer:1 },
    { id:"os_044", question:"프로세스(Process)와 스레드(Thread)의 차이점으로 옳은 것은?", options:["프로세스는 자원을 공유하지 않지만 스레드는 같은 프로세스 내의 자원을 공유한다","스레드는 독립적인 메모리 공간을 갖는다","프로세스 전환보다 스레드 전환에 더 많은 오버헤드가 발생한다","스레드는 별도의 프로세스 제어 블록을 갖는다"], answer:1 },
    { id:"os_045", question:"실시간 운영체제(Real-Time OS)에서 가장 중요한 요소는?", options:["처리량(Throughput)","응답 시간(Response Time)","자원 활용도(Utilization)","공평성(Fairness)"], answer:2 },
    { id:"os_046", question:"SJF(Shortest Job First) 스케줄링의 단점은?", options:["CPU 활용률이 낮다","기아(Starvation) 현상이 발생할 수 있다","평균 대기 시간이 길다","구현이 복잡하다"], answer:2 },
    { id:"os_047", question:"운영체제에서 스풀링(Spooling)이란?", options:["주기억장치를 보조기억장치처럼 사용하는 것","고속 CPU와 저속 I/O 장치의 속도 차이를 줄이기 위한 버퍼링 기법","프로세스를 메모리에서 디스크로 내보내는 것","다중 프로세서를 활용하는 기법"], answer:2 },
    { id:"os_048", question:"운영체제에서 문맥 교환(Context Switching)이란?", options:["CPU가 현재 실행 중인 프로세스에서 다른 프로세스로 전환하는 것","메모리에서 프로세스를 디스크로 이동하는 것","인터럽트를 처리하는 것","프로세스를 생성하는 것"], answer:1 },
    { id:"os_049", question:"FCFS(First Come First Served) 스케줄링의 특징으로 옳은 것은?", options:["선점형 스케줄링이다","도착 순서대로 처리된다","가장 짧은 작업이 먼저 처리된다","우선순위가 높은 작업이 먼저 처리된다"], answer:2 },
    { id:"os_050", question:"운영체제에서 모니터(Monitor)에 대한 설명으로 옳은 것은?", options:["세마포어보다 더 낮은 수준의 동기화 도구이다","상호 배제를 자동으로 보장하는 고수준 동기화 도구이다","P와 V 연산을 사용한다","하나의 정수 변수로 구현된다"], answer:2 },
    { id:"os_051", question:"운영체제에서 교착상태 탐지(Detection) 알고리즘의 목적은?", options:["교착상태가 발생하지 않도록 예방한다","교착상태 가능성이 있으면 회피한다","교착상태가 발생했는지 확인한다","교착상태 발생 후 복구한다"], answer:3 },
    { id:"os_052", question:"다음 중 페이지 테이블(Page Table)에 저장되는 정보가 아닌 것은?", options:["프레임 번호","유효/무효 비트","접근 비트","프로세스 이름"], answer:4 },
    { id:"os_053", question:"운영체제에서 선점(Preemption)이란?", options:["프로세스가 자원을 자발적으로 반환하는 것","운영체제가 실행 중인 프로세스에서 CPU를 강제로 빼앗는 것","프로세스가 우선순위를 높이는 것","프로세스가 입출력을 요청하는 것"], answer:2 },
    { id:"os_054", question:"파일 시스템의 링크드 리스트 할당(Linked Allocation) 방식의 단점은?", options:["외부 단편화가 발생한다","직접 접근이 어렵다","파일 크기 변경이 불가능하다","연속된 공간이 필요하다"], answer:2 },
    { id:"os_055", question:"운영체제에서 교착상태 예방(Prevention) 기법 중 순환 대기(Circular Wait) 조건을 제거하는 방법은?", options:["한 번에 모든 자원을 요청한다","자원에 번호를 부여하고 순서대로만 요청한다","선점을 허용한다","자원을 독점하지 않는다"], answer:2 },
    { id:"os_056", question:"다음 중 LRU(Least Recently Used) 페이지 교체 알고리즘의 특징은?", options:["가장 오래 전에 사용된 페이지를 교체한다","가장 자주 사용된 페이지를 교체한다","가장 최근에 사용된 페이지를 교체한다","페이지를 순서대로 교체한다"], answer:1 },
    { id:"os_057", question:"운영체제에서 파이프(Pipe)의 특징은?", options:["양방향 통신이 가능하다","부모-자식 프로세스 간의 단방향 통신에 사용된다","네트워크를 통한 통신에 사용된다","공유 메모리 방식이다"], answer:2 },
    { id:"os_058", question:"다음 중 UNIX에서 프로세스를 강제로 종료하는 명령은?", options:["stop","kill","exit","terminate"], answer:2 },
    { id:"os_059", question:"운영체제에서 스와핑(Swapping)이란?", options:["캐시에 데이터를 저장하는 것","프로세스 전체를 메모리에서 디스크로 이동하는 것","페이지를 메모리에서 디스크로 이동하는 것","메모리를 압축하는 것"], answer:2 },
    { id:"os_060", question:"다음 중 운영체제의 스케줄링 기준으로 적합하지 않은 것은?", options:["CPU 이용률 최대화","처리량 최대화","반환 시간 최소화","프로그램 코드 크기 최소화"], answer:4 },
    { id:"os_061", question:"다음 중 임계 구역(Critical Section) 문제의 해결 조건이 아닌 것은?", options:["상호 배제(Mutual Exclusion)","진행(Progress)","한정 대기(Bounded Waiting)","선점(Preemption)"], answer:4 },
    { id:"os_062", question:"운영체제에서 좀비 프로세스(Zombie Process)란?", options:["실행이 멈춘 프로세스","실행이 종료됐지만 부모 프로세스가 종료 상태를 읽지 않은 프로세스","메모리를 과도하게 사용하는 프로세스","CPU를 독점하는 프로세스"], answer:2 },
    { id:"os_063", question:"다음 중 멀티스레딩(Multi-Threading)의 장점이 아닌 것은?", options:["응답성 향상","자원 공유 용이","보안성 향상","경제성"], answer:3 },
    { id:"os_064", question:"운영체제에서 페이지 폴트(Page Fault) 발생 시 처리 절차의 순서로 옳은 것은?", options:["페이지 폴트 감지 → 디스크에서 페이지 로드 → 페이지 테이블 업데이트 → 프로세스 재개","디스크에서 페이지 로드 → 페이지 폴트 감지 → 프로세스 재개 → 페이지 테이블 업데이트","페이지 폴트 감지 → 프로세스 재개 → 디스크에서 페이지 로드 → 페이지 테이블 업데이트","프로세스 재개 → 페이지 폴트 감지 → 페이지 테이블 업데이트 → 디스크에서 페이지 로드"], answer:1 },
    { id:"os_065", question:"운영체제에서 고아 프로세스(Orphan Process)란?", options:["부모 프로세스가 먼저 종료되어 부모가 없는 프로세스","CPU를 할당받지 못한 프로세스","메모리 부족으로 실행 중단된 프로세스","입출력 대기 중인 프로세스"], answer:1 },
    { id:"os_066", question:"다음 중 UNIX에서 프로세스 생성에 사용되는 시스템 호출은?", options:["exec()","fork()","wait()","exit()"], answer:2 },
    { id:"os_067", question:"운영체제에서 인터럽트(Interrupt)와 트랩(Trap)의 차이점은?", options:["인터럽트는 소프트웨어, 트랩은 하드웨어에 의해 발생한다","인터럽트는 외부 장치, 트랩은 현재 실행 중인 프로세스에 의해 발생한다","차이가 없다","인터럽트는 운영체제, 트랩은 사용자 프로그램이 발생시킨다"], answer:2 },
    { id:"os_068", question:"운영체제에서 프로세스 동기화를 위한 방법이 아닌 것은?", options:["세마포어","모니터","소켓","뮤텍스"], answer:3 },
    { id:"os_069", question:"다음 중 디스크 스케줄링 알고리즘 중 SCAN 알고리즘의 설명으로 옳은 것은?", options:["요청된 트랙을 순서대로 처리한다","헤드가 한쪽 끝에서 다른 쪽 끝으로 이동하면서 요청을 처리한다","가장 가까운 요청을 먼저 처리한다","임의의 순서로 요청을 처리한다"], answer:2 },
    { id:"os_070", question:"운영체제에서 반환 시간(Turnaround Time)의 의미는?", options:["프로세스가 준비 큐에서 대기하는 시간","프로세스가 생성되어 완료될 때까지의 시간","CPU가 실제로 프로세스를 처리하는 시간","프로세스가 입출력을 기다리는 시간"], answer:2 },
    { id:"os_071", question:"운영체제에서 가상 메모리의 장점이 아닌 것은?", options:["물리 메모리보다 큰 프로그램 실행 가능","메모리 접근 속도 향상","메모리 이용률 향상","여러 프로세스 간 메모리 공유 용이"], answer:2 },
    { id:"os_072", question:"다음 중 파일 시스템에서 FAT(File Allocation Table)의 역할은?", options:["파일 접근 권한을 관리한다","파일이 저장된 블록 위치를 관리한다","파일 암호화를 담당한다","파일 압축을 담당한다"], answer:2 },
    { id:"os_073", question:"운영체제에서 HRN(Highest Response ratio Next) 스케줄링에서 우선순위를 결정하는 공식은?", options:["(대기시간 + 서비스시간) / 서비스시간","서비스시간 / 대기시간","대기시간 / 서비스시간","(서비스시간 + 대기시간) × 서비스시간"], answer:1 },
    { id:"os_074", question:"운영체제에서 다중 레벨 큐(Multi-level Queue) 스케줄링의 특징으로 옳은 것은?", options:["모든 프로세스는 동일한 큐에 있다","프로세스를 여러 그룹으로 분류하여 각각 다른 큐에 배치한다","프로세스는 큐 간 이동이 자유롭다","비선점형 방식만 사용한다"], answer:2 },
    { id:"os_075", question:"운영체제에서 분산 시스템(Distributed System)의 특징이 아닌 것은?", options:["자원 공유","향상된 신뢰성","하나의 중앙 컴퓨터에 의존","계산 속도 향상"], answer:3 },
    { id:"os_076", question:"다음 중 운영체제에서 IPC(Inter-Process Communication) 방법이 아닌 것은?", options:["공유 메모리","메시지 패싱","소켓","컴파일러"], answer:4 },
    { id:"os_077", question:"운영체제에서 선점 우선순위 스케줄링에서 기아(Starvation)를 해결하는 방법은?", options:["프로세스를 강제 종료한다","에이징(Aging) 기법을 사용한다","모든 프로세스에 동일한 우선순위를 부여한다","선점을 금지한다"], answer:2 },
    { id:"os_078", question:"운영체제에서 세그멘테이션(Segmentation)의 장점은?", options:["내부 단편화가 없다","외부 단편화가 없다","페이지 테이블이 필요 없다","메모리 접근 속도가 빠르다"], answer:1 },
    { id:"os_079", question:"다음 중 운영체제에서 배치 처리(Batch Processing) 시스템의 특징은?", options:["대화형으로 즉시 응답한다","유사한 작업을 모아서 한꺼번에 처리한다","실시간 처리를 한다","분산 처리를 한다"], answer:2 },
    { id:"os_080", question:"운영체제에서 가상 메모리 구현에 사용되는 기법이 아닌 것은?", options:["페이징(Paging)","세그멘테이션(Segmentation)","페이지드 세그멘테이션","인터리빙(Interleaving)"], answer:4 },
    { id:"os_081", question:"다음 중 운영체제의 스케줄러 종류가 아닌 것은?", options:["장기 스케줄러","중기 스케줄러","단기 스케줄러","초단기 스케줄러"], answer:4 },
    { id:"os_082", question:"운영체제에서 프로세스가 준비 상태에서 실행 상태로 전이되는 것을 무엇이라 하는가?", options:["디스패치(Dispatch)","인터럽트(Interrupt)","블록(Block)","스왑 아웃(Swap Out)"], answer:1 },
    { id:"os_083", question:"운영체제에서 다중 프로그래밍(Multiprogramming)의 목적은?", options:["여러 사용자가 동시에 접근하는 것","CPU 이용률을 높이는 것","실시간 처리를 위한 것","보안을 강화하는 것"], answer:2 },
    { id:"os_084", question:"다음 중 UNIX의 파일 권한에서 rwxr-xr-- 에서 그룹의 권한은?", options:["rwx","r-x","r--","---"], answer:2 },
    { id:"os_085", question:"운영체제에서 동적 적재(Dynamic Loading)의 장점은?", options:["메모리 접근 속도가 빠르다","필요한 루틴만 메모리에 로드하여 메모리를 효율적으로 사용한다","프로그램 실행 전에 모든 루틴을 로드한다","메모리 관리가 단순해진다"], answer:2 },
    { id:"os_086", question:"운영체제에서 LFU(Least Frequently Used) 페이지 교체 알고리즘의 특징은?", options:["가장 최근에 사용된 페이지를 교체한다","사용 빈도가 가장 낮은 페이지를 교체한다","가장 오래된 페이지를 교체한다","무작위로 페이지를 교체한다"], answer:2 },
    { id:"os_087", question:"다음 중 운영체제에서 프로세스 간 통신에서 메시지 큐(Message Queue)의 특징으로 옳은 것은?", options:["단방향 통신만 가능하다","FIFO 방식으로 메시지를 전달한다","같은 컴퓨터 내에서만 사용 가능하다","연결형 통신 방식이다"], answer:2 },
    { id:"os_088", question:"운영체제에서 페이지 크기가 작을 때의 특징으로 옳지 않은 것은?", options:["내부 단편화가 줄어든다","페이지 테이블의 크기가 커진다","I/O 효율이 높아진다","페이지 폴트 발생 가능성이 높아진다"], answer:3 },
    { id:"os_089", question:"다음 중 UNIX/Linux에서 파일 입출력을 위한 시스템 콜이 아닌 것은?", options:["open()","read()","write()","print()"], answer:4 },
    { id:"os_090", question:"운영체제에서 메모리 보호(Memory Protection)의 목적은?", options:["메모리 접근 속도를 높이기 위해","한 프로세스가 다른 프로세스의 메모리 영역에 접근하지 못하도록 하기 위해","메모리 용량을 늘리기 위해","메모리 단편화를 방지하기 위해"], answer:2 },
    { id:"os_091", question:"다음 중 운영체제에서 임계 구역의 특징으로 옳은 것은?", options:["여러 프로세스가 동시에 진입 가능하다","한 번에 하나의 프로세스만 진입 가능하다","운영체제만 접근 가능하다","인터럽트 처리 중에만 진입 가능하다"], answer:2 },
    { id:"os_092", question:"운영체제에서 교착상태 발생 조건 중 비선점(Non-Preemption) 조건이란?", options:["프로세스가 자원을 요청할 때 다른 자원을 보유하고 있다","자원을 강제로 빼앗을 수 없다","여러 프로세스가 자원을 순환하여 대기한다","자원은 한 번에 한 프로세스만 사용한다"], answer:2 },
    { id:"os_093", question:"운영체제에서 인터럽트 처리 시 저장해야 하는 레지스터 정보를 무엇이라 하는가?", options:["PCB(Process Control Block)","레지스터 파일","문맥(Context)","스택 프레임"], answer:3 },
    { id:"os_094", question:"다음 중 운영체제에서 동적 분할(Dynamic Partitioning) 방식의 단점은?", options:["내부 단편화가 심하다","외부 단편화가 발생한다","프로그램 크기가 고정되어야 한다","동시에 하나의 프로세스만 실행 가능하다"], answer:2 },
    { id:"os_095", question:"운영체제에서 교착상태 회피에 사용되는 은행원 알고리즘(Banker's Algorithm)의 전제 조건은?", options:["자원의 종류와 수가 미리 정해져 있지 않아도 된다","각 프로세스의 최대 자원 요구량이 사전에 알려져야 한다","모든 자원이 공유 가능해야 한다","프로세스 수가 고정되지 않아도 된다"], answer:2 },
    { id:"os_096", question:"다음 중 운영체제에서 시스템 호출(System Call)에 대한 설명으로 옳은 것은?", options:["사용자 프로그램이 직접 하드웨어를 제어한다","사용자 프로그램이 운영체제 서비스를 요청하는 인터페이스이다","운영체제가 사용자 프로그램을 직접 호출한다","하드웨어가 운영체제에 서비스를 요청한다"], answer:2 },
    { id:"os_097", question:"운영체제에서 SSTF(Shortest Seek Time First) 디스크 스케줄링의 단점은?", options:["헤드 이동 거리가 길다","기아(Starvation) 현상이 발생할 수 있다","구현이 복잡하다","처리량이 낮다"], answer:2 },
    { id:"os_098", question:"운영체제에서 fork() 시스템 호출의 특징으로 옳은 것은?", options:["부모 프로세스의 코드만 복사한다","부모 프로세스와 동일한 복사본 프로세스를 생성한다","자식 프로세스의 PID는 항상 0이다","fork() 후 부모 프로세스는 종료된다"], answer:2 },
    { id:"os_099", question:"운영체제에서 다단계 피드백 큐(Multi-level Feedback Queue) 스케줄링의 특징으로 옳은 것은?", options:["프로세스가 큐 사이를 이동할 수 없다","프로세스의 행동에 따라 다른 큐로 이동할 수 있다","모든 프로세스에 동일한 타임 퀀텀을 부여한다","비선점 방식만 사용한다"], answer:2 },
    { id:"os_100", question:"운영체제에서 스레드(Thread)의 장점으로 옳지 않은 것은?", options:["같은 프로세스의 스레드 간 자원 공유가 용이하다","프로세스 생성보다 스레드 생성 오버헤드가 작다","하나의 스레드 오류가 다른 스레드에 영향을 주지 않는다","멀티 코어 환경에서 병렬 처리가 가능하다"], answer:3 }
],

  "소프트웨어공학": [
    { id:"se_001", question:"실시간 소프트웨어 설계 시 고려해야 할 사항이 아닌 것은?", options:["인터럽트와 문맥 교환의 표현","태스크들 간의 통신과 동기화","동기적인 프로세싱","타이밍 제약의 표현"], answer:3 },
    { id:"se_002", question:"하향식 통합 테스트 수행을 위해 일시적으로 필요한 조건만을 가지고 임시로 제공되는 시험용 모듈의 명칭은?", options:["alpha","builder","cluster","stub"], answer:4 },
    { id:"se_003", question:"NS차트(Nassi-Schneiderman chart)에 대한 설명으로 가장 옳지 않은 것은?", options:["논리의 기술에 중점을 두고 도형을 이용한 표현 방법이다","이해하기 쉽고 코드 변환이 용이하다","화살표나 GOTO를 사용하여 이해하기 쉽다","연속, 선택, 반복 등의 제어 논리 구조를 표현한다"], answer:3 },
    { id:"se_004", question:"Rumbaugh의 모델링에서 상태도와 자료흐름도는 각각 어떤 모델링과 관련이 있는가?", options:["상태도-동적 모델링, 자료 흐름도-기능 모델링","상태도-기능 모델링, 자료 흐름도-동적 모델링","상태도-객체 모델링, 자료 흐름도-기능 모델링","상태도-객체 모델링, 자료 흐름도-동적 모델링"], answer:1 },
    { id:"se_005", question:"화이트박스 검사로 찾기 힘든 오류는?", options:["논리흐름도","자료구조","루프구조","순환복잡도"], answer:2 },
    { id:"se_006", question:"소프트웨어 개발 과정에서 사용되는 요구분석, 설계, 구현, 검사 및 디버깅 과정 전체 또는 일부를 컴퓨터와 전용의 소프트웨어 도구를 사용하여 자동화하는 것은?", options:["CAD(Computer Aided Design)","CAI(Computer Aided Instruction)","CAT(Computer Aided Testing)","CASE(Computer Aided Software Engineering)"], answer:4 },
    { id:"se_007", question:"소프트웨어 재사용에 대한 설명으로 가장 옳은 것은?", options:["프로젝트 실패의 위험을 증가시킨다","소프트웨어를 재사용함으로써 유지보수 비용이 높아진다","모든 소프트웨어를 재사용해야 한다","소프트웨어의 개발 생산성과 품질을 높이려는 주요 방법이다"], answer:4 },
    { id:"se_008", question:"소프트웨어 비용 산정 기법 중 산정 요원과 조정자에 의해 산정하는 방법은?", options:["기능 점수 기법","LOC 기법","COCOMO 기법","델파이 기법"], answer:4 },
    { id:"se_009", question:"자료사전에서 자료의 연결(and)을 나타내는 기호는?", options:["+","=","( )","{ }"], answer:1 },
    { id:"se_010", question:"다음 중 가장 높은 응집도(Cohesion)에 해당하는 것은?", options:["순서적 응집도(Sequential Cohesion)","시간적 응집도(Temporal Cohesion)","논리적 응집도(Logical Cohesion)","절차적 응집도(Procedural Cohesion)"], answer:1 },
    { id:"se_011", question:"소프트웨어 생명 주기에서 가장 많은 비용이 소요되는 단계는?", options:["계획단계","유지보수단계","분석단계","구현단계"], answer:2 },
    { id:"se_012", question:"소프트웨어 품질 관리 기술에서 품질 목표와 항목과 가장 거리가 먼 것은?", options:["정확성","종속성","유연성","무결성"], answer:2 },
    { id:"se_013", question:"시스템에서 모듈 사이의 결합도(Coupling)에 대한 설명으로 옳은 것은?", options:["한 모듈 내에 있는 처리요소들 사이의 기능적인 연관 정도를 나타낸다","결합도를 높이면 시스템 구현 및 유지보수 작업이 용이해진다","모듈간의 결합도를 약하게 하면 모듈 독립성이 향상된다","자료결합도는 내용결합도 보다 결합도가 높다"], answer:3 },
    { id:"se_014", question:"DFD(Data Flow Diagram)에 대한 설명으로 거리가 먼 것은?", options:["단말(Terminator)은 원으로 표기한다","구조적 분석 기법에 이용된다","자료 흐름과 기능을 자세히 표현하기 위해 단계적으로 세분화된다","자료 흐름 그래프 또는 버블(Bubble)차트라고도 한다"], answer:1 },
    { id:"se_015", question:"소프트웨어 품질 목표 중 요구되는 기능을 수행하기 위해 필요한 자원의 소요 정도를 의미하는 것은?", options:["Usability","Reliability","Efficiency","Functionality"], answer:3 },
    { id:"se_016", question:"객체에게 어떤 행위를 하도록 지시하는 명령은?", options:["Class","Instance","Object","Message"], answer:4 },
    { id:"se_017", question:"소프트웨어의 위기 현상과 가장 거리가 먼 것은?", options:["개발 인력의 급증","유지보수의 어려움","개발 기간의 지연 및 개발 비용의 증가","신기술에 대한 교육과 훈련의 부족"], answer:1 },
    { id:"se_018", question:"자료 사전에서 기호 '( )'의 의미는?", options:["정의","생략","선택","반복"], answer:3 },
    { id:"se_019", question:"소프트웨어 생명주기 모형 중 Boehm이 제시한 고전적 생명주기 모형으로서 선형 순차적 모델이라고도 하며, 타당성 검토, 계획, 요구사항 분석, 설계, 구현, 테스트, 유지보수의 단계를 통해 소프트웨어를 개발하는 모형은?", options:["폭포수 모형","프로토타입 모형","나선형 모형","RAD 모형"], answer:1 },
    { id:"se_020", question:"블랙박스 테스트를 이용하여 발견할 수 있는 오류의 경우로 가장 거리가 먼 것은?", options:["비정상적인 자료를 입력해도 오류 처리를 수행하지 않는 경우","정상적인 자료를 입력해도 요구된 기능이 제대로 수행되지 않는 경우","반복 조건을 만족하는데도 루프 내의 문장이 수행되지 않는 경우","경계값을 입력할 경우 요구된 출력 결과가 나오지 않는 경우"], answer:3 },
    { id:"se_021", question:"소프트웨어 공학에 대한 설명으로 가장 적합한 것은?", options:["소프트웨어의 제작부터 운영까지 생산성을 높이기 위해 기술적, 인간적인 요소에 대한 방법론을 제공한다","소프트웨어의 설계, 제작, 운영에 있어서 인간적인 요소를 배제한 프로그래밍 자체에 대한 공학적 연구를 의미한다","소프트웨어의 공학적이고 기술적인 영향을 사회 경제적인 시각에서만 설명한다","소프트웨어의 위기를 해결하기 위해서 현재 이미 해결된 문제들에 대해서 역사적 관점을 설명한다"], answer:1 },
    { id:"se_022", question:"시스템의 구성 요소 중 출력된 결과가 예정된 목표를 만족시키지 못할 경우 목표 달성을 위해 반복 처리하는 것을 의미하는 것은?", options:["Process","Feedback","Control","Output"], answer:2 },
    { id:"se_023", question:"객체지향 개발 과정에 대한 설명으로 가장 거리가 먼 것은?", options:["분석 단계에서는 객체의 이름과 상태, 행위들을 개념적으로 파악한다","설계 단계에서는 객체의 속성과 연산으로 정의하고 접근 방법을 구체화한다","구현 단계에서는 클래스를 절차적 프로그래밍 언어로 기술한다","테스트 단계에서는 클래스 단위 테스트와 시스템 테스트를 진행한다"], answer:3 },
    { id:"se_024", question:"럼바우의 분석 기법 중 자료 흐름도(DFD)를 이용하는 것은?", options:["기능 모델링","동적 모델링","객체 모델링","정적 모델링"], answer:1 },
    { id:"se_025", question:"객체지향에서 정보 은닉과 가장 밀접한 관계가 있는 것은?", options:["Encapsulation","Class","Method","Instance"], answer:1 },
    { id:"se_026", question:"소프트웨어 프로젝트 계획 수립 시 소프트웨어 영역(software scope) 결정사항에 기술되어야 할 주요사항으로 가장 거리가 먼 것은?", options:["인적자원","기능","제약조건","인터페이스"], answer:1 },
    { id:"se_027", question:"COCOMO(Constructive Cost Model) 모형에 대한 설명으로 옳지 않은 것은?", options:["산정 결과는 프로젝트를 완성하는데 필요한 man-month로 나타난다","보헴(Boehm)이 제안한 것으로 원시코드 라인 수에 의한 비용 산정 기법이다","비용견적의 유연성이 높아 소프트웨어 개발비 견적에 널리 통용되고 있다","프로젝트 개발유형에 따라 object, dynamic, function의 3가지 모드로 구분한다"], answer:4 },
    { id:"se_028", question:"모듈의 결합도 중 가장 낮은 결합도(좋은 설계)는?", options:["내용 결합도(Content Coupling)","공통 결합도(Common Coupling)","자료 결합도(Data Coupling)","제어 결합도(Control Coupling)"], answer:3 },
    { id:"se_029", question:"테스트 케이스(Test Case)에 포함되어야 할 항목이 아닌 것은?", options:["테스트 조건","테스트 데이터","예상 결과","소스 코드"], answer:4 },
    { id:"se_030", question:"나선형 모델(Spiral Model)에서 반복되는 4가지 활동의 순서로 옳은 것은?", options:["계획 → 위험 분석 → 개발 → 고객 평가","위험 분석 → 계획 → 개발 → 고객 평가","개발 → 위험 분석 → 계획 → 고객 평가","계획 → 개발 → 위험 분석 → 고객 평가"], answer:1 },
    { id:"se_031", question:"UML(Unified Modeling Language)에서 클래스 다이어그램이 속하는 다이어그램 종류는?", options:["행동(Behavioral) 다이어그램","구조(Structural) 다이어그램","상호작용(Interaction) 다이어그램","상태(State) 다이어그램"], answer:2 },
    { id:"se_032", question:"소프트웨어 유지보수의 유형 중 소프트웨어의 오류를 수정하는 유지보수는?", options:["수정 유지보수(Corrective Maintenance)","적응 유지보수(Adaptive Maintenance)","완전화 유지보수(Perfective Maintenance)","예방 유지보수(Preventive Maintenance)"], answer:1 },
    { id:"se_033", question:"소프트웨어 설계에서 응집도(Cohesion)가 가장 높은 것은?", options:["논리적 응집도(Logical Cohesion)","시간적 응집도(Temporal Cohesion)","기능적 응집도(Functional Cohesion)","절차적 응집도(Procedural Cohesion)"], answer:3 },
    { id:"se_034", question:"요구사항 명세서(SRS: Software Requirements Specification)의 특성이 아닌 것은?", options:["완전성(Completeness)","일관성(Consistency)","모호성(Ambiguity)","검증 가능성(Verifiability)"], answer:3 },
    { id:"se_035", question:"객체지향 프로그래밍에서 상속(Inheritance)에 대한 설명으로 옳지 않은 것은?", options:["기존 클래스의 속성과 메서드를 재사용할 수 있다","코드 재사용성을 높인다","부모 클래스는 자식 클래스의 속성을 상속받는다","계층적 분류를 가능하게 한다"], answer:3 },
    { id:"se_036", question:"소프트웨어 테스트에서 알파(Alpha) 테스트와 베타(Beta) 테스트에 대한 설명으로 옳은 것은?", options:["알파 테스트는 사용자 환경에서, 베타 테스트는 개발자 환경에서 수행한다","알파 테스트는 개발자 환경에서, 베타 테스트는 사용자 환경에서 수행한다","알파 테스트와 베타 테스트 모두 개발자가 수행한다","알파 테스트와 베타 테스트는 동일한 테스트 방법이다"], answer:2 },
    { id:"se_037", question:"소프트웨어 형상 관리(Software Configuration Management)의 기능이 아닌 것은?", options:["형상 식별","형상 통제","형상 감사","형상 개발"], answer:4 },
    { id:"se_038", question:"CPM(Critical Path Method)에 대한 설명으로 옳은 것은?", options:["프로젝트 완료에 가장 오래 걸리는 경로를 찾는 방법이다","비용이 가장 적게 드는 경로를 찾는 방법이다","자원 할당을 최적화하는 방법이다","품질 관리를 위한 방법이다"], answer:1 },
    { id:"se_039", question:"소프트웨어 재공학(Software Reengineering)의 주요 활동이 아닌 것은?", options:["역공학(Reverse Engineering)","재구조화(Restructuring)","순공학(Forward Engineering)","신규 개발(New Development)"], answer:4 },
    { id:"se_040", question:"구조적 프로그래밍(Structured Programming)에서 사용하는 기본 제어 구조가 아닌 것은?", options:["순차(Sequence)","선택(Selection)","반복(Iteration)","GOTO"], answer:4 },
    { id:"se_041", question:"소프트웨어 품질 특성(ISO/IEC 9126) 중 지정된 조건에서 소프트웨어가 성능 수준을 유지하는 능력은?", options:["기능성(Functionality)","신뢰성(Reliability)","사용성(Usability)","효율성(Efficiency)"], answer:2 },
    { id:"se_042", question:"프로토타입(Prototype) 모형에 대한 설명으로 옳지 않은 것은?", options:["사용자 요구사항을 파악하기 위해 시제품을 개발한다","사용자와 개발자 모두에게 공동의 참조 모델을 제공한다","요구사항을 충실히 반영할 수 있다","대형 시스템의 전체 개발 방법으로 적합하다"], answer:4 },
    { id:"se_043", question:"소프트웨어 위험(Risk) 관리에서 위험을 사전에 파악하고 분석하는 활동은?", options:["위험 식별","위험 추정","위험 평가","위험 통제"], answer:1 },
    { id:"se_044", question:"객체지향의 기본 개념 중 같은 클래스에 속하는 각각의 객체를 의미하는 것은?", options:["클래스(Class)","인스턴스(Instance)","메시지(Message)","메서드(Method)"], answer:2 },
    { id:"se_045", question:"소프트웨어 개발 방법론 중 XP(eXtreme Programming)의 핵심 가치가 아닌 것은?", options:["의사소통(Communication)","단순성(Simplicity)","문서화(Documentation)","피드백(Feedback)"], answer:3 },
    { id:"se_046", question:"소프트웨어 테스트에서 경계값 분석(Boundary Value Analysis)은 어느 테스트 기법에 속하는가?", options:["화이트박스 테스트","블랙박스 테스트","회귀 테스트","통합 테스트"], answer:2 },
    { id:"se_047", question:"UML에서 시퀀스 다이어그램(Sequence Diagram)이 나타내는 것은?", options:["클래스 간의 정적 관계","객체 간의 시간에 따른 메시지 흐름","시스템의 상태 변화","데이터 흐름"], answer:2 },
    { id:"se_048", question:"소프트웨어 모듈의 결합도 유형 중 가장 결합도가 높은(나쁜 설계) 것은?", options:["자료 결합도","스탬프 결합도","제어 결합도","내용 결합도"], answer:4 },
    { id:"se_049", question:"애자일(Agile) 소프트웨어 개발 방법론의 특징이 아닌 것은?", options:["변화에 적응하는 것을 중시한다","지속적인 고객 참여를 강조한다","상세한 문서화를 최우선으로 한다","반복적이고 점진적인 개발을 수행한다"], answer:3 },
    { id:"se_050", question:"소프트웨어 테스트에서 동치 분할(Equivalence Partitioning)의 목적은?", options:["모든 코드 경로를 실행한다","입력 데이터를 유사한 그룹으로 나누어 각 그룹 대표값으로 테스트한다","성능을 측정한다","보안 취약점을 찾는다"], answer:2 },
    { id:"se_051", question:"소프트웨어 개발에서 디자인 패턴(Design Pattern)의 목적은?", options:["특정 언어에서만 사용되는 코딩 기법","반복적으로 발생하는 설계 문제의 검증된 해결책 제공","컴파일러 최적화 기법","데이터베이스 설계 방법"], answer:2 },
    { id:"se_052", question:"GoF(Gang of Four) 디자인 패턴의 분류가 아닌 것은?", options:["생성(Creational) 패턴","구조(Structural) 패턴","행위(Behavioral) 패턴","통신(Communication) 패턴"], answer:4 },
    { id:"se_053", question:"소프트웨어 유지보수 유형 중 소프트웨어를 환경 변화에 맞게 수정하는 것은?", options:["수정 유지보수","적응 유지보수","완전화 유지보수","예방 유지보수"], answer:2 },
    { id:"se_054", question:"소프트웨어 테스트에서 화이트박스 테스트의 기준이 아닌 것은?", options:["문장 커버리지","분기 커버리지","조건 커버리지","기능 커버리지"], answer:4 },
    { id:"se_055", question:"UML 다이어그램 중 유즈케이스 다이어그램(Use Case Diagram)이 표현하는 것은?", options:["시스템의 내부 구조","사용자와 시스템 간의 상호작용","객체 간의 메시지 흐름","클래스 간의 관계"], answer:2 },
    { id:"se_056", question:"소프트웨어 품질 보증(SQA: Software Quality Assurance)의 목적은?", options:["프로젝트 비용을 최소화한다","소프트웨어가 기준에 맞게 개발되고 있는지 확인한다","개발 속도를 높인다","팀 간 의사소통을 향상시킨다"], answer:2 },
    { id:"se_057", question:"소프트웨어 개발 방법론 중 스크럼(Scrum)에서 스프린트(Sprint)란?", options:["팀 미팅","짧은 개발 주기 (1~4주)","제품 백로그 항목","고객 검토 회의"], answer:2 },
    { id:"se_058", question:"PERT(Program Evaluation and Review Technique) 차트에 대한 설명으로 옳은 것은?", options:["막대 그래프로 일정을 표현한다","작업 간의 의존 관계와 소요 시간을 네트워크로 표현한다","클래스 관계를 표현한다","데이터 흐름을 표현한다"], answer:2 },
    { id:"se_059", question:"소프트웨어 개발에서 리팩토링(Refactoring)이란?", options:["소프트웨어 기능을 추가하는 것","외부 동작은 유지하면서 내부 코드 구조를 개선하는 것","소프트웨어를 완전히 재개발하는 것","소프트웨어를 테스트하는 것"], answer:2 },
    { id:"se_060", question:"소프트웨어 테스트에서 회귀 테스트(Regression Test)의 목적은?", options:["새로운 기능을 테스트한다","수정 후 기존 기능이 여전히 올바르게 동작하는지 확인한다","성능을 측정한다","보안을 테스트한다"], answer:2 },
    { id:"se_061", question:"객체지향에서 다형성(Polymorphism)에 대한 설명으로 옳은 것은?", options:["하나의 클래스에서만 하나의 형태로 동작한다","동일한 메시지에 대해 객체의 타입에 따라 다르게 반응할 수 있다","상속을 통해서만 구현 가능하다","컴파일 타임에만 결정된다"], answer:2 },
    { id:"se_062", question:"소프트웨어 개발에서 TDD(Test-Driven Development)의 순서로 옳은 것은?", options:["코드 작성 → 테스트 작성 → 리팩토링","테스트 작성 → 코드 작성 → 리팩토링","리팩토링 → 테스트 작성 → 코드 작성","코드 작성 → 리팩토링 → 테스트 작성"], answer:2 },
    { id:"se_063", question:"소프트웨어 공학에서 WBS(Work Breakdown Structure)란?", options:["소프트웨어 아키텍처 설계 방법","프로젝트 작업을 계층적으로 분해한 구조","소프트웨어 테스트 방법","코드 품질 측정 도구"], answer:2 },
    { id:"se_064", question:"다음 중 블랙박스 테스트 기법이 아닌 것은?", options:["동치 분할","경계값 분석","원인-결과 그래프","조건 커버리지"], answer:4 },
    { id:"se_065", question:"소프트웨어 아키텍처 패턴 중 클라이언트가 서버에 서비스를 요청하는 구조는?", options:["파이프-필터 패턴","클라이언트-서버 패턴","계층화 패턴","이벤트 기반 패턴"], answer:2 },
    { id:"se_066", question:"소프트웨어 개발에서 형상 관리(Configuration Management)의 대상이 아닌 것은?", options:["소스 코드","테스트 케이스","설계 문서","개발자 개인 일정"], answer:4 },
    { id:"se_067", question:"UML에서 클래스 다이어그램의 관계 중 포함(Composition) 관계의 의미는?", options:["부분이 전체 없이 독립적으로 존재 가능","부분이 전체에 강하게 속하며 전체 삭제 시 부분도 삭제","단순한 사용 관계","상속 관계"], answer:2 },
    { id:"se_068", question:"소프트웨어 테스트에서 통합 테스트(Integration Test) 방법이 아닌 것은?", options:["하향식 통합","상향식 통합","빅뱅 통합","단위 테스트"], answer:4 },
    { id:"se_069", question:"소프트웨어 프로젝트 관리에서 마일스톤(Milestone)이란?", options:["프로젝트의 중요한 완료 시점","프로젝트 비용 단위","팀 구성원의 역할","소프트웨어 버전 번호"], answer:1 },
    { id:"se_070", question:"객체지향에서 추상화(Abstraction)의 의미는?", options:["객체의 모든 세부 사항을 표현하는 것","불필요한 세부 사항을 숨기고 핵심 특성만 표현하는 것","여러 클래스에서 공통 기능을 상속받는 것","클래스를 객체로 생성하는 것"], answer:2 },
    { id:"se_071", question:"소프트웨어 개발에서 CI/CD(Continuous Integration/Continuous Deployment)의 목적은?", options:["코드 변경을 자주 통합하고 자동으로 배포하는 것","상세한 문서를 자동 생성하는 것","보안 취약점을 자동으로 수정하는 것","성능을 자동으로 최적화하는 것"], answer:1 },
    { id:"se_072", question:"소프트웨어 유지보수 중 가장 많은 비중을 차지하는 유형은?", options:["수정 유지보수","적응 유지보수","완전화 유지보수","예방 유지보수"], answer:3 },
    { id:"se_073", question:"소프트웨어 아키텍처 패턴 중 데이터 변환 처리에 적합한 것은?", options:["클라이언트-서버 패턴","파이프-필터 패턴","계층화 패턴","마이크로서비스 패턴"], answer:2 },
    { id:"se_074", question:"소프트웨어 테스트에서 시스템 테스트(System Test)는 어떤 수준의 테스트인가?", options:["개별 모듈 테스트","모듈 간 통합 테스트","완성된 전체 시스템 테스트","사용자 환경에서의 테스트"], answer:3 },
    { id:"se_075", question:"소프트웨어 개발에서 페어 프로그래밍(Pair Programming)이란?", options:["두 명이 하나의 컴퓨터에서 함께 코드를 작성하는 것","두 개의 프로젝트를 동시에 진행하는 것","두 팀이 경쟁하여 개발하는 것","두 언어로 동시에 개발하는 것"], answer:1 },
    { id:"se_076", question:"소프트웨어 품질 요소 중 주어진 시간 내에 주어진 기능을 수행할 확률은?", options:["효율성(Efficiency)","신뢰성(Reliability)","이식성(Portability)","사용성(Usability)"], answer:2 },
    { id:"se_077", question:"소프트웨어 개발 생명주기에서 타당성 분석(Feasibility Study)의 목적은?", options:["요구사항을 문서화하는 것","프로젝트가 실현 가능한지 평가하는 것","소프트웨어를 테스트하는 것","소프트웨어를 배포하는 것"], answer:2 },
    { id:"se_078", question:"소프트웨어 테스트에서 오류 추측(Error Guessing) 기법은?", options:["코드 구조를 분석하는 기법","테스터의 경험을 바탕으로 오류가 발생할 가능성이 있는 부분을 테스트하는 기법","입력 데이터를 동등 분류로 나누는 기법","경계값을 테스트하는 기법"], answer:2 },
    { id:"se_079", question:"소프트웨어 개발에서 코드 인스펙션(Code Inspection)의 목적은?", options:["코드를 자동으로 실행하는 것","동료 검토를 통해 소스 코드의 결함을 찾는 것","코드를 최적화하는 것","코드를 문서화하는 것"], answer:2 },
    { id:"se_080", question:"소프트웨어 설계에서 모듈화(Modularity)의 이점이 아닌 것은?", options:["개발의 용이성","유지보수의 용이성","재사용성 향상","실행 속도 향상"], answer:4 },
    { id:"se_081", question:"UML에서 액티비티 다이어그램(Activity Diagram)이 표현하는 것은?", options:["클래스의 정적 구조","객체 생명주기","작업 흐름 및 제어 흐름","배포 구조"], answer:3 },
    { id:"se_082", question:"소프트웨어 개발에서 버전 관리 시스템(VCS)의 목적은?", options:["코드 실행 속도를 높이는 것","소스 코드의 변경 이력을 추적하고 관리하는 것","코드를 자동으로 최적화하는 것","보안 취약점을 찾는 것"], answer:2 },
    { id:"se_083", question:"소프트웨어 아키텍처에서 MVC(Model-View-Controller) 패턴의 구성 요소 중 비즈니스 로직을 담당하는 것은?", options:["View","Controller","Model","Service"], answer:3 },
    { id:"se_084", question:"소프트웨어 개발에서 사용자 스토리(User Story)는 어떤 방법론에서 주로 사용되는가?", options:["폭포수 모형","애자일 방법론","나선형 모형","RAD 모형"], answer:2 },
    { id:"se_085", question:"소프트웨어 테스트에서 수락 테스트(Acceptance Test)의 주체는?", options:["개발자","QA 팀","최종 사용자 또는 고객","시스템 관리자"], answer:3 },
    { id:"se_086", question:"소프트웨어 개발에서 정적 분석(Static Analysis)이란?", options:["소프트웨어를 실행하여 테스트하는 것","소프트웨어를 실행하지 않고 코드를 분석하는 것","성능을 측정하는 것","사용자 인터페이스를 평가하는 것"], answer:2 },
    { id:"se_087", question:"소프트웨어 공학에서 FP(Function Point) 방법의 특징은?", options:["코드 라인 수로 크기를 측정한다","기능의 복잡도를 기반으로 소프트웨어 크기를 측정한다","개발 기간으로 비용을 산정한다","개발자 수로 비용을 산정한다"], answer:2 },
    { id:"se_088", question:"소프트웨어 설계에서 팬인(Fan-In)과 팬아웃(Fan-Out)에 대한 설명으로 옳은 것은?", options:["팬인이 높고 팬아웃이 낮은 모듈이 좋은 설계이다","팬인이 낮고 팬아웃이 높은 모듈이 좋은 설계이다","팬인은 모듈을 호출하는 모듈 수, 팬아웃은 호출하는 모듈 수이다","팬인이 높을수록 모듈의 독립성이 낮다"], answer:3 },
    { id:"se_089", question:"소프트웨어 개발 방법론 중 칸반(Kanban)의 특징은?", options:["정해진 스프린트 기간에 작업을 완료한다","작업 흐름을 시각화하고 진행 중인 작업 수를 제한한다","매일 스탠드업 미팅을 필수로 한다","역할을 스크럼 마스터, 제품 소유자 등으로 구분한다"], answer:2 },
    { id:"se_090", question:"소프트웨어 테스트에서 스모크 테스트(Smoke Test)의 목적은?", options:["전체 기능을 상세히 테스트한다","소프트웨어의 기본 기능이 동작하는지 빠르게 확인한다","성능을 측정한다","보안을 테스트한다"], answer:2 },
    { id:"se_091", question:"객체지향의 캡슐화(Encapsulation)의 장점이 아닌 것은?", options:["정보 은닉","코드 재사용성","실행 속도 향상","유지보수 용이"], answer:3 },
    { id:"se_092", question:"소프트웨어 품질 측정 지표 중 결함 밀도(Defect Density)의 의미는?", options:["단위 크기당 결함의 수","테스트 케이스 수","수정된 결함의 수","발견된 결함의 심각도"], answer:1 },
    { id:"se_093", question:"소프트웨어 개발에서 SDLC(Software Development Life Cycle)의 기본 단계가 아닌 것은?", options:["요구사항 분석","설계","구현","마케팅"], answer:4 },
    { id:"se_094", question:"소프트웨어 유지보수 중 예방 유지보수(Preventive Maintenance)란?", options:["발생한 오류를 수정하는 것","미래의 문제를 예방하기 위해 소프트웨어를 개선하는 것","환경 변화에 맞게 수정하는 것","기능을 향상시키는 것"], answer:2 },
    { id:"se_095", question:"소프트웨어 아키텍처 설계에서 관심사의 분리(Separation of Concerns) 원칙의 목적은?", options:["코드 실행 속도를 높이기 위해","각 모듈이 하나의 책임만 갖도록 분리하여 복잡성을 줄이기 위해","모든 기능을 하나의 모듈에 모으기 위해","보안을 강화하기 위해"], answer:2 },
    { id:"se_096", question:"소프트웨어 테스트에서 부하 테스트(Load Test)의 목적은?", options:["기능적 결함을 찾는다","시스템이 예상 부하 조건에서 올바르게 동작하는지 검증한다","보안 취약점을 찾는다","사용성을 평가한다"], answer:2 },
    { id:"se_097", question:"소프트웨어 설계 원칙 중 DRY(Don't Repeat Yourself)의 의미는?", options:["테스트를 반복하지 않는다","동일한 로직을 중복하지 않는다","문서를 반복해서 작성한다","회의를 자주 하지 않는다"], answer:2 },
    { id:"se_098", question:"소프트웨어 개발에서 코드 리뷰(Code Review)의 주요 목적은?", options:["코드 실행 속도를 측정한다","결함을 조기에 발견하고 코드 품질을 향상시킨다","소프트웨어를 배포한다","요구사항을 분석한다"], answer:2 },
    { id:"se_099", question:"소프트웨어 설계에서 클린 코드(Clean Code)의 특징이 아닌 것은?", options:["읽기 쉬운 코드","의미 있는 변수명 사용","최대한 많은 기능을 하나의 함수에 넣는 것","적절한 주석 사용"], answer:3 },
    { id:"se_100", question:"소프트웨어 테스트에서 탐색적 테스트(Exploratory Testing)의 특징은?", options:["미리 작성된 테스트 케이스만 실행한다","테스터가 동시에 테스트를 설계하고 실행하며 학습한다","자동화 도구만 사용한다","문서화를 최우선으로 한다"], answer:2 }
],

  "데이터통신": [
    { id:"dc_001", question:"무선 LAN에서 사용되는 매체접근방식(MAC)은?", options:["ALOHA","token passing","CSMA/CD","CSMA/CA"], answer:4 },
    { id:"dc_002", question:"데이터 변조속도가 3600 baud이고 쿼드비트(Quad bit)를 사용하는 경우 전송속도(bps)는?", options:["14400","10800","9600","7200"], answer:1 },
    { id:"dc_003", question:"ARP(Address Resolution Protocol)에 대한 설명으로 틀린 것은?", options:["네트워크에서 두 호스트가 성공적으로 통신하기 위하여 각 하드웨어의 물리적인 주소문제를 해결해 줄 수 있다","목적지 호스트의 IP주소를 MAC주소로 바꾸는 역할을 한다","ARP 캐시를 사용하므로 캐시에서 대상이 되는 IP주소의 MAC주소를 발견하면 이 MAC주소가 통신을 위해 사용된다","ARP 캐시를 유지하기 위해서는 TTL값이 0이 되면 이 주소는 ARP 캐시에서 영구히 보존된다"], answer:4 },
    { id:"dc_004", question:"IPv6의 헤더 항목이 아닌 것은?", options:["Flow label","Payload length","HOP limit","Section"], answer:4 },
    { id:"dc_005", question:"HDLC(High-Level Data Link Control) 프레임 형식으로 옳은 것은?", options:["플래그 | 제어영역 | 주소영역 | 정보영역 | FCS | 플래그","플래그 | 주소영역 | 제어영역 | 정보영역 | FCS | 플래그","플래그 | 주소영역 | 정보영역 | 제어영역 | FCS | 플래그","플래그 | 정보영역 | 제어영역 | 주소영역 | FCS | 플래그"], answer:2 },
    { id:"dc_006", question:"주파수 분할 다중화기(FDM)에서 부채널 간의 상호 간섭을 방지하기 위한 것은?", options:["가드 밴드(Guard Band)","채널(Channel)","버퍼(Buffer)","슬롯(Slot)"], answer:1 },
    { id:"dc_007", question:"한 개의 프레임을 전송하고, 수신 측으로부터 ACK 및 NAK 신호를 수신할 때까지 정보전송을 중지하고 기다리는 ARQ 방식은?", options:["CRC 방식","GO-back-N 방식","Stop-and-Wait 방식","Selective Repeat 방식"], answer:3 },
    { id:"dc_008", question:"IEEE 802.5는 무엇에 대한 표준인가?", options:["이더넷","토큰링","토큰버스","FDDI"], answer:2 },
    { id:"dc_009", question:"양자화 잡음에 대한 설명으로 옳은 것은?", options:["PAM 펄스의 아날로그 값을 양자화 잡음이라 한다","PCM 펄스의 디지털 값을 양자화 잡음이라 한다","PCM 펄스의 아날로그 값과 양자화된 PCM 펄스의 디지털 값의 합을 양자화 잡음이라 한다","PCM 펄스의 아날로그 값과 양자화된 PCM 펄스의 디지털 값의 차이를 양자화 잡음이라 한다"], answer:4 },
    { id:"dc_010", question:"아날로그 변조방식에 해당되지 않는 것은?", options:["AM","FM","PM","DM"], answer:4 },
    { id:"dc_011", question:"현재 많이 사용되고 있는 LAN 방식인 '10BASE-T'에서 '10'이 가리키는 의미는?", options:["데이터 전송속도가 10Mbps","케이블 굵기가 10 밀리미터","접속할 수 있는 단말의 수가 10대","배선할 수 있는 케이블의 길이가 10미터"], answer:1 },
    { id:"dc_012", question:"X.25 프로토콜에서 정의하고 있는 것은?", options:["다이얼 접속(dial access)을 위한 기술","Start-Stop 데이터를 위한 기술","데이터 비트 전송률","DTE와 DCE 간 상호접속 및 통신절차 규정"], answer:4 },
    { id:"dc_013", question:"4진 PSK의 반송파 간의 위상차(°)는?", options:["45°","90°","180°","360°"], answer:2 },
    { id:"dc_014", question:"패킷교환에 대한 설명으로 틀린 것은?", options:["전송데이터를 패킷이라 부르는 일정한 길이의 전송단위로 나누어 교환 및 전송한다","패킷교환은 축적교환 방식을 사용한다","가상회선 방식은 비연결형 지향 서비스라고도 한다","메시지 교환이 갖는 장점을 그대로 취하면서 대화형 데이터 통신에 적합하도록 개발된 교환방식이다"], answer:3 },
    { id:"dc_015", question:"링크상태 라우팅 알고리즘을 사용하며, 대규모 네트워크에 적합한 라우팅 프로토콜은?", options:["RIP","VPN","OSPF","XOP"], answer:3 },
    { id:"dc_016", question:"HDLC 프레임 구조 중 플래그(flag)에 대한 설명으로 틀린 것은?", options:["프레임의 최종목적 주소를 나타낸다","동기화에 사용된다","프레임의 시작과 끝을 표시한다","01111110의 형식을 취한다"], answer:1 },
    { id:"dc_017", question:"TCP/IP 관련 프로토콜 중 응용계층에 해당하지 않는 것은?", options:["ARP","DNS","SMTP","HTTP"], answer:1 },
    { id:"dc_018", question:"C class에 속하는 IP address는?", options:["200.168.30.1","10.3.2.1","225.2.4.1","172.16.98.3"], answer:1 },
    { id:"dc_019", question:"회선 교환망에 대한 설명으로 옳은 것은?", options:["일반적으로 전송속도 및 코드변환이 가능하다","전송 대역폭 사용이 가변적이다","물리적인 통신경로가 통신 종료시까지 구성된다","소량의 데이터 전송에 효율적이다"], answer:3 },
    { id:"dc_020", question:"인터넷 제어 메시지 프로토콜(ICMP)에 관한 설명으로 옳지 않은 것은?", options:["에코 메시지는 호스트가 정상적으로 동작하는 지를 결정하는 데 사용할 수 있다","물리계층 프로토콜이다","메시지 형식은 8바이트의 헤더와 가변길이의 데이터 영역으로 분리된다","수신지 도달 불가 메시지는 수신지 또는 서비스에 도달할 수 없는 호스트를 통지하는데 사용된다"], answer:2 },
    { id:"dc_021", question:"1000BaseT 규격에 대한 설명으로 틀린 것은?", options:["최대 전송 속도는 1000Kbps이다","베이스 밴드 전송 방식을 사용한다","전송 매체는 UTP(꼬임쌍선)이다","주로 이더넷(Ethernet)에서 사용된다"], answer:1 },
    { id:"dc_022", question:"HDLC 프레임 구성에서 프레임 검사 시퀀스(FCS) 영역의 기능으로 옳은 것은?", options:["전송 오류 검출","데이터 처리","주소 인식","정보 저장"], answer:1 },
    { id:"dc_023", question:"라우팅 프로토콜이 아닌 것은?", options:["Border Gateway Protocol","Open Shortest Path First","Routing Information Protocol","Serial Line Internet Protocol"], answer:4 },
    { id:"dc_024", question:"IPv4 주소 구조 중 실험적인 주소로 공용으로는 사용되지 않는 클래스는?", options:["A 클래스","B 클래스","C 클래스","E 클래스"], answer:4 },
    { id:"dc_025", question:"OSI-7계층 중 물리 주소를 지정하고 흐름 제어 및 전송 제어를 수행하는 계층은?", options:["물리 계층","데이터 링크 계층","세션 계층","응용 계층"], answer:2 },
    { id:"dc_026", question:"HDLC 전송 제어 절차의 세 가지 동작 모드에 속하지 않는 것은?", options:["정규 응답 모드(NRM)","동기 응답 모드(SRM)","비동기 응답 모드(ARM)","비동기 평형 모드(ABM)"], answer:2 },
    { id:"dc_027", question:"TCP/IP 네트워크에서 IP 주소를 물리 주소로 변환하는 프로토콜은?", options:["ICMP","RIP","ARP","UDP"], answer:3 },
    { id:"dc_028", question:"데이터 전송 방식 중 패킷 교환 방식에서 데이터그램에 대한 설명으로 틀린 것은?", options:["패킷 교환은 저장-전달 방식을 사용한다","패킷 교환은 데이터그램 방식과 가상 회선 방식으로 구분된다","데이터그램은 연결형 서비스 방식으로 패킷을 전송하기 전에 미리 경로를 설정해야 한다","가상 회선은 패킷이 전송되기 전에 논리적인 연결 설정이 이루어져야 한다"], answer:3 },
    { id:"dc_029", question:"IEEE 802.3의 표준안 내용으로 옳은 것은?", options:["CSMA/CD LAN","무선 LAN","토큰 링 LAN","토큰 버스 LAN"], answer:1 },
    { id:"dc_030", question:"외부 네트워크에서 알려진 공인 IP 주소와 사설 IP 주소를 사용하는 내부 네트워크에서 IP 주소를 변환하는 것은?", options:["NAT","FTP","SMTP","SNMP"], answer:1 },
    { id:"dc_031", question:"OSI 7계층에서 데이터 압축, 암호화 기능을 담당하는 계층은?", options:["세션 계층","표현 계층","응용 계층","전송 계층"], answer:2 },
    { id:"dc_032", question:"TCP(Transmission Control Protocol)의 특성으로 옳은 것은?", options:["비연결형 서비스를 제공한다","신뢰성 있는 데이터 전송을 보장한다","헤더 크기가 UDP보다 작다","실시간 스트리밍에 주로 사용된다"], answer:2 },
    { id:"dc_033", question:"이더넷(Ethernet)에서 충돌(Collision) 감지 후 처리하는 알고리즘은?", options:["CSMA/CD","이진 지수 백오프(Binary Exponential Backoff)","토큰 패싱(Token Passing)","폴링(Polling)"], answer:2 },
    { id:"dc_034", question:"서브넷 마스크(Subnet Mask) 255.255.255.0에서 하나의 서브넷에 할당 가능한 호스트 수는?", options:["254","255","256","512"], answer:1 },
    { id:"dc_035", question:"WAN(Wide Area Network)에서 사용하는 전송 방식이 아닌 것은?", options:["ISDN","ATM","Frame Relay","CSMA/CD"], answer:4 },
    { id:"dc_036", question:"전송 매체 중 전자기 간섭(EMI)의 영향을 가장 적게 받는 것은?", options:["UTP 케이블","STP 케이블","동축 케이블","광섬유 케이블"], answer:4 },
    { id:"dc_037", question:"HTTP 프로토콜에서 기본적으로 사용하는 포트 번호는?", options:["21","23","80","443"], answer:3 },
    { id:"dc_038", question:"DNS(Domain Name System)의 기능은?", options:["IP 주소를 MAC 주소로 변환","도메인 이름을 IP 주소로 변환","IP 주소를 도메인 이름으로 변환만 한다","MAC 주소를 IP 주소로 변환"], answer:2 },
    { id:"dc_039", question:"FTP(File Transfer Protocol)에서 데이터 전송에 사용하는 포트 번호는?", options:["20","21","23","25"], answer:1 },
    { id:"dc_040", question:"전이중(Full Duplex) 통신 방식에 대한 설명으로 옳은 것은?", options:["단방향 통신만 가능하다","양방향이지만 동시에는 불가능하다","동시에 양방향 통신이 가능하다","방송과 같이 한 곳에서 여러 곳으로 전송한다"], answer:3 },
    { id:"dc_041", question:"네트워크 토폴로지 중 중앙 허브에 모든 노드가 연결되는 형태는?", options:["버스형(Bus)","링형(Ring)","스타형(Star)","메시형(Mesh)"], answer:3 },
    { id:"dc_042", question:"오류 제어 방식 중 CRC(Cyclic Redundancy Check)에 대한 설명으로 옳은 것은?", options:["패리티 비트만을 사용하여 오류를 검출한다","다항식을 이용한 오류 검출 방식이다","오류를 자동으로 수정하는 방식이다","해밍 코드와 동일한 방식이다"], answer:2 },
    { id:"dc_043", question:"TCP/IP 프로토콜에서 IP 계층의 주요 기능이 아닌 것은?", options:["라우팅(Routing)","주소 지정(Addressing)","신뢰성 있는 전송 보장","패킷 분할 및 재조합"], answer:3 },
    { id:"dc_044", question:"SMTP(Simple Mail Transfer Protocol)에 대한 설명으로 옳은 것은?", options:["전자 메일을 수신하는 프로토콜이다","전자 메일을 전송하는 프로토콜이다","파일을 전송하는 프로토콜이다","웹 페이지를 전송하는 프로토콜이다"], answer:2 },
    { id:"dc_045", question:"IEEE 802.11 표준에 해당하는 것은?", options:["이더넷(Ethernet)","토큰 링(Token Ring)","무선 LAN(Wireless LAN)","광섬유 분산 데이터 인터페이스(FDDI)"], answer:3 },
    { id:"dc_046", question:"OSI 7계층 모델에서 물리 계층(Physical Layer)의 주요 기능은?", options:["패킷 라우팅","비트 전송","세션 관리","암호화"], answer:2 },
    { id:"dc_047", question:"TCP/IP에서 UDP(User Datagram Protocol)의 특징으로 옳은 것은?", options:["연결 지향 서비스를 제공한다","신뢰성 있는 전송을 보장한다","오버헤드가 적고 빠르다","흐름 제어를 수행한다"], answer:3 },
    { id:"dc_048", question:"네트워크 장비 중 OSI 3계층(네트워크 계층)에서 동작하는 장비는?", options:["허브(Hub)","스위치(Switch)","라우터(Router)","리피터(Repeater)"], answer:3 },
    { id:"dc_049", question:"IPv4 주소 체계에서 루프백(Loopback) 주소는?", options:["0.0.0.0","127.0.0.1","192.168.0.1","255.255.255.255"], answer:2 },
    { id:"dc_050", question:"데이터 통신에서 흐름 제어(Flow Control)의 목적은?", options:["오류를 검출하고 수정한다","송신측이 수신측의 처리 능력을 초과하지 않도록 전송 속도를 조절한다","라우팅 경로를 결정한다","데이터를 암호화한다"], answer:2 },
    { id:"dc_051", question:"TCP에서 3-Way Handshake의 목적은?", options:["데이터 암호화","연결 설정","오류 수정","라우팅"], answer:2 },
    { id:"dc_052", question:"네트워크에서 브로드캐스트(Broadcast) 주소의 역할은?", options:["특정 호스트에게만 데이터를 전송한다","네트워크의 모든 호스트에게 데이터를 전송한다","특정 그룹에게만 데이터를 전송한다","라우터에게만 데이터를 전송한다"], answer:2 },
    { id:"dc_053", question:"VPN(Virtual Private Network)에 대한 설명으로 옳은 것은?", options:["물리적인 전용선을 사용하는 네트워크","공용 네트워크를 통해 사설 네트워크처럼 안전하게 통신하는 기술","로컬 네트워크만을 위한 기술","무선 통신만을 위한 기술"], answer:2 },
    { id:"dc_054", question:"OSI 7계층에서 전송 계층(Transport Layer)의 주요 프로토콜은?", options:["IP, ICMP","TCP, UDP","HTTP, FTP","PPP, HDLC"], answer:2 },
    { id:"dc_055", question:"네트워크에서 DHCP(Dynamic Host Configuration Protocol)의 역할은?", options:["도메인 이름을 IP로 변환한다","IP 주소를 자동으로 할당한다","라우팅 경로를 결정한다","방화벽 역할을 한다"], answer:2 },
    { id:"dc_056", question:"방화벽(Firewall)의 주요 기능은?", options:["네트워크 속도를 향상시킨다","허가되지 않은 네트워크 접근을 차단한다","IP 주소를 자동 할당한다","DNS 서비스를 제공한다"], answer:2 },
    { id:"dc_057", question:"네트워크에서 SNMP(Simple Network Management Protocol)의 목적은?", options:["전자 메일 전송","네트워크 장비 관리","파일 전송","웹 서비스 제공"], answer:2 },
    { id:"dc_058", question:"데이터 통신에서 노이즈(Noise)의 영향을 줄이기 위한 방법이 아닌 것은?", options:["차폐 케이블 사용","오류 검출 코드 사용","전송 속도를 높임","신호 증폭"], answer:3 },
    { id:"dc_059", question:"TCP/IP 프로토콜 스택에서 응용 계층 프로토콜이 아닌 것은?", options:["HTTP","SMTP","FTP","IP"], answer:4 },
    { id:"dc_060", question:"네트워크에서 멀티캐스트(Multicast)에 대한 설명으로 옳은 것은?", options:["모든 호스트에게 전송한다","특정 그룹의 호스트에게만 전송한다","하나의 특정 호스트에게만 전송한다","근처 호스트에게만 전송한다"], answer:2 },
    { id:"dc_061", question:"데이터 전송에서 슬라이딩 윈도우(Sliding Window) 프로토콜의 목적은?", options:["오류를 자동으로 수정한다","여러 프레임을 연속으로 전송하여 효율을 높인다","암호화를 수행한다","라우팅 경로를 결정한다"], answer:2 },
    { id:"dc_062", question:"인터넷에서 HTTPS의 포트 번호는?", options:["80","443","21","25"], answer:2 },
    { id:"dc_063", question:"네트워크 토폴로지 중 메시형(Mesh)의 특징으로 옳은 것은?", options:["중앙 허브에 모든 노드가 연결된다","모든 노드가 서로 직접 연결된다","노드가 순환적으로 연결된다","모든 노드가 하나의 공유 버스에 연결된다"], answer:2 },
    { id:"dc_064", question:"인터넷에서 TELNET 프로토콜의 기본 포트 번호는?", options:["21","22","23","25"], answer:3 },
    { id:"dc_065", question:"데이터 통신에서 기저대역(Baseband) 전송의 특징은?", options:["여러 채널을 동시에 전송한다","디지털 신호를 변조 없이 전송한다","아날로그 신호만 전송한다","마이크로파를 사용한다"], answer:2 },
    { id:"dc_066", question:"OSI 7계층에서 세션 계층(Session Layer)의 역할은?", options:["비트 전송","오류 제어","응용 프로그램 간의 대화 설정 및 관리","데이터 압축"], answer:3 },
    { id:"dc_067", question:"TCP/IP에서 RARP(Reverse ARP)의 기능은?", options:["IP 주소를 MAC 주소로 변환","MAC 주소를 IP 주소로 변환","도메인을 IP 주소로 변환","IP 주소를 도메인으로 변환"], answer:2 },
    { id:"dc_068", question:"네트워크에서 게이트웨이(Gateway)의 역할은?", options:["동일한 프로토콜을 사용하는 네트워크를 연결한다","서로 다른 프로토콜을 사용하는 네트워크를 연결한다","신호를 증폭하여 전달한다","MAC 주소를 기반으로 패킷을 전달한다"], answer:2 },
    { id:"dc_069", question:"데이터 통신에서 오류 검출 방법 중 패리티 비트(Parity Bit)에 대한 설명으로 옳은 것은?", options:["단일 비트 오류만 검출 가능하다","모든 종류의 오류를 검출할 수 있다","오류를 자동으로 수정할 수 있다","2비트 이상의 오류도 항상 검출 가능하다"], answer:1 },
    { id:"dc_070", question:"인터넷 프로토콜 IPv6의 주소 길이는?", options:["32비트","64비트","128비트","256비트"], answer:3 },
    { id:"dc_071", question:"네트워크에서 스위치(Switch)가 동작하는 OSI 계층은?", options:["물리 계층","데이터 링크 계층","네트워크 계층","전송 계층"], answer:2 },
    { id:"dc_072", question:"데이터 통신에서 다중화(Multiplexing)의 목적은?", options:["데이터를 암호화한다","하나의 채널에서 여러 신호를 동시에 전송한다","오류를 검출한다","라우팅 경로를 결정한다"], answer:2 },
    { id:"dc_073", question:"인터넷에서 SSH(Secure Shell) 프로토콜의 기본 포트 번호는?", options:["21","22","23","443"], answer:2 },
    { id:"dc_074", question:"네트워크 보안에서 IDS(Intrusion Detection System)의 역할은?", options:["네트워크 접근을 차단한다","침입 시도를 탐지하고 경고한다","IP 주소를 자동 할당한다","데이터를 암호화한다"], answer:2 },
    { id:"dc_075", question:"TCP/IP 4계층 모델에서 인터넷 계층(Internet Layer)에 해당하는 프로토콜은?", options:["TCP","HTTP","IP","Ethernet"], answer:3 },
    { id:"dc_076", question:"데이터 통신에서 ARQ(Automatic Repeat reQuest) 방식이 아닌 것은?", options:["Stop-and-Wait ARQ","Go-Back-N ARQ","Selective Repeat ARQ","Forward Error Correction"], answer:4 },
    { id:"dc_077", question:"네트워크에서 허브(Hub)와 스위치(Switch)의 차이점은?", options:["허브는 MAC 주소를 인식하여 해당 포트로만 전송하고, 스위치는 모든 포트로 브로드캐스트한다","허브는 모든 포트로 브로드캐스트하고, 스위치는 MAC 주소를 기반으로 특정 포트로 전송한다","차이가 없다","허브는 3계층, 스위치는 2계층에서 동작한다"], answer:2 },
    { id:"dc_078", question:"인터넷에서 POP3(Post Office Protocol 3)의 역할은?", options:["전자 메일 전송","전자 메일 수신","파일 전송","웹 서비스"], answer:2 },
    { id:"dc_079", question:"데이터 통신에서 나이퀴스트(Nyquist) 정리의 내용은?", options:["잡음이 있는 채널의 최대 데이터 전송률을 계산한다","아날로그 신호를 디지털로 변환하려면 최소 2배의 샘플링 주파수가 필요하다","오류 검출을 위한 패리티 비트 계산법이다","주파수 분할 다중화 방법이다"], answer:2 },
    { id:"dc_080", question:"OSI 7계층에서 네트워크 계층(Network Layer)의 주요 기능은?", options:["비트 전송","오류 검출","패킷 라우팅","세션 관리"], answer:3 },
    { id:"dc_081", question:"인터넷에서 IMAP(Internet Message Access Protocol)과 POP3의 차이점은?", options:["IMAP은 메일을 서버에서 관리하고, POP3는 클라이언트에 다운로드한다","POP3는 메일을 서버에서 관리하고, IMAP은 클라이언트에 다운로드한다","두 프로토콜은 동일한 기능을 제공한다","IMAP은 메일 전송, POP3는 메일 수신용이다"], answer:1 },
    { id:"dc_082", question:"네트워크 보안에서 SSL/TLS의 목적은?", options:["데이터 압축","데이터 암호화 및 안전한 통신 제공","IP 주소 변환","라우팅 최적화"], answer:2 },
    { id:"dc_083", question:"데이터 통신에서 CSMA/CD의 CD가 의미하는 것은?", options:["Content Detection","Collision Detection","Channel Division","Code Decoding"], answer:2 },
    { id:"dc_084", question:"인터넷 주소 체계에서 사설 IP 주소(Private IP Address)가 아닌 것은?", options:["10.0.0.1","172.16.0.1","192.168.1.1","200.200.200.1"], answer:4 },
    { id:"dc_085", question:"네트워크에서 브리지(Bridge)의 기능은?", options:["신호를 증폭하여 전달","같은 프로토콜을 사용하는 두 네트워크를 연결하고 트래픽을 필터링","서로 다른 프로토콜의 네트워크를 연결","IP 주소를 기반으로 패킷을 전달"], answer:2 },
    { id:"dc_086", question:"데이터 통신에서 광대역(Broadband) 전송의 특징은?", options:["단일 채널만 사용한다","여러 채널을 동시에 전송할 수 있다","디지털 신호만 전송한다","짧은 거리에만 적합하다"], answer:2 },
    { id:"dc_087", question:"인터넷에서 서브넷팅(Subnetting)의 목적은?", options:["IP 주소의 보안을 강화한다","하나의 네트워크를 여러 개의 소규모 네트워크로 분할한다","전송 속도를 높인다","DNS 성능을 향상시킨다"], answer:2 },
    { id:"dc_088", question:"TCP에서 흐름 제어를 위해 사용하는 기법은?", options:["슬라이딩 윈도우(Sliding Window)","패리티 비트","CRC","해밍 코드"], answer:1 },
    { id:"dc_089", question:"네트워크 보안에서 DMZ(Demilitarized Zone)란?", options:["완전히 격리된 내부 네트워크","외부와 내부 네트워크 사이의 중간 구역","무선 네트워크 영역","가상 사설 네트워크"], answer:2 },
    { id:"dc_090", question:"데이터 통신에서 비동기 전송(Asynchronous Transmission)의 특징으로 옳은 것은?", options:["클럭 신호를 공유한다","각 문자 전송 전후에 시작 비트와 정지 비트를 사용한다","연속적인 데이터 스트림을 전송한다","블록 단위로 전송한다"], answer:2 },
    { id:"dc_091", question:"OSI 7계층에서 응용 계층(Application Layer)의 프로토콜이 아닌 것은?", options:["HTTP","FTP","SMTP","TCP"], answer:4 },
    { id:"dc_092", question:"네트워크에서 VLAN(Virtual LAN)의 장점이 아닌 것은?", options:["브로드캐스트 도메인 분리","보안 향상","물리적 케이블 절약","전송 속도 증가"], answer:4 },
    { id:"dc_093", question:"데이터 통신에서 전파 지연(Propagation Delay)이란?", options:["데이터를 처리하는 시간","신호가 전송 매체를 통해 목적지까지 도달하는 시간","버퍼에서 대기하는 시간","데이터를 인코딩하는 시간"], answer:2 },
    { id:"dc_094", question:"인터넷에서 BGP(Border Gateway Protocol)는 어떤 유형의 라우팅 프로토콜인가?", options:["내부 라우팅 프로토콜(IGP)","외부 라우팅 프로토콜(EGP)","링크 상태 라우팅 프로토콜","거리 벡터 라우팅 프로토콜"], answer:2 },
    { id:"dc_095", question:"네트워크 보안에서 DDoS(Distributed Denial of Service) 공격의 특징은?", options:["단일 호스트에서 공격한다","여러 호스트를 이용해 대상 서버에 과부하를 유발한다","데이터를 도청한다","IP 주소를 위조한다"], answer:2 },
    { id:"dc_096", question:"데이터 통신에서 전송 지연(Transmission Delay)이란?", options:["신호가 매체를 통해 이동하는 시간","비트를 전송 매체에 올리는 데 걸리는 시간","라우터에서 처리하는 시간","대기열에서 기다리는 시간"], answer:2 },
    { id:"dc_097", question:"TCP/IP에서 ICMP(Internet Control Message Protocol)의 주요 목적은?", options:["신뢰성 있는 데이터 전송","오류 보고 및 네트워크 진단","파일 전송","메일 전송"], answer:2 },
    { id:"dc_098", question:"네트워크에서 리피터(Repeater)의 기능은?", options:["MAC 주소를 기반으로 트래픽 필터링","신호를 재생하여 전달 거리를 연장","패킷을 라우팅","프로토콜 변환"], answer:2 },
    { id:"dc_099", question:"데이터 통신에서 암호화 방식 중 공개키 암호화(Public Key Cryptography)의 특징은?", options:["암호화와 복호화에 동일한 키를 사용한다","암호화와 복호화에 서로 다른 키를 사용한다","키 배포 문제가 없어 관리가 쉽다","대칭키 방식보다 처리 속도가 빠르다"], answer:2 },
    { id:"dc_100", question:"OSI 7계층 모델에서 각 계층이 올바르게 나열된 것은?", options:["물리-데이터링크-네트워크-전송-세션-표현-응용","물리-네트워크-데이터링크-전송-세션-표현-응용","물리-데이터링크-전송-네트워크-세션-표현-응용","물리-데이터링크-네트워크-세션-전송-표현-응용"], answer:1 }
]
};
