const QUESTIONS = {
  "데이터베이스": [
    { id:"db_001", question:"다음 중 DDL(Data Definition Language)에 해당하는 SQL 명령어는?", options:["SELECT", "INSERT", "CREATE", "UPDATE"], answer:3 },
    { id:"db_002", question:"트랜잭션의 특성 중 '트랜잭션은 완전히 실행되거나 전혀 실행되지 않아야 한다'는 특성은?", options:["일관성(Consistency)", "원자성(Atomicity)", "고립성(Isolation)", "지속성(Durability)"], answer:2 },
    { id:"db_003", question:"E-R 다이어그램에서 개체(Entity) 집합을 나타내는 기호는?", options:["타원형", "마름모형", "직사각형", "삼각형"], answer:3 },
    { id:"db_004", question:"정규화 과정에서 제2정규형(2NF)이 되기 위한 조건은?", options:["모든 도메인이 원자값", "부분 함수 종속 제거", "이행 함수 종속 제거", "다치 종속 제거"], answer:2 },
    { id:"db_005", question:"SQL에서 데이터를 검색할 때 사용하는 명령어는?", options:["INSERT", "SELECT", "UPDATE", "DELETE"], answer:2 },
    { id:"db_006", question:"트랜잭션의 ACID 특성 중 '트랜잭션 실행 중 다른 트랜잭션이 접근할 수 없다'는 특성은?", options:["원자성(Atomicity)", "일관성(Consistency)", "고립성(Isolation)", "지속성(Durability)"], answer:3 },
    { id:"db_007", question:"E-R 다이어그램에서 관계(Relationship)를 나타내는 기호는?", options:["직사각형", "타원형", "마름모형", "원형"], answer:3 },
    { id:"db_008", question:"테이블에서 행(Row)을 삭제할 때 사용하는 SQL 명령어는?", options:["DROP", "REMOVE", "DELETE", "TRUNCATE"], answer:3 },
    { id:"db_009", question:"다음 중 DML(Data Manipulation Language)에 해당하지 않는 것은?", options:["SELECT", "INSERT", "CREATE", "UPDATE"], answer:3 },
    { id:"db_010", question:"릴레이션에서 튜플(Tuple)을 다른 말로 표현하면?", options:["열(Column)", "행(Row)", "도메인(Domain)", "속성(Attribute)"], answer:2 },
    { id:"db_011", question:"기본키(Primary Key)의 특성으로 옳지 않은 것은?", options:["유일성을 가진다", "NOT NULL이어야 한다", "중복 값을 허용한다", "테이블당 하나만 존재한다"], answer:3 },
    { id:"db_012", question:"외래키(Foreign Key)에 대한 설명으로 옳은 것은?", options:["반드시 유일해야 한다", "다른 테이블의 기본키를 참조한다", "NULL 값을 가질 수 없다", "테이블당 하나만 설정 가능하다"], answer:2 },
    { id:"db_013", question:"정규화의 목적으로 가장 적절한 것은?", options:["데이터 검색 속도 향상", "데이터 중복 최소화", "인덱스 자동 생성", "트랜잭션 처리 속도 향상"], answer:2 },
    { id:"db_014", question:"제1정규형(1NF)의 조건은?", options:["부분 함수 종속 제거", "이행 함수 종속 제거", "모든 속성값이 원자값이어야 한다", "결정자가 모두 후보키이어야 한다"], answer:3 },
    { id:"db_015", question:"DCL(Data Control Language)에 해당하는 SQL 명령어는?", options:["CREATE", "SELECT", "GRANT", "INSERT"], answer:3 },
    { id:"db_016", question:"뷰(View)에 대한 설명으로 옳지 않은 것은?", options:["논리적으로 정의된 가상 테이블이다", "독립적인 인덱스를 가진다", "기본 테이블로부터 파생된다", "보안 목적으로 사용 가능하다"], answer:2 },
    { id:"db_017", question:"트랜잭션 완료 후 결과가 영구적으로 저장되어야 한다는 특성은?", options:["원자성", "일관성", "고립성", "지속성"], answer:4 },
    { id:"db_018", question:"스키마의 3단계 구조 중 사용자 관점에서 본 스키마는?", options:["외부 스키마", "개념 스키마", "내부 스키마", "물리 스키마"], answer:1 },
    { id:"db_019", question:"스키마의 3단계 구조 중 데이터베이스 전체를 정의한 스키마는?", options:["외부 스키마", "개념 스키마", "내부 스키마", "논리 스키마"], answer:2 },
    { id:"db_020", question:"스키마의 3단계 구조 중 물리적 저장 방식을 정의한 스키마는?", options:["외부 스키마", "개념 스키마", "내부 스키마", "서브 스키마"], answer:3 },
    { id:"db_021", question:"인덱스(Index)의 주요 목적은?", options:["데이터 무결성 보장", "데이터 검색 속도 향상", "데이터 중복 방지", "보안 강화"], answer:2 },
    { id:"db_022", question:"관계 대수 연산 중 조건을 만족하는 튜플을 추출하는 연산은?", options:["PROJECT", "SELECT", "JOIN", "UNION"], answer:2 },
    { id:"db_023", question:"관계 대수 연산 중 특정 속성만 추출하는 연산은?", options:["SELECT", "PROJECT", "JOIN", "DIFFERENCE"], answer:2 },
    { id:"db_024", question:"두 릴레이션의 공통 속성을 기준으로 합치는 관계 대수 연산은?", options:["UNION", "INTERSECTION", "JOIN", "DIFFERENCE"], answer:3 },
    { id:"db_025", question:"후보키(Candidate Key)에 대한 설명으로 옳은 것은?", options:["반드시 단일 속성으로만 구성된다", "기본키로 선택될 수 있는 키이다", "중복 값을 허용한다", "외래키와 동일한 개념이다"], answer:2 },
    { id:"db_026", question:"슈퍼키(Super Key)에 대한 설명으로 옳은 것은?", options:["유일성만 만족하면 된다", "최소성을 반드시 만족해야 한다", "기본키와 동일한 개념이다", "NULL 값을 허용하지 않는다"], answer:1 },
    { id:"db_027", question:"테이블 구조를 수정할 때 사용하는 DDL 명령어는?", options:["UPDATE", "MODIFY", "ALTER", "CHANGE"], answer:3 },
    { id:"db_028", question:"테이블을 완전히 삭제할 때 사용하는 DDL 명령어는?", options:["DELETE", "REMOVE", "TRUNCATE", "DROP"], answer:4 },
    { id:"db_029", question:"사용자에게 권한을 부여하는 DCL 명령어는?", options:["PERMIT", "ALLOW", "GRANT", "AUTHORIZE"], answer:3 },
    { id:"db_030", question:"사용자로부터 권한을 회수하는 DCL 명령어는?", options:["REVOKE", "DENY", "REMOVE", "CANCEL"], answer:1 },
    { id:"db_031", question:"개체 무결성(Entity Integrity) 제약 조건에 대한 설명으로 옳은 것은?", options:["외래키는 NULL이 될 수 없다", "기본키는 NULL이나 중복 값을 가질 수 없다", "속성값은 도메인을 벗어날 수 없다", "모든 속성값은 원자값이어야 한다"], answer:2 },
    { id:"db_032", question:"참조 무결성(Referential Integrity) 제약 조건에 대한 설명으로 옳은 것은?", options:["기본키는 유일해야 한다", "외래키 값은 참조 테이블의 기본키 값이어야 한다", "속성값은 정해진 도메인 내에 있어야 한다", "모든 속성은 원자값이어야 한다"], answer:2 },
    { id:"db_033", question:"도메인 무결성(Domain Integrity)에 대한 설명으로 옳은 것은?", options:["기본키는 중복될 수 없다", "외래키는 참조 테이블의 기본키를 참조한다", "속성값은 해당 도메인에서 정의된 값만 허용된다", "튜플은 유일하게 식별되어야 한다"], answer:3 },
    { id:"db_034", question:"E-R 다이어그램에서 속성(Attribute)을 나타내는 기호는?", options:["직사각형", "마름모형", "타원형", "육각형"], answer:3 },
    { id:"db_035", question:"데이터베이스 설계 단계의 순서로 올바른 것은?", options:["개념→요구분석→논리→물리→구현", "요구분석→개념→논리→물리→구현", "논리→개념→요구분석→물리→구현", "요구분석→논리→개념→물리→구현"], answer:2 },
    { id:"db_036", question:"논리적 데이터 독립성의 의미는?", options:["내부 스키마 변경이 개념 스키마에 영향을 주지 않음", "개념 스키마 변경이 외부 스키마에 영향을 주지 않음", "외부 스키마 변경이 내부 스키마에 영향을 주지 않음", "물리적 저장 구조 변경이 논리 구조에 영향을 주지 않음"], answer:2 },
    { id:"db_037", question:"물리적 데이터 독립성의 의미는?", options:["내부 스키마 변경이 개념 스키마에 영향을 주지 않음", "개념 스키마 변경이 외부 스키마에 영향을 주지 않음", "외부 스키마 변경이 내부 스키마에 영향을 주지 않음", "외부 스키마 변경이 개념 스키마에 영향을 주지 않음"], answer:1 },
    { id:"db_038", question:"병행 제어(Concurrency Control)의 목적으로 가장 적절한 것은?", options:["데이터 검색 속도 향상", "트랜잭션 간 데이터 일관성 유지", "인덱스 관리 자동화", "백업 및 복구 처리"], answer:2 },
    { id:"db_039", question:"로킹(Locking)에 대한 설명으로 옳은 것은?", options:["데이터 압축 기법이다", "병행 제어 기법 중 하나이다", "인덱스 생성 방법이다", "정규화 기법이다"], answer:2 },
    { id:"db_040", question:"타임스탬프(Timestamp) 기법은 어떤 목적으로 사용되는가?", options:["데이터 암호화", "병행 제어", "인덱스 관리", "백업 관리"], answer:2 },
    { id:"db_041", question:"릴레이션(Relation)의 특성으로 옳지 않은 것은?", options:["튜플의 순서는 의미가 없다", "중복된 튜플이 존재할 수 없다", "속성의 순서는 의미가 있다", "속성값은 원자값이어야 한다"], answer:3 },
    { id:"db_042", question:"해싱(Hashing)에서 충돌(Collision)이 발생했을 때 처리하는 방법이 아닌 것은?", options:["체이닝(Chaining)", "개방 주소법(Open Addressing)", "선형 조사법(Linear Probing)", "이진 탐색(Binary Search)"], answer:4 },
    { id:"db_043", question:"제3정규형(3NF)이 되기 위한 조건은?", options:["모든 속성값이 원자값", "부분 함수 종속 제거", "이행 함수 종속 제거", "다치 종속 제거"], answer:3 },
    { id:"db_044", question:"BCNF(보이스-코드 정규형)의 조건은?", options:["모든 도메인이 원자값", "부분 함수 종속 제거", "이행 함수 종속 제거", "모든 결정자가 후보키"], answer:4 },
    { id:"db_045", question:"관계 대수의 UNION(합집합) 연산을 수행하기 위한 조건은?", options:["두 릴레이션의 기본키가 같아야 한다", "두 릴레이션의 차수와 도메인이 같아야 한다", "두 릴레이션의 튜플 수가 같아야 한다", "두 릴레이션의 속성 이름이 같아야 한다"], answer:2 },
    { id:"db_046", question:"SQL에서 테이블을 생성하는 명령어는?", options:["MAKE TABLE", "BUILD TABLE", "CREATE TABLE", "NEW TABLE"], answer:3 },
    { id:"db_047", question:"뷰(View)의 장점으로 옳지 않은 것은?", options:["데이터 보안성 향상", "논리적 독립성 제공", "물리적 저장 공간 절약", "복잡한 쿼리 단순화"], answer:3 },
    { id:"db_048", question:"기본키(Primary Key)를 구성하는 속성의 집합을 식별하는 최소 단위는?", options:["슈퍼키", "후보키", "외래키", "대리키"], answer:2 },
    { id:"db_049", question:"대리키(Surrogate Key)에 대한 설명으로 옳은 것은?", options:["자연스럽게 존재하는 속성으로 구성된 키", "의미 없는 인공적으로 생성된 키", "여러 테이블에 걸쳐 참조되는 키", "두 개 이상의 속성으로 구성된 키"], answer:2 },
    { id:"db_050", question:"트랜잭션에서 COMMIT 명령어의 역할은?", options:["트랜잭션을 취소하고 이전 상태로 되돌린다", "트랜잭션의 모든 변경 사항을 영구 저장한다", "트랜잭션을 일시 중지한다", "새로운 트랜잭션을 시작한다"], answer:2 },
    { id:"db_051", question:"트랜잭션에서 ROLLBACK 명령어의 역할은?", options:["트랜잭션의 변경 사항을 영구 저장한다", "트랜잭션을 취소하고 이전 상태로 되돌린다", "새로운 저장점을 만든다", "트랜잭션을 시작한다"], answer:2 },
    { id:"db_052", question:"SQL에서 기존 데이터를 수정할 때 사용하는 명령어는?", options:["MODIFY", "CHANGE", "ALTER", "UPDATE"], answer:4 },
    { id:"db_053", question:"SQL에서 새로운 데이터를 삽입할 때 사용하는 명령어는?", options:["ADD", "INSERT", "APPEND", "PUT"], answer:2 },
    { id:"db_054", question:"관계 대수 연산 중 두 릴레이션의 차집합을 구하는 연산은?", options:["UNION", "INTERSECTION", "DIFFERENCE", "JOIN"], answer:3 },
    { id:"db_055", question:"관계 대수 연산 중 두 릴레이션의 교집합을 구하는 연산은?", options:["UNION", "INTERSECTION", "DIFFERENCE", "JOIN"], answer:2 },
    { id:"db_056", question:"데이터베이스에서 릴레이션의 차수(Degree)는 무엇을 의미하는가?", options:["릴레이션의 튜플 수", "릴레이션의 속성 수", "릴레이션의 도메인 수", "릴레이션의 기본키 수"], answer:2 },
    { id:"db_057", question:"데이터베이스에서 카디널리티(Cardinality)는 무엇을 의미하는가?", options:["릴레이션의 속성 수", "릴레이션의 튜플 수", "릴레이션의 도메인 수", "릴레이션의 인덱스 수"], answer:2 },
    { id:"db_058", question:"물리적 설계 단계에서 주로 결정하는 사항은?", options:["개체와 관계 정의", "논리적 데이터 구조 설계", "저장 구조 및 접근 방법 결정", "사용자 요구사항 분석"], answer:3 },
    { id:"db_059", question:"개념적 설계 단계의 주요 산출물은?", options:["E-R 다이어그램", "물리적 스키마", "SQL 스크립트", "테이블 정의서"], answer:1 },
    { id:"db_060", question:"논리적 설계 단계에서 수행하는 작업은?", options:["저장 장치 결정", "E-R 다이어그램 작성", "릴레이션 스키마 변환", "사용자 인터뷰"], answer:3 },
    { id:"db_061", question:"해시 함수(Hash Function)의 특성으로 옳은 것은?", options:["동일한 키는 다른 해시값을 가진다", "입력값에 상관없이 검색 속도가 일정하다", "항상 충돌이 발생하지 않는다", "인덱스 대신 순차 검색에 사용된다"], answer:2 },
    { id:"db_062", question:"데이터 독립성(Data Independence)의 목적으로 옳은 것은?", options:["데이터 중복 제거", "스키마 변경 시 응용 프로그램의 영향 최소화", "검색 속도 향상", "트랜잭션 처리 향상"], answer:2 },
    { id:"db_063", question:"SQL에서 조건을 지정할 때 사용하는 절은?", options:["FROM", "GROUP BY", "WHERE", "ORDER BY"], answer:3 },
    { id:"db_064", question:"SQL에서 결과를 정렬할 때 사용하는 절은?", options:["WHERE", "HAVING", "GROUP BY", "ORDER BY"], answer:4 },
    { id:"db_065", question:"SQL에서 그룹화를 수행하는 절은?", options:["WHERE", "ORDER BY", "GROUP BY", "HAVING"], answer:3 },
    { id:"db_066", question:"뷰(View)를 생성하는 SQL 명령어는?", options:["MAKE VIEW", "BUILD VIEW", "CREATE VIEW", "NEW VIEW"], answer:3 },
    { id:"db_067", question:"인덱스의 단점으로 옳은 것은?", options:["검색 속도가 느려진다", "저장 공간이 추가로 필요하다", "데이터 무결성이 감소한다", "트랜잭션 처리가 불가능하다"], answer:2 },
    { id:"db_068", question:"트랜잭션의 일관성(Consistency) 특성에 대한 설명으로 옳은 것은?", options:["트랜잭션이 완전히 실행되거나 전혀 실행되지 않는다", "트랜잭션 실행 전후 데이터베이스가 일관된 상태를 유지한다", "다른 트랜잭션이 동시에 접근할 수 없다", "결과가 영구적으로 저장된다"], answer:2 },
    { id:"db_069", question:"E-R 다이어그램에서 다중값 속성을 나타내는 기호는?", options:["단일 타원", "이중 타원", "직사각형", "마름모"], answer:2 },
    { id:"db_070", question:"관계 데이터베이스에서 테이블을 다른 말로 부르는 것은?", options:["뷰(View)", "인덱스(Index)", "릴레이션(Relation)", "스키마(Schema)"], answer:3 },
    { id:"db_071", question:"SQL의 SELECT 문에서 중복 행을 제거하기 위해 사용하는 키워드는?", options:["UNIQUE", "DISTINCT", "DIFFERENT", "NODUPLICATE"], answer:2 },
    { id:"db_072", question:"SQL에서 NULL 값을 검색할 때 사용하는 조건은?", options:["= NULL", "== NULL", "IS NULL", "EQUALS NULL"], answer:3 },
    { id:"db_073", question:"병행 제어에서 데드락(Deadlock)이란?", options:["트랜잭션 처리 속도가 느려지는 현상", "두 트랜잭션이 서로 상대방의 자원을 기다리며 무한 대기하는 상태", "데이터가 손실되는 현상", "인덱스가 손상되는 현상"], answer:2 },
    { id:"db_074", question:"다음 중 DDL(데이터 정의어)에 해당하지 않는 것은?", options:["CREATE", "ALTER", "DROP", "INSERT"], answer:4 },
    { id:"db_075", question:"기본키는 몇 개의 속성으로 구성될 수 있는가?", options:["반드시 1개", "반드시 2개 이상", "1개 이상(복합 기본키 가능)", "최대 3개"], answer:3 },
    { id:"db_076", question:"외래키(Foreign Key)가 참조하는 것은?", options:["다른 테이블의 외래키", "다른 테이블의 기본키", "같은 테이블의 기본키", "다른 테이블의 인덱스"], answer:2 },
    { id:"db_077", question:"정규화 단계 중 가장 낮은 단계는?", options:["BCNF", "제3정규형", "제2정규형", "제1정규형"], answer:4 },
    { id:"db_078", question:"데이터베이스 시스템에서 DBMS의 역할로 옳은 것은?", options:["하드웨어를 직접 제어한다", "데이터를 정의, 조작, 제어하는 역할을 한다", "운영체제 대신 자원을 관리한다", "네트워크를 관리한다"], answer:2 },
    { id:"db_079", question:"SQL에서 LIKE 연산자와 함께 임의의 한 문자를 대체하는 와일드카드는?", options:["%", "_", "*", "?"], answer:2 },
    { id:"db_080", question:"SQL에서 LIKE 연산자와 함께 임의의 여러 문자를 대체하는 와일드카드는?", options:["%", "_", "*", "?"], answer:1 },
    { id:"db_081", question:"뷰(View)에 대한 설명으로 옳은 것은?", options:["물리적으로 데이터를 저장한다", "기본 테이블 삭제 시에도 뷰는 유지된다", "SELECT 문으로 정의되는 가상 테이블이다", "인덱스를 자동으로 생성한다"], answer:3 },
    { id:"db_082", question:"SQL에서 집계 함수를 사용한 결과에 조건을 적용할 때 사용하는 절은?", options:["WHERE", "GROUP BY", "ORDER BY", "HAVING"], answer:4 },
    { id:"db_083", question:"관계 대수의 DIVISION 연산에 대한 설명으로 옳은 것은?", options:["두 릴레이션의 합집합을 구한다", "한 릴레이션의 모든 튜플에 대응하는 튜플을 추출한다", "두 릴레이션의 차집합을 구한다", "두 릴레이션을 특정 속성 기준으로 합친다"], answer:2 },
    { id:"db_084", question:"데이터베이스에서 스키마(Schema)란?", options:["실제 저장된 데이터", "데이터베이스 구조와 제약 조건의 명세", "물리적 저장 장치", "트랜잭션 처리 결과"], answer:2 },
    { id:"db_085", question:"인덱스(Index) 사용으로 가장 큰 효과를 볼 수 있는 연산은?", options:["INSERT", "UPDATE", "DELETE", "SELECT"], answer:4 },
    { id:"db_086", question:"해싱(Hashing)에서 충돌 해결 방법 중 체이닝(Chaining)에 대한 설명은?", options:["다음 빈 버킷을 찾아 저장한다", "연결 리스트로 충돌된 키를 연결한다", "해시 함수를 다시 적용한다", "테이블 크기를 늘린다"], answer:2 },
    { id:"db_087", question:"1:N(일대다) 관계에서 외래키는 어느 쪽 테이블에 위치하는가?", options:["1쪽 테이블", "N쪽 테이블", "양쪽 모두", "별도의 연결 테이블"], answer:2 },
    { id:"db_088", question:"M:N(다대다) 관계를 릴레이션으로 변환할 때 일반적인 방법은?", options:["두 테이블 중 하나에 외래키 추가", "별도의 연결 테이블 생성", "두 테이블을 하나로 합침", "기존 구조를 그대로 사용"], answer:2 },
    { id:"db_089", question:"SQL에서 테이블의 모든 데이터를 삭제하지만 테이블 구조는 유지하는 명령어는?", options:["DROP TABLE", "DELETE FROM", "TRUNCATE TABLE", "REMOVE TABLE"], answer:3 },
    { id:"db_090", question:"트랜잭션 처리 시 저장점(Savepoint)의 역할은?", options:["트랜잭션을 완전히 종료한다", "트랜잭션 내 특정 지점까지 롤백할 수 있게 한다", "새로운 트랜잭션을 시작한다", "인덱스를 재구성한다"], answer:2 },
    { id:"db_091", question:"데이터베이스에서 도메인(Domain)의 의미는?", options:["테이블의 행 수", "속성이 가질 수 있는 값의 범위", "테이블의 열 수", "인덱스의 종류"], answer:2 },
    { id:"db_092", question:"관계형 데이터베이스에서 릴레이션의 특성으로 옳은 것은?", options:["동일한 튜플이 존재할 수 있다", "튜플의 순서가 중요하다", "속성의 순서가 중요하다", "모든 속성값은 원자값이다"], answer:4 },
    { id:"db_093", question:"SQL에서 두 테이블을 연결할 때 사용하는 절은?", options:["CONNECT", "LINK", "JOIN", "MERGE"], answer:3 },
    { id:"db_094", question:"데이터베이스 회복(Recovery) 기법 중 로그(Log)를 이용하는 이유는?", options:["인덱스를 빠르게 생성하기 위해", "장애 발생 시 이전 상태로 복원하기 위해", "데이터 압축을 위해", "쿼리 최적화를 위해"], answer:2 },
    { id:"db_095", question:"E-R 다이어그램에서 약한 개체(Weak Entity)를 나타내는 기호는?", options:["단일 직사각형", "이중 직사각형", "단일 타원", "마름모"], answer:2 },
    { id:"db_096", question:"SQL에서 부속 질의(Subquery)란?", options:["다른 테이블과 조인하는 쿼리", "SELECT 문 안에 포함된 또 다른 SELECT 문", "저장 프로시저를 호출하는 문", "뷰를 생성하는 문"], answer:2 },
    { id:"db_097", question:"정규화 과정에서 이상(Anomaly) 현상의 종류가 아닌 것은?", options:["삽입 이상", "삭제 이상", "갱신 이상", "조회 이상"], answer:4 },
    { id:"db_098", question:"데이터베이스 설계에서 요구분석 단계의 목적은?", options:["물리적 저장 구조 결정", "사용자 요구사항 파악 및 명세화", "E-R 다이어그램 작성", "SQL 스크립트 작성"], answer:2 },
    { id:"db_099", question:"관계 대수에서 카티션 프로덕트(Cartesian Product)는 무엇인가?", options:["두 릴레이션의 교집합", "두 릴레이션의 모든 튜플 조합", "두 릴레이션의 차집합", "두 릴레이션의 합집합"], answer:2 },
    { id:"db_100", question:"SQL에서 외래키를 설정할 때 사용하는 키워드는?", options:["PRIMARY KEY", "FOREIGN KEY", "UNIQUE KEY", "INDEX KEY"], answer:2 }
  ],
  "전자계산기구조": [
    { id:"ca_001", question:"CPU의 구성 요소에 해당하지 않는 것은?", options:["연산장치(ALU)", "제어장치", "레지스터", "하드디스크"], answer:4 },
    { id:"ca_002", question:"다음에 실행할 명령어의 주소를 저장하는 레지스터는?", options:["누산기(AC)", "프로그램 카운터(PC)", "명령어 레지스터(IR)", "메모리 주소 레지스터(MAR)"], answer:2 },
    { id:"ca_003", question:"캐시 메모리에 대한 설명으로 옳지 않은 것은?", options:["CPU와 주기억장치 사이에 위치한다", "주기억장치보다 속도가 빠르다", "주기억장치보다 용량이 크다", "적중률이 높을수록 성능이 향상된다"], answer:3 },
    { id:"ca_004", question:"DMA(Direct Memory Access)에 대한 설명으로 옳은 것은?", options:["CPU를 통해 데이터를 전송한다", "CPU 없이 주기억장치와 입출력장치 간 직접 데이터 전송", "항상 인터럽트 방식과 함께 사용된다", "소프트웨어로만 구현된다"], answer:2 },
    { id:"ca_005", question:"파이프라인(Pipeline) 기법의 목적으로 가장 적합한 것은?", options:["메모리 용량 절약", "명령어 처리 속도 향상", "오류 발생 감소", "전력 소비 감소"], answer:2 },
    { id:"ca_006", question:"현재 실행 중인 명령어를 저장하는 레지스터는?", options:["프로그램 카운터(PC)", "누산기(AC)", "명령어 레지스터(IR)", "스택 포인터(SP)"], answer:3 },
    { id:"ca_007", question:"ALU(산술논리연산장치)의 주요 기능으로 옳은 것은?", options:["명령어 해독", "산술 및 논리 연산 수행", "입출력 제어", "주기억장치 관리"], answer:2 },
    { id:"ca_008", question:"메모리 주소 레지스터(MAR)의 역할로 옳은 것은?", options:["연산 결과를 임시 저장", "접근할 메모리의 주소를 저장", "현재 명령어를 저장", "다음 명령어 주소를 저장"], answer:2 },
    { id:"ca_009", question:"메모리 버퍼 레지스터(MBR)에 대한 설명으로 옳은 것은?", options:["CPU와 메모리 사이에 전송될 데이터를 임시 저장", "다음 명령어의 주소를 저장", "논리 연산 결과를 저장", "스택의 최상위 주소를 저장"], answer:1 },
    { id:"ca_010", question:"누산기(AC, Accumulator)의 주요 역할은?", options:["다음 명령어 주소 보관", "연산 결과를 임시 저장", "메모리 주소 보관", "입출력 데이터 버퍼링"], answer:2 },
    { id:"ca_011", question:"기억장치 계층 구조를 속도가 빠른 순서로 올바르게 나열한 것은?", options:["레지스터 > 캐시 > 주기억장치 > 보조기억장치", "캐시 > 레지스터 > 주기억장치 > 보조기억장치", "주기억장치 > 캐시 > 레지스터 > 보조기억장치", "보조기억장치 > 주기억장치 > 캐시 > 레지스터"], answer:1 },
    { id:"ca_012", question:"RAM(Random Access Memory)의 특징으로 옳지 않은 것은?", options:["전원이 꺼지면 데이터가 소멸된다", "읽기와 쓰기가 모두 가능하다", "주기억장치로 주로 사용된다", "전원이 꺼져도 데이터가 유지된다"], answer:4 },
    { id:"ca_013", question:"ROM(Read Only Memory)에 대한 설명으로 옳은 것은?", options:["읽기와 쓰기가 자유롭다", "전원이 꺼지면 내용이 사라진다", "전원이 꺼져도 내용이 유지되는 비휘발성 메모리", "캐시 메모리의 일종이다"], answer:3 },
    { id:"ca_014", question:"캐시 메모리의 적중률(Hit Ratio)에 대한 설명으로 옳은 것은?", options:["적중률이 낮을수록 시스템 성능이 향상된다", "적중률은 캐시에서 찾은 횟수를 전체 접근 횟수로 나눈 값이다", "적중률은 항상 100%이다", "적중률은 캐시 용량과 무관하다"], answer:2 },
    { id:"ca_015", question:"가상 메모리(Virtual Memory)를 사용하는 주된 목적은?", options:["CPU 처리 속도 향상", "실제 주기억장치보다 더 큰 주소 공간을 사용하기 위해", "캐시 적중률 향상", "입출력 속도 향상"], answer:2 },
    { id:"ca_016", question:"2진수 1010을 10진수로 변환하면?", options:["8", "10", "12", "14"], answer:2 },
    { id:"ca_017", question:"10진수 15를 2진수로 변환하면?", options:["1110", "1111", "1101", "1011"], answer:2 },
    { id:"ca_018", question:"16진수 A는 10진수로 얼마인가?", options:["8", "10", "11", "12"], answer:2 },
    { id:"ca_019", question:"2진수 1111의 1의 보수는?", options:["0000", "0001", "1110", "1000"], answer:1 },
    { id:"ca_020", question:"2의 보수를 구하는 방법으로 옳은 것은?", options:["각 비트를 반전시킨다", "1의 보수에 1을 더한다", "1의 보수에서 1을 뺀다", "각 비트를 반전시키고 2를 더한다"], answer:2 },
    { id:"ca_021", question:"AND 게이트의 동작으로 옳은 것은?", options:["두 입력 중 하나라도 1이면 출력이 1", "두 입력이 모두 1일 때만 출력이 1", "입력이 0이면 출력이 1", "두 입력이 같으면 출력이 1"], answer:2 },
    { id:"ca_022", question:"OR 게이트의 동작으로 옳은 것은?", options:["두 입력이 모두 1일 때만 출력이 1", "두 입력이 모두 0일 때만 출력이 0", "입력이 0이면 출력이 1", "두 입력이 같으면 출력이 0"], answer:2 },
    { id:"ca_023", question:"NOT 게이트(인버터)의 동작으로 옳은 것은?", options:["두 입력이 모두 1일 때 출력이 1", "입력과 반대의 값을 출력", "두 입력 중 하나가 1이면 출력이 1", "두 입력이 같으면 출력이 1"], answer:2 },
    { id:"ca_024", question:"NAND 게이트는 어떤 게이트들의 조합인가?", options:["OR + NOT", "AND + NOT", "NOR + NOT", "XOR + NOT"], answer:2 },
    { id:"ca_025", question:"NOR 게이트의 출력이 1이 되는 조건은?", options:["두 입력이 모두 1일 때", "두 입력이 모두 0일 때", "두 입력 중 하나라도 1일 때", "두 입력이 서로 다를 때"], answer:2 },
    { id:"ca_026", question:"XOR(배타적 논리합) 게이트의 동작으로 옳은 것은?", options:["두 입력이 모두 1일 때 출력이 1", "두 입력이 서로 다를 때 출력이 1", "두 입력 중 하나라도 1이면 출력이 1", "두 입력이 모두 0일 때 출력이 1"], answer:2 },
    { id:"ca_027", question:"SR 플립플롭에서 S=1, R=0 일 때 출력 Q의 상태는?", options:["Q=0", "Q=1", "Q 불변", "불확정"], answer:2 },
    { id:"ca_028", question:"SR 플립플롭에서 S=1, R=1 일 때의 상태는?", options:["Q=0", "Q=1", "Q 불변", "금지(불확정) 상태"], answer:4 },
    { id:"ca_029", question:"JK 플립플롭에서 J=1, K=1 일 때의 동작은?", options:["Q=0", "Q=1", "현재 상태 유지", "현재 상태의 반전(토글)"], answer:4 },
    { id:"ca_030", question:"D 플립플롭의 특징으로 옳은 것은?", options:["S=R=1 금지 상태가 존재한다", "클록 에지에서 D 입력이 그대로 Q에 전달된다", "두 개의 입력(J, K)을 가진다", "토글 기능을 기본으로 한다"], answer:2 },
    { id:"ca_031", question:"T 플립플롭에서 T=1일 때의 동작은?", options:["Q=0 고정", "Q=1 고정", "현재 상태 유지", "출력이 반전(토글)된다"], answer:4 },
    { id:"ca_032", question:"명령어 형식에서 연산코드(OP Code)의 역할은?", options:["데이터의 저장 주소를 나타낸다", "수행할 연산의 종류를 나타낸다", "데이터의 크기를 나타낸다", "레지스터 번호를 나타낸다"], answer:2 },
    { id:"ca_033", question:"명령어 형식에서 오퍼랜드(Operand)의 역할은?", options:["수행할 연산의 종류를 지정", "연산에 사용될 데이터 또는 데이터의 주소를 지정", "명령어의 우선순위를 지정", "인터럽트 신호를 지정"], answer:2 },
    { id:"ca_034", question:"즉시 주소 지정 방식(Immediate Addressing)에 대한 설명으로 옳은 것은?", options:["오퍼랜드가 데이터의 주소를 나타낸다", "오퍼랜드 자체가 실제 데이터이다", "오퍼랜드가 가리키는 주소에 실제 주소가 있다", "레지스터 번호를 오퍼랜드로 사용한다"], answer:2 },
    { id:"ca_035", question:"직접 주소 지정 방식(Direct Addressing)에 대한 설명으로 옳은 것은?", options:["오퍼랜드 자체가 실제 데이터", "오퍼랜드가 실제 데이터가 저장된 메모리 주소", "오퍼랜드가 가리키는 주소에 실제 주소가 저장", "레지스터에 데이터가 저장"], answer:2 },
    { id:"ca_036", question:"간접 주소 지정 방식(Indirect Addressing)에 대한 설명으로 옳은 것은?", options:["오퍼랜드 자체가 실제 데이터", "오퍼랜드가 실제 메모리 주소", "오퍼랜드가 가리키는 메모리 위치에 실제 데이터의 주소가 있다", "레지스터 번호를 오퍼랜드로 사용"], answer:3 },
    { id:"ca_037", question:"레지스터 주소 지정 방식(Register Addressing)의 특징으로 옳은 것은?", options:["오퍼랜드가 메모리 주소를 가리킨다", "데이터가 레지스터에 저장되어 있어 접근 속도가 빠르다", "메모리를 두 번 접근해야 한다", "오퍼랜드 자체가 데이터이다"], answer:2 },
    { id:"ca_038", question:"상대 주소 지정 방식(Relative Addressing)에서 유효 주소 계산에 사용되는 레지스터는?", options:["누산기(AC)", "명령어 레지스터(IR)", "프로그램 카운터(PC)", "메모리 버퍼 레지스터(MBR)"], answer:3 },
    { id:"ca_039", question:"입출력 방식 중 CPU가 입출력 장치의 상태를 계속 확인하는 방식은?", options:["인터럽트 방식", "DMA 방식", "프로그램(폴링) 방식", "채널 방식"], answer:3 },
    { id:"ca_040", question:"인터럽트(Interrupt) 방식의 특징으로 옳은 것은?", options:["CPU가 입출력 완료를 계속 확인한다", "입출력 완료 시 장치가 CPU에게 신호를 보낸다", "CPU 없이 메모리와 입출력 장치가 직접 통신한다", "소프트웨어로만 처리된다"], answer:2 },
    { id:"ca_041", question:"DMA(Direct Memory Access) 방식의 장점으로 옳은 것은?", options:["구현이 매우 간단하다", "CPU 개입 없이 대량 데이터 전송이 가능하다", "소량 데이터 전송에 적합하다", "캐시 메모리를 활용한다"], answer:2 },
    { id:"ca_042", question:"버스(Bus)의 종류 중 데이터 버스(Data Bus)의 역할은?", options:["메모리 주소를 전달한다", "제어 신호를 전달한다", "실제 데이터를 전달한다", "인터럽트 신호를 전달한다"], answer:3 },
    { id:"ca_043", question:"주소 버스(Address Bus)의 특징으로 옳은 것은?", options:["양방향 통신이 가능하다", "CPU에서 메모리나 입출력 장치로 단방향 전달", "데이터를 전달한다", "클록 신호를 전달한다"], answer:2 },
    { id:"ca_044", question:"제어 버스(Control Bus)가 전달하는 신호에 해당하지 않는 것은?", options:["읽기/쓰기 신호", "인터럽트 신호", "클록 신호", "실제 처리 데이터"], answer:4 },
    { id:"ca_045", question:"파이프라인의 단점으로 옳은 것은?", options:["명령어 처리량이 감소한다", "분기 명령어 발생 시 파이프라인이 비워지는 문제가 생길 수 있다", "레지스터가 필요 없어진다", "메모리 용량이 증가한다"], answer:2 },
    { id:"ca_046", question:"캐시 메모리의 지역성(Locality) 원리 중 시간적 지역성(Temporal Locality)이란?", options:["최근에 사용한 데이터는 곧 다시 사용될 가능성이 높다", "최근에 사용한 데이터 근처의 데이터가 사용될 가능성이 높다", "데이터는 순서대로 접근된다", "캐시 용량이 클수록 적중률이 높다"], answer:1 },
    { id:"ca_047", question:"캐시 메모리의 공간적 지역성(Spatial Locality)이란?", options:["최근에 사용한 데이터는 곧 다시 사용될 가능성이 높다", "최근에 접근한 데이터 근처의 데이터도 곧 사용될 가능성이 높다", "데이터는 무작위로 접근된다", "캐시가 클수록 효율이 높다"], answer:2 },
    { id:"ca_048", question:"10진수 255를 16진수로 변환하면?", options:["EE", "FF", "FE", "EF"], answer:2 },
    { id:"ca_049", question:"2진수 1100의 10진수 값은?", options:["10", "11", "12", "13"], answer:3 },
    { id:"ca_050", question:"불 대수(Boolean Algebra)에서 A + 0 의 결과는?", options:["0", "1", "A", "A'"], answer:3 },
    { id:"ca_051", question:"불 대수에서 A · 1 의 결과는?", options:["0", "1", "A", "A'"], answer:3 },
    { id:"ca_052", question:"불 대수에서 A + 1 의 결과는?", options:["0", "1", "A", "A'"], answer:2 },
    { id:"ca_053", question:"불 대수에서 A · 0 의 결과는?", options:["0", "1", "A", "A'"], answer:1 },
    { id:"ca_054", question:"드모르간의 법칙으로 옳은 것은?", options:["(A+B)' = A' + B'", "(A·B)' = A' · B'", "(A+B)' = A' · B'", "(A·B)' = A + B"], answer:3 },
    { id:"ca_055", question:"SRAM과 DRAM의 비교로 옳은 것은?", options:["DRAM이 SRAM보다 속도가 빠르다", "SRAM은 재충전(Refresh)이 필요하다", "SRAM이 DRAM보다 속도가 빠르고 가격이 비싸다", "DRAM은 플립플롭으로 구성된다"], answer:3 },
    { id:"ca_056", question:"DRAM(Dynamic RAM)의 특징으로 옳은 것은?", options:["재충전이 필요 없다", "SRAM보다 속도가 빠르다", "일정 시간마다 재충전(Refresh)이 필요하다", "캐패시터가 아닌 플립플롭으로 구성된다"], answer:3 },
    { id:"ca_057", question:"제어장치(Control Unit)의 주요 기능으로 옳은 것은?", options:["산술 및 논리 연산 수행", "명령어를 해독하고 각 장치에 제어 신호를 보낸다", "데이터를 임시 저장", "입출력 장치를 직접 구동"], answer:2 },
    { id:"ca_058", question:"주기억장치(Main Memory)의 특징으로 옳지 않은 것은?", options:["CPU가 직접 접근할 수 있다", "보조기억장치보다 속도가 빠르다", "보조기억장치보다 용량이 크다", "반도체 메모리로 구성된다"], answer:3 },
    { id:"ca_060", question:"보조기억장치의 예로 적절하지 않은 것은?", options:["하드디스크(HDD)", "SSD", "USB 플래시 드라이브", "캐시 메모리"], answer:4 },
    { id:"ca_061", question:"인터럽트 처리 후 복귀할 주소를 저장하는 곳은?", options:["캐시 메모리", "스택(Stack)", "레지스터 파일", "명령어 레지스터"], answer:2 },
    { id:"ca_062", question:"명령어 사이클(Instruction Cycle)의 기본 단계로 옳은 것은?", options:["인출(Fetch) → 해독(Decode) → 실행(Execute)", "실행(Execute) → 해독(Decode) → 인출(Fetch)", "해독(Decode) → 인출(Fetch) → 실행(Execute)", "인출(Fetch) → 실행(Execute) → 해독(Decode)"], answer:1 },
    { id:"ca_063", question:"8비트로 표현할 수 있는 부호 없는 정수의 최댓값은?", options:["127", "128", "255", "256"], answer:3 },
    { id:"ca_064", question:"16진수 F의 2진수 표현은?", options:["1011", "1100", "1110", "1111"], answer:4 },
    { id:"ca_065", question:"2진수 0101을 10진수로 변환하면?", options:["3", "4", "5", "6"], answer:3 },
    { id:"ca_066", question:"파이프라인에서 '해저드(Hazard)'란 무엇인가?", options:["파이프라인의 처리 속도가 높아지는 현상", "파이프라인의 정상 실행을 방해하는 조건이나 상황", "레지스터 수를 줄이는 기법", "캐시 미스가 발생하는 현상"], answer:2 },
    { id:"ca_067", question:"스택 포인터(SP, Stack Pointer)의 역할은?", options:["다음 명령어 주소 저장", "스택의 최상위 주소를 가리킨다", "연산 결과를 저장", "메모리 접근 주소를 저장"], answer:2 },
    { id:"ca_068", question:"범용 레지스터(General Purpose Register)의 특징으로 옳은 것은?", options:["특정 용도로만 사용된다", "프로그래머가 다양한 용도로 사용할 수 있다", "주소 저장 전용이다", "연산 결과만 저장한다"], answer:2 },
    { id:"ca_069", question:"플래그 레지스터(Flag Register)에 저장되는 정보로 옳은 것은?", options:["다음 명령어 주소", "연산 결과의 상태 정보(부호, 오버플로, 제로 등)", "현재 명령어", "메모리 주소"], answer:2 },
    { id:"ca_070", question:"10진수 10을 2진수로 변환하면?", options:["1000", "1001", "1010", "1011"], answer:3 },
    { id:"ca_071", question:"2진수 1000의 2의 보수는?", options:["0111", "1000", "0000", "1001"], answer:2 },
    { id:"ca_072", question:"오버플로(Overflow)가 발생하는 경우는?", options:["연산 결과가 0일 때", "연산 결과가 해당 자료형의 표현 범위를 초과할 때", "두 수가 같을 때", "음수와 양수를 더할 때"], answer:2 },
    { id:"ca_073", question:"ROM의 종류 중 자외선으로 내용을 지우고 다시 쓸 수 있는 것은?", options:["Mask ROM", "PROM", "EPROM", "EEPROM"], answer:3 },
    { id:"ca_074", question:"플래시 메모리(Flash Memory)의 특징으로 옳은 것은?", options:["휘발성 메모리이다", "전기적으로 내용을 지우고 다시 쓸 수 있는 비휘발성 메모리", "재충전(Refresh)이 필요하다", "속도가 DRAM보다 빠르다"], answer:2 },
    { id:"ca_075", question:"가상 메모리에서 페이지 폴트(Page Fault)란?", options:["페이지 크기가 너무 클 때 발생하는 오류", "접근하려는 페이지가 주기억장치에 없을 때 발생하는 상황", "캐시 메모리가 꽉 찼을 때 발생하는 오류", "레지스터 오버플로가 발생하는 상황"], answer:2 },
    { id:"ca_076", question:"세그멘테이션(Segmentation) 기법은 무엇에 관한 것인가?", options:["메모리를 고정 크기 블록으로 나누는 기법", "프로그램을 논리적 단위(세그먼트)로 나누는 메모리 관리 기법", "캐시 메모리를 구성하는 방법", "CPU 스케줄링 기법"], answer:2 },
    { id:"ca_077", question:"채널(Channel) 방식의 입출력에 대한 설명으로 옳은 것은?", options:["CPU가 입출력을 직접 제어한다", "DMA보다 더 독립적으로 입출력을 처리하는 전용 프로세서를 사용한다", "폴링 방식의 일종이다", "소프트웨어 인터럽트만 사용한다"], answer:2 },
    { id:"ca_078", question:"인터럽트의 종류 중 하드웨어 인터럽트의 예로 옳은 것은?", options:["0으로 나누기 오류", "타이머 인터럽트", "소프트웨어 트랩", "시스템 호출"], answer:2 },
    { id:"ca_079", question:"인터럽트 처리 과정의 순서로 옳은 것은?", options:["인터럽트 발생 → 현재 상태 저장 → 인터럽트 서비스 루틴 실행 → 복귀", "인터럽트 서비스 루틴 실행 → 인터럽트 발생 → 현재 상태 저장 → 복귀", "현재 상태 저장 → 인터럽트 발생 → 복귀 → 인터럽트 서비스 루틴 실행", "복귀 → 인터럽트 발생 → 현재 상태 저장 → 인터럽트 서비스 루틴 실행"], answer:1 },
    { id:"ca_080", question:"16진수 1F를 10진수로 변환하면?", options:["30", "31", "32", "33"], answer:2 },
    { id:"ca_081", question:"AND 연산에서 A=1, B=0 일 때 결과는?", options:["0", "1", "A", "B"], answer:1 },
    { id:"ca_082", question:"OR 연산에서 A=0, B=0 일 때 결과는?", options:["0", "1", "A", "B"], answer:1 },
    { id:"ca_083", question:"XOR 연산에서 A=1, B=1 일 때 결과는?", options:["0", "1", "2", "불확정"], answer:1 },
    { id:"ca_084", question:"2진수 덧셈에서 1 + 1 의 결과(합, 올림수)는?", options:["합=0, 올림수=0", "합=1, 올림수=0", "합=0, 올림수=1", "합=1, 올림수=1"], answer:3 },
    { id:"ca_085", question:"멀티플렉서(MUX)의 기능으로 옳은 것은?", options:["여러 출력 중 하나를 선택하여 하나의 입력으로 전달", "여러 입력 중 하나를 선택하여 하나의 출력으로 전달", "두 수를 비교한다", "두 수를 더한다"], answer:2 },
    { id:"ca_086", question:"디코더(Decoder)의 기능으로 옳은 것은?", options:["여러 입력 중 하나를 선택", "n비트 입력을 최대 2^n 개의 출력선 중 하나를 활성화", "데이터를 압축한다", "오류를 수정한다"], answer:2 },
    { id:"ca_087", question:"순서 논리 회로(Sequential Logic Circuit)의 특징으로 옳은 것은?", options:["출력이 현재 입력에만 의존한다", "출력이 현재 입력과 이전 상태(기억)에 의존한다", "플립플롭을 사용하지 않는다", "조합 논리 회로의 일종이다"], answer:2 },
    { id:"ca_088", question:"조합 논리 회로(Combinational Logic Circuit)의 특징으로 옳은 것은?", options:["이전 상태를 기억한다", "플립플롭이 반드시 필요하다", "출력이 오직 현재 입력에만 의존한다", "클록 신호가 필요하다"], answer:3 },
    { id:"ca_089", question:"카운터(Counter)가 사용하는 기본 소자는?", options:["멀티플렉서", "플립플롭", "디코더", "전가산기"], answer:2 },
    { id:"ca_090", question:"시프트 레지스터(Shift Register)의 주요 기능은?", options:["산술 연산 수행", "데이터를 한 비트씩 이동(시프트)시킨다", "주소를 계산한다", "데이터를 압축한다"], answer:2 },
    { id:"ca_091", question:"기억장치 계층에서 레지스터에 대한 설명으로 옳지 않은 것은?", options:["CPU 내부에 위치한다", "가장 빠른 기억 장치이다", "용량이 매우 작다", "보조기억장치보다 용량이 크다"], answer:4 },
    { id:"ca_092", question:"페이징(Paging) 기법에 대한 설명으로 옳은 것은?", options:["메모리를 가변 크기로 분할한다", "메모리를 고정된 크기의 페이지로 나누어 관리한다", "외부 단편화가 발생한다", "논리적 단위로 메모리를 나눈다"], answer:2 },
    { id:"ca_093", question:"RISC(Reduced Instruction Set Computer)의 특징으로 옳은 것은?", options:["명령어 수가 많고 복잡하다", "명령어 수가 적고 단순하며 고정 길이 명령어를 사용한다", "하드웨어가 간단하여 칩 면적이 작다", "마이크로프로그램 방식을 주로 사용한다"], answer:2 },
    { id:"ca_094", question:"CISC(Complex Instruction Set Computer)의 특징으로 옳은 것은?", options:["명령어 수가 적고 단순하다", "고정 길이 명령어만 사용한다", "다양하고 복잡한 명령어를 가지며 가변 길이 명령어를 사용한다", "파이프라인 구현이 용이하다"], answer:3 },
    { id:"ca_095", question:"마이크로오퍼레이션(Micro-operation)이란?", options:["고급 프로그래밍 언어의 명령어", "CPU의 레지스터 전송 단위로 이루어지는 가장 기본적인 동작", "운영체제의 시스템 호출", "가상 메모리 페이지 교체 연산"], answer:2 },
    { id:"ca_096", question:"버스 중재(Bus Arbitration)가 필요한 이유는?", options:["버스 속도를 높이기 위해", "여러 장치가 동시에 버스를 사용하려 할 때 충돌을 방지하기 위해", "메모리 용량을 늘리기 위해", "CPU 연산 속도를 높이기 위해"], answer:2 },
    { id:"ca_097", question:"2진수 11111111의 2의 보수는?", options:["00000000", "00000001", "11111110", "10000000"], answer:2 },
    { id:"ca_098", question:"8진수 17을 10진수로 변환하면?", options:["13", "14", "15", "17"], answer:3 },
    { id:"ca_099", question:"하프 애더(Half Adder)와 풀 애더(Full Adder)의 차이점으로 옳은 것은?", options:["하프 애더가 올림수 입력을 처리할 수 있다", "풀 애더는 이전 단계의 올림수 입력을 처리할 수 있다", "하프 애더가 더 복잡하다", "풀 애더는 단일 비트만 처리한다"], answer:2 },
    { id:"ca_100", question:"다음 중 비휘발성(Non-volatile) 메모리에 해당하는 것은?", options:["SRAM", "DRAM", "플래시 메모리(Flash Memory)", "캐시 메모리"], answer:3 },
    { id:"ca_059", question:"보조기억장치의 특징으로 옳은 것은?", options:["전원이 꺼지면 데이터가 소멸된다", "CPU가 직접 접근한다", "주기억장치보다 용량이 크고 가격이 저렴하다", "주기억장치보다 속도가 빠르다"], answer:3 }
  ],
  "운영체제": [
    { id:"os_001", question:"교착상태(Deadlock)의 발생 조건이 아닌 것은?", options:["상호 배제(Mutual Exclusion)", "점유와 대기(Hold and Wait)", "선점(Preemption)", "환형 대기(Circular Wait)"], answer:3 },
    { id:"os_002", question:"라운드 로빈(Round Robin) CPU 스케줄링에서 핵심이 되는 요소는?", options:["우선순위", "시간 할당량(Time Quantum)", "도착 시간", "CPU 버스트 시간"], answer:2 },
    { id:"os_003", question:"다음 중 선점형(Preemptive) 스케줄링 알고리즘은?", options:["FCFS", "SJF", "라운드 로빈(RR)", "비선점 우선순위"], answer:3 },
    { id:"os_004", question:"페이지 교체 알고리즘 중 가장 오랫동안 사용되지 않은 페이지를 교체하는 알고리즘은?", options:["FIFO", "LRU", "OPT", "LFU"], answer:2 },
    { id:"os_005", question:"프로세스와 스레드에 대한 설명으로 옳은 것은?", options:["스레드는 프로세스보다 자원을 더 많이 사용한다", "같은 프로세스 내의 스레드들은 자원을 공유한다", "프로세스는 스레드보다 컨텍스트 스위칭 비용이 작다", "스레드는 독립적인 주소 공간을 가진다"], answer:2 },
    { id:"os_006", question:"운영체제의 주요 목적으로 가장 적절한 것은?", options:["하드웨어 제조 비용 절감", "컴퓨터 시스템 자원의 효율적 관리", "응용 프로그램 개발 지원", "네트워크 속도 향상"], answer:2 },
    { id:"os_007", question:"프로세스 제어 블록(PCB)에 포함되지 않는 정보는?", options:["프로세스 상태", "프로그램 카운터(PC)", "CPU 레지스터", "하드디스크 용량"], answer:4 },
    { id:"os_008", question:"프로세스의 상태 중 CPU를 사용하고 있는 상태는?", options:["준비(Ready)", "실행(Running)", "대기(Waiting)", "종료(Terminated)"], answer:2 },
    { id:"os_009", question:"세마포어(Semaphore)에서 P 연산의 의미는?", options:["세마포어 값을 증가시키고 자원을 반납한다", "세마포어 값을 감소시키고 자원을 획득한다", "프로세스를 종료한다", "인터럽트를 발생시킨다"], answer:2 },
    { id:"os_010", question:"가상 메모리(Virtual Memory)의 주요 목적은?", options:["CPU 속도를 향상시킨다", "실제 메모리보다 큰 프로그램을 실행할 수 있게 한다", "디스크 접근 속도를 높인다", "프로세스 수를 줄인다"], answer:2 },
    { id:"os_011", question:"FCFS(First Come First Served) 스케줄링의 특징으로 옳은 것은?", options:["선점형 스케줄링이다", "도착한 순서대로 CPU를 할당한다", "우선순위가 높은 프로세스를 먼저 실행한다", "짧은 작업을 먼저 처리한다"], answer:2 },
    { id:"os_012", question:"내부 단편화(Internal Fragmentation)가 발생하는 원인은?", options:["할당된 메모리 공간이 요청된 공간보다 작을 때", "할당된 메모리 공간이 요청된 공간보다 클 때", "메모리가 부족할 때", "페이지 교체가 발생할 때"], answer:2 },
    { id:"os_013", question:"페이징(Paging) 기법의 특징으로 옳지 않은 것은?", options:["외부 단편화가 발생하지 않는다", "페이지 테이블이 필요하다", "논리 주소를 물리 주소로 변환한다", "세그먼트 단위로 메모리를 관리한다"], answer:4 },
    { id:"os_014", question:"스래싱(Thrashing)이란 무엇인가?", options:["CPU 이용률이 매우 높은 상태", "프로세스가 페이지 교체에 대부분의 시간을 소비하는 현상", "메모리가 과도하게 남는 현상", "CPU 스케줄링이 자주 변경되는 현상"], answer:2 },
    { id:"os_015", question:"디스크 스케줄링 중 SSTF(Shortest Seek Time First)의 설명으로 옳은 것은?", options:["요청 순서대로 처리한다", "현재 헤드 위치에서 가장 가까운 요청을 먼저 처리한다", "헤드가 한 방향으로 끝까지 이동하며 처리한다", "가장 나중에 들어온 요청을 먼저 처리한다"], answer:2 },
    { id:"os_016", question:"교착상태 예방(Prevention) 방법의 설명으로 옳은 것은?", options:["교착상태 발생 후 탐지한다", "교착상태 발생 조건 중 하나를 제거하여 교착상태를 원천 봉쇄한다", "은행원 알고리즘을 사용한다", "주기적으로 시스템 상태를 검사한다"], answer:2 },
    { id:"os_017", question:"SJF(Shortest Job First) 스케줄링에 대한 설명으로 옳은 것은?", options:["도착 순서대로 처리한다", "CPU 버스트 시간이 짧은 프로세스를 먼저 처리한다", "우선순위가 높은 프로세스를 먼저 처리한다", "시간 할당량을 사용한다"], answer:2 },
    { id:"os_018", question:"세마포어에서 V 연산의 의미는?", options:["세마포어 값을 감소시키고 자원을 요청한다", "세마포어 값을 증가시키고 자원을 반납한다", "프로세스를 생성한다", "인터럽트를 처리한다"], answer:2 },
    { id:"os_019", question:"프로세스가 준비(Ready) 상태에서 실행(Running) 상태로 전이되는 것을 무엇이라 하는가?", options:["블로킹(Blocking)", "디스패치(Dispatch)", "웨이크업(Wakeup)", "스왑(Swap)"], answer:2 },
    { id:"os_020", question:"LRU(Least Recently Used) 페이지 교체 알고리즘의 교체 기준은?", options:["앞으로 가장 오래 사용되지 않을 페이지", "가장 적게 사용된 페이지", "가장 오랫동안 사용되지 않은 페이지", "가장 먼저 적재된 페이지"], answer:3 },
    { id:"os_021", question:"OPT(Optimal) 페이지 교체 알고리즘의 특징은?", options:["구현이 가장 쉽다", "앞으로 가장 오랫동안 사용되지 않을 페이지를 교체한다", "가장 오래된 페이지를 교체한다", "가장 많이 사용된 페이지를 교체한다"], answer:2 },
    { id:"os_022", question:"은행원 알고리즘(Banker's Algorithm)은 교착상태 해결 방법 중 어디에 해당하는가?", options:["예방(Prevention)", "회피(Avoidance)", "탐지(Detection)", "복구(Recovery)"], answer:2 },
    { id:"os_023", question:"외부 단편화(External Fragmentation)를 해결하는 방법은?", options:["페이징", "스왑", "압축(Compaction)", "캐싱"], answer:3 },
    { id:"os_024", question:"프로세스 제어 블록(PCB)의 역할로 가장 적절한 것은?", options:["CPU의 처리 속도를 높인다", "프로세스에 관한 모든 정보를 저장하여 스케줄링 및 관리에 활용한다", "메모리를 직접 관리한다", "입출력 장치를 제어한다"], answer:2 },
    { id:"os_025", question:"SCAN 디스크 스케줄링 알고리즘의 특징은?", options:["요청 순서대로 처리한다", "헤드가 한쪽 끝에서 반대쪽 끝까지 이동하면서 처리하고 방향을 바꾼다", "현재 위치에서 가장 가까운 요청을 처리한다", "원형으로 순환하며 처리한다"], answer:2 },
    { id:"os_026", question:"다단계 큐(Multilevel Queue) 스케줄링의 특징으로 옳은 것은?", options:["모든 프로세스가 동일한 큐에 배치된다", "프로세스를 여러 그룹으로 나누어 각각 다른 큐에 배치한다", "오직 우선순위만으로 스케줄링한다", "비선점 방식만 사용한다"], answer:2 },
    { id:"os_027", question:"페이지 부재(Page Fault)란 무엇인가?", options:["페이지 테이블이 손상된 경우", "참조한 페이지가 주기억장치에 없어 보조기억장치에서 불러와야 하는 상황", "페이지 크기가 너무 클 때 발생하는 오류", "메모리가 부족한 경우"], answer:2 },
    { id:"os_028", question:"스레드(Thread)에 대한 설명으로 옳지 않은 것은?", options:["프로세스 내에서 실행되는 흐름의 단위이다", "같은 프로세스 내의 스레드는 코드, 데이터, 힙을 공유한다", "스레드는 각자 독립적인 스택을 가진다", "스레드 간 컨텍스트 스위칭은 프로세스 간보다 비용이 크다"], answer:4 },
    { id:"os_029", question:"운영체제의 기능이 아닌 것은?", options:["프로세스 관리", "메모리 관리", "응용 프로그램 코딩", "파일 시스템 관리"], answer:3 },
    { id:"os_030", question:"교착상태의 환형 대기(Circular Wait) 조건이란?", options:["각 프로세스가 자원을 점유하고 있으면서 다른 자원을 요청하는 것", "프로세스들이 서로 상대방이 점유한 자원을 기다리는 순환 구조", "자원이 한 번에 하나의 프로세스에만 할당되는 것", "자원을 강제로 빼앗을 수 없는 것"], answer:2 },
    { id:"os_031", question:"SRT(Shortest Remaining Time) 스케줄링의 특징으로 옳은 것은?", options:["비선점형 스케줄링이다", "선점형 SJF 스케줄링으로 남은 실행 시간이 가장 짧은 프로세스를 선택한다", "우선순위를 기반으로 스케줄링한다", "FIFO 방식으로 처리한다"], answer:2 },
    { id:"os_032", question:"세그멘테이션(Segmentation) 기법의 특징으로 옳은 것은?", options:["고정된 크기의 단위로 메모리를 나눈다", "논리적 의미 단위(세그먼트)로 메모리를 나누며 외부 단편화가 발생한다", "내부 단편화만 발생한다", "페이지 테이블을 사용한다"], answer:2 },
    { id:"os_033", question:"FIFO 페이지 교체 알고리즘의 특징은?", options:["가장 오랫동안 사용되지 않은 페이지를 교체한다", "앞으로 가장 오래 사용되지 않을 페이지를 교체한다", "메모리에 가장 먼저 들어온 페이지를 교체한다", "가장 적게 사용된 페이지를 교체한다"], answer:3 },
    { id:"os_034", question:"프로세스가 실행 중 입출력 요청을 하면 어떤 상태로 전이되는가?", options:["준비(Ready)", "대기(Waiting)", "종료(Terminated)", "생성(New)"], answer:2 },
    { id:"os_035", question:"CPU 스케줄링의 목적으로 가장 적절한 것은?", options:["디스크 I/O를 줄이기 위해", "CPU 이용률을 높이고 프로세스의 대기 시간을 줄이기 위해", "메모리 사용량을 줄이기 위해", "스레드 수를 최대화하기 위해"], answer:2 },
    { id:"os_036", question:"교착상태 탐지(Detection) 후 복구 방법이 아닌 것은?", options:["프로세스를 강제 종료한다", "자원을 강제로 선점한다", "교착상태 조건 중 하나를 제거한다", "롤백(Rollback)을 수행한다"], answer:3 },
    { id:"os_037", question:"페이지 테이블(Page Table)의 역할은?", options:["프로세스의 우선순위를 저장한다", "논리 주소(페이지 번호)를 물리 주소(프레임 번호)로 변환하는 데 사용된다", "디스크 스케줄링 정보를 저장한다", "세마포어 값을 관리한다"], answer:2 },
    { id:"os_038", question:"LFU(Least Frequently Used) 페이지 교체 알고리즘의 교체 기준은?", options:["가장 오래된 페이지", "가장 오랫동안 사용되지 않은 페이지", "사용 빈도가 가장 낮은 페이지", "가장 최근에 사용된 페이지"], answer:3 },
    { id:"os_039", question:"라운드 로빈(Round Robin) 스케줄링에서 Time Quantum이 너무 크면 어떤 알고리즘과 유사해지는가?", options:["SJF", "FCFS", "SRT", "다단계 큐"], answer:2 },
    { id:"os_040", question:"C-SCAN 디스크 스케줄링의 특징으로 옳은 것은?", options:["요청된 순서대로 처리한다", "헤드가 한쪽 방향으로만 이동하며 처리하고, 끝에 도달하면 처음으로 돌아온다", "양방향으로 이동하며 처리한다", "현재 위치에서 가장 가까운 요청만 처리한다"], answer:2 },
    { id:"os_041", question:"교착상태 회피(Avoidance)의 핵심 개념은?", options:["교착상태 발생 조건을 원천적으로 제거한다", "시스템이 항상 안전 상태(Safe State)를 유지하도록 자원을 할당한다", "교착상태 발생 후 탐지하여 복구한다", "모든 자원을 공유하지 않는다"], answer:2 },
    { id:"os_042", question:"프로세스의 5가지 상태 중 자원 할당을 기다리며 CPU 큐에 대기하는 상태는?", options:["생성(New)", "준비(Ready)", "실행(Running)", "대기(Waiting)"], answer:2 },
    { id:"os_043", question:"메모리 관리에서 스와핑(Swapping)이란?", options:["페이지를 교체하는 것", "프로세스 전체를 보조기억장치로 내보내거나 다시 메모리로 불러오는 것", "세그먼트를 분할하는 것", "메모리를 압축하는 것"], answer:2 },
    { id:"os_044", question:"다음 중 비선점형(Non-preemptive) 스케줄링 알고리즘은?", options:["라운드 로빈(RR)", "SRT", "다단계 큐(Multilevel Queue)", "FCFS"], answer:4 },
    { id:"os_045", question:"파일 시스템(File System)의 주요 기능이 아닌 것은?", options:["파일 생성 및 삭제", "파일 접근 제어", "파일의 논리적/물리적 구조 관리", "CPU 스케줄링 수행"], answer:4 },
    { id:"os_046", question:"PCB에 저장되는 정보가 아닌 것은?", options:["프로세스 ID(PID)", "프로그램 카운터(PC)", "스케줄링 우선순위", "사용자의 비밀번호"], answer:4 },
    { id:"os_047", question:"MFU(Most Frequently Used) 페이지 교체 알고리즘의 교체 기준은?", options:["사용 빈도가 가장 낮은 페이지", "사용 빈도가 가장 높은 페이지", "가장 최근에 사용된 페이지", "가장 오래된 페이지"], answer:2 },
    { id:"os_048", question:"교착상태의 상호 배제(Mutual Exclusion) 조건이란?", options:["프로세스가 자원을 점유하며 다른 자원을 요청하는 것", "자원은 한 번에 한 프로세스만 사용할 수 있는 것", "프로세스들이 순환적으로 자원을 기다리는 것", "자원을 강제로 빼앗을 수 없는 것"], answer:2 },
    { id:"os_049", question:"프로세스를 정의한 것으로 가장 적절한 것은?", options:["보조기억장치에 저장된 프로그램", "실행 중인 프로그램으로 CPU에 의해 처리되는 능동적 개체", "운영체제의 핵심 구성 요소", "스레드의 집합"], answer:2 },
    { id:"os_050", question:"페이징 기법에서 내부 단편화가 발생하는 이유는?", options:["페이지 크기가 너무 작아서", "프로세스의 크기가 페이지 크기의 배수가 아니어서 마지막 페이지에 낭비 공간이 생기기 때문", "페이지 테이블의 크기가 너무 커서", "메모리가 부족해서"], answer:2 },
    { id:"os_051", question:"세마포어(Semaphore)의 주요 용도는?", options:["CPU 스케줄링 순서 결정", "프로세스 간 동기화 및 상호 배제 구현", "메모리 할당 관리", "디스크 스케줄링 수행"], answer:2 },
    { id:"os_052", question:"스레드가 프로세스보다 유리한 점은?", options:["스레드는 독립적인 메모리 공간을 가진다", "스레드 간 컨텍스트 스위칭이 프로세스보다 빠르고 자원 공유가 용이하다", "스레드는 보안이 더 강하다", "스레드 생성 비용이 프로세스보다 더 크다"], answer:2 },
    { id:"os_053", question:"교착상태의 비선점(Non-preemption) 조건이란?", options:["프로세스가 자원을 점유하며 추가 자원을 요청하는 것", "할당된 자원은 프로세스가 자발적으로 반납하기 전까지 강제로 빼앗을 수 없는 것", "자원이 하나의 프로세스에만 할당되는 것", "프로세스들이 원형으로 자원을 기다리는 것"], answer:2 },
    { id:"os_054", question:"운영체제가 사용자 프로그램에게 제공하는 인터페이스는?", options:["드라이버(Driver)", "시스템 호출(System Call)", "인터럽트(Interrupt)", "레지스터(Register)"], answer:2 },
    { id:"os_055", question:"FCFS 디스크 스케줄링의 특징으로 옳은 것은?", options:["현재 위치에서 가장 가까운 트랙을 먼저 처리한다", "요청이 들어온 순서대로 처리하며 구현이 간단하다", "헤드가 한 방향으로만 이동한다", "처리량(Throughput)이 가장 높다"], answer:2 },
    { id:"os_056", question:"가상 메모리 구현 방법 중 가장 일반적으로 사용되는 방법은?", options:["세그멘테이션", "요구 페이징(Demand Paging)", "스와핑", "압축(Compaction)"], answer:2 },
    { id:"os_057", question:"프로세스 상태 전이에서 '타임아웃'이 발생하면 어떤 상태로 바뀌는가?", options:["실행(Running) → 대기(Waiting)", "실행(Running) → 준비(Ready)", "준비(Ready) → 실행(Running)", "대기(Waiting) → 종료(Terminated)"], answer:2 },
    { id:"os_058", question:"다음 중 선점형 스케줄링의 특징으로 옳은 것은?", options:["일단 CPU를 할당받으면 작업이 끝날 때까지 CPU를 계속 사용한다", "높은 우선순위의 프로세스가 현재 실행 중인 프로세스를 밀어내고 CPU를 차지할 수 있다", "FCFS가 대표적인 예이다", "응답 시간이 항상 길다"], answer:2 },
    { id:"os_059", question:"파일 시스템에서 디렉터리(Directory)의 역할은?", options:["파일의 내용을 저장한다", "파일의 이름, 위치, 속성 등을 관리하는 구조이다", "CPU 스케줄링 정보를 저장한다", "네트워크 연결 정보를 저장한다"], answer:2 },
    { id:"os_060", question:"메모리 관리에서 최적 적합(Best Fit) 알고리즘이란?", options:["가장 큰 빈 공간에 프로세스를 할당한다", "가장 첫 번째 빈 공간에 프로세스를 할당한다", "프로세스를 수용할 수 있는 빈 공간 중 가장 작은 곳에 할당한다", "순서 관계없이 임의의 빈 공간에 할당한다"], answer:3 },
    { id:"os_061", question:"스래싱(Thrashing)을 해결하는 방법이 아닌 것은?", options:["워킹 셋(Working Set) 모델 사용", "다중 프로그래밍 정도를 낮춤", "페이지 프레임 수를 증가", "페이지 크기를 감소"], answer:4 },
    { id:"os_062", question:"교착상태 점유 대기(Hold and Wait) 조건이란?", options:["자원이 한 번에 하나씩 할당되는 것", "프로세스가 자원을 점유하면서 다른 자원을 요청하며 대기하는 것", "자원을 강제로 빼앗을 수 없는 것", "프로세스들이 서로의 자원을 기다리는 것"], answer:2 },
    { id:"os_063", question:"운영체제의 핵심 부분으로 항상 메모리에 상주하는 부분은?", options:["셸(Shell)", "커널(Kernel)", "사용자 인터페이스", "응용 프로그램"], answer:2 },
    { id:"os_064", question:"FIFO 페이지 교체 알고리즘에서 프레임 수를 늘렸음에도 페이지 부재가 증가하는 현상은?", options:["스래싱(Thrashing)", "벨라디의 역설(Belady's Anomaly)", "페이지 폴트 루프(Page Fault Loop)", "교착상태(Deadlock)"], answer:2 },
    { id:"os_065", question:"세마포어의 P 연산과 V 연산에 대한 설명으로 옳은 것은?", options:["P는 자원을 반납하고 V는 자원을 요청한다", "P는 자원을 요청(획득)하고 V는 자원을 반납(해제)한다", "두 연산 모두 세마포어 값을 증가시킨다", "두 연산 모두 세마포어 값을 감소시킨다"], answer:2 },
    { id:"os_066", question:"다음 중 스케줄링 알고리즘 선택 기준으로 옳지 않은 것은?", options:["CPU 이용률(Utilization)", "처리량(Throughput)", "반환 시간(Turnaround Time)", "메모리 용량(Memory Capacity)"], answer:4 },
    { id:"os_067", question:"프로세스 생성 시 부모 프로세스가 자식 프로세스를 만드는 것을 무엇이라 하는가?", options:["스케줄링(Scheduling)", "포크(Fork)", "세마포어(Semaphore)", "인터럽트(Interrupt)"], answer:2 },
    { id:"os_068", question:"메모리 관리 기법 중 최초 적합(First Fit) 알고리즘이란?", options:["프로세스를 수용할 수 있는 첫 번째 빈 공간에 할당한다", "가장 작은 빈 공간에 할당한다", "가장 큰 빈 공간에 할당한다", "마지막 빈 공간에 할당한다"], answer:1 },
    { id:"os_069", question:"페이지(Page)와 프레임(Frame)의 관계로 옳은 것은?", options:["페이지는 물리 메모리의 단위이고, 프레임은 논리 메모리의 단위이다", "페이지는 논리 메모리의 단위이고, 프레임은 물리 메모리의 단위이다", "페이지와 프레임은 같은 개념이다", "페이지는 디스크의 단위이다"], answer:2 },
    { id:"os_070", question:"선점형 우선순위 스케줄링의 문제점으로 발생할 수 있는 것은?", options:["오버헤드가 전혀 없다", "낮은 우선순위의 프로세스가 영원히 실행되지 못하는 기아(Starvation) 현상", "응답 시간이 항상 길다", "CPU 이용률이 낮아진다"], answer:2 },
    { id:"os_071", question:"기아(Starvation) 현상을 해결하는 방법은?", options:["페이지 교체", "에이징(Aging) 기법을 사용해 오래 기다린 프로세스의 우선순위를 높인다", "세마포어 사용", "다단계 큐 적용"], answer:2 },
    { id:"os_072", question:"운영체제에서 인터럽트(Interrupt)의 역할은?", options:["프로세스를 생성한다", "CPU가 현재 작업을 중단하고 긴급한 작업을 처리하도록 신호를 보내는 것", "메모리를 할당한다", "파일을 저장한다"], answer:2 },
    { id:"os_073", question:"다음 중 프로세스 동기화가 필요한 이유는?", options:["CPU 이용률을 낮추기 위해", "여러 프로세스가 공유 자원에 동시에 접근할 때 데이터 일관성을 유지하기 위해", "메모리 할당을 줄이기 위해", "디스크 읽기 속도를 높이기 위해"], answer:2 },
    { id:"os_074", question:"라운드 로빈에서 Time Quantum이 너무 작으면 어떤 문제가 발생하는가?", options:["기아 현상이 발생한다", "컨텍스트 스위칭 오버헤드가 증가한다", "응답 시간이 길어진다", "FCFS와 동일해진다"], answer:2 },
    { id:"os_075", question:"세그멘테이션(Segmentation)에서 주소 변환 시 사용하는 테이블은?", options:["페이지 테이블(Page Table)", "세그먼트 테이블(Segment Table)", "PCB 테이블", "파일 테이블"], answer:2 },
    { id:"os_076", question:"메모리 관리에서 워킹 셋(Working Set)이란?", options:["현재 실행 중인 모든 프로세스의 집합", "일정 시간 동안 프로세스가 참조한 페이지들의 집합", "사용하지 않는 메모리 공간", "페이지 테이블 전체"], answer:2 },
    { id:"os_077", question:"은행원 알고리즘에서 '안전 상태(Safe State)'란?", options:["모든 프로세스가 동시에 실행되는 상태", "시스템이 교착상태 없이 모든 프로세스를 완료할 수 있는 순서가 존재하는 상태", "모든 자원이 사용 중인 상태", "프로세스가 없는 상태"], answer:2 },
    { id:"os_078", question:"컨텍스트 스위칭(Context Switching)이란?", options:["프로세스를 종료하는 것", "CPU가 현재 실행 중인 프로세스의 상태를 저장하고 다음 프로세스 상태를 복원하는 과정", "새로운 프로세스를 생성하는 것", "메모리를 할당하는 것"], answer:2 },
    { id:"os_079", question:"디스크 스케줄링의 목적으로 가장 적절한 것은?", options:["CPU 이용률을 높이기 위해", "디스크 헤드의 이동 거리를 최소화하여 입출력 성능을 향상시키기 위해", "메모리 사용량을 줄이기 위해", "파일 시스템을 관리하기 위해"], answer:2 },
    { id:"os_080", question:"다음 중 교착상태 예방(Prevention) 방법으로 옳은 것은?", options:["은행원 알고리즘을 사용한다", "교착상태 발생 후 프로세스를 종료한다", "점유 대기 조건을 제거하여 프로세스 시작 시 필요한 모든 자원을 한 번에 할당한다", "자원 할당 그래프를 주기적으로 검사한다"], answer:3 },
    { id:"os_081", question:"프로세스의 생성(New) 상태에서 준비(Ready) 상태로 전이되는 조건은?", options:["CPU를 할당받았을 때", "운영체제가 프로세스 생성을 완료하고 승인했을 때", "입출력이 완료됐을 때", "타임아웃이 발생했을 때"], answer:2 },
    { id:"os_082", question:"페이지 크기가 작을 때의 장점은?", options:["페이지 테이블 크기가 작아진다", "내부 단편화가 줄어든다", "입출력 효율이 높아진다", "페이지 폴트 횟수가 줄어든다"], answer:2 },
    { id:"os_083", question:"다음 중 운영체제의 종류로 옳지 않은 것은?", options:["Windows", "Linux", "Android", "Photoshop"], answer:4 },
    { id:"os_084", question:"메모리 관리에서 최악 적합(Worst Fit) 알고리즘이란?", options:["가장 작은 빈 공간에 할당한다", "첫 번째 빈 공간에 할당한다", "가장 큰 빈 공간에 할당하여 남은 공간을 크게 유지한다", "마지막 빈 공간에 할당한다"], answer:3 },
    { id:"os_085", question:"스레드(Thread) 생성이 프로세스 생성보다 유리한 점은?", options:["보안이 더 강하다", "생성 및 종료 시간이 빠르고 자원 소비가 적다", "독립적인 주소 공간을 가진다", "메모리 사용량이 더 많다"], answer:2 },
    { id:"os_086", question:"교착상태 탐지(Detection) 방법의 설명으로 옳은 것은?", options:["교착상태가 발생하지 않도록 자원을 제한한다", "교착상태가 발생한 후 이를 찾아내어 복구하는 방법이다", "안전 상태를 유지하며 자원을 할당한다", "발생 조건 중 하나를 항상 제거한다"], answer:2 },
    { id:"os_087", question:"다음 중 PCB(Process Control Block)에 저장되는 정보는?", options:["프로세스 상태, 프로그램 카운터, CPU 레지스터, 스케줄링 정보", "사용자 이름, 로그인 시간, 비밀번호", "하드디스크 파티션 정보", "네트워크 IP 주소"], answer:1 },
    { id:"os_088", question:"세그멘테이션에서 외부 단편화를 줄이는 방법은?", options:["페이지 교체", "압축(Compaction)으로 사용 중인 세그먼트를 한쪽으로 모은다", "세마포어를 사용한다", "은행원 알고리즘을 적용한다"], answer:2 },
    { id:"os_089", question:"CPU 스케줄링에서 반환 시간(Turnaround Time)이란?", options:["프로세스가 CPU를 기다린 시간", "프로세스가 제출된 시점부터 완료될 때까지 걸린 총 시간", "CPU가 실제로 실행한 시간", "프로세스가 대기 큐에 있는 시간"], answer:2 },
    { id:"os_090", question:"다음 중 운영체제가 제공하는 서비스가 아닌 것은?", options:["프로세스 관리", "메모리 관리", "파일 시스템 관리", "전자상거래 기능"], answer:4 },
    { id:"os_091", question:"가상 메모리에서 페이지 부재(Page Fault) 처리 순서로 옳은 것은?", options:["페이지 교체 → 페이지 부재 감지 → 디스크에서 페이지 로드", "페이지 부재 감지 → 디스크에서 해당 페이지 로드 → 프로세스 재개", "디스크에서 페이지 로드 → 페이지 부재 감지 → 프로세스 종료", "프로세스 종료 → 페이지 교체 → 재시작"], answer:2 },
    { id:"os_092", question:"교착상태 회피에서 은행원 알고리즘이 필요로 하는 정보가 아닌 것은?", options:["각 프로세스의 최대 자원 요구량", "현재 자원 할당 상태", "남아있는 가용 자원", "각 프로세스의 도착 시간"], answer:4 },
    { id:"os_093", question:"다음 중 멀티스레딩(Multithreading)의 장점은?", options:["스레드 간 보안이 강화된다", "병렬 처리로 응답성이 향상되고 자원 공유가 효율적이다", "각 스레드가 독립적인 메모리를 사용한다", "컨텍스트 스위칭 비용이 증가한다"], answer:2 },
    { id:"os_094", question:"SSTF(Shortest Seek Time First)의 단점은?", options:["헤드 이동 거리가 너무 길다", "헤드에서 멀리 있는 요청은 계속 처리되지 못하는 기아(Starvation) 현상이 발생할 수 있다", "구현이 복잡하다", "처리량이 매우 낮다"], answer:2 },
    { id:"os_095", question:"운영체제에서 커널 모드와 사용자 모드를 구분하는 이유는?", options:["처리 속도를 높이기 위해", "운영체제의 핵심 자원을 보호하고 시스템 안정성을 높이기 위해", "메모리 사용량을 줄이기 위해", "디스크 입출력을 줄이기 위해"], answer:2 },
    { id:"os_096", question:"페이지 교체 알고리즘 중 이론적으로 가장 성능이 좋은 알고리즘은?", options:["FIFO", "LRU", "LFU", "OPT(Optimal)"], answer:4 },
    { id:"os_097", question:"다음 중 대기(Waiting) 상태에서 준비(Ready) 상태로의 전이 조건은?", options:["타임아웃 발생", "입출력 완료 또는 이벤트 발생", "CPU 할당", "프로세스 종료"], answer:2 },
    { id:"os_098", question:"파일 시스템에서 절대 경로(Absolute Path)에 대한 설명으로 옳은 것은?", options:["현재 디렉터리를 기준으로 경로를 표시한다", "루트 디렉터리(/)를 기준으로 파일의 위치를 표시한다", "상대적인 위치로 파일을 표시한다", "파일 이름만으로 위치를 표시한다"], answer:2 },
    { id:"os_099", question:"다음 중 CPU 스케줄링 기준(Criteria)으로 옳지 않은 것은?", options:["CPU 이용률(CPU Utilization)", "처리량(Throughput)", "대기 시간(Waiting Time)", "프로세스 크기(Process Size)"], answer:4 },
    { id:"os_100", question:"다음 중 프로세스 간 통신(IPC: Inter-Process Communication) 방법이 아닌 것은?", options:["파이프(Pipe)", "공유 메모리(Shared Memory)", "메시지 큐(Message Queue)", "페이지 교체(Page Replacement)"], answer:4 }
  ],
  "소프트웨어공학": [
    { id:"se_001", question:"폭포수 모델(Waterfall Model)의 특징으로 옳지 않은 것은?", options:["각 단계가 순차적으로 진행된다", "이전 단계가 완료된 후 다음 단계로 진행된다", "반복적이고 점진적으로 개발한다", "각 단계마다 결과물이 산출된다"], answer:3 },
    { id:"se_002", question:"블랙박스 테스트(Black-box Test)에 해당하는 기법은?", options:["구문 커버리지", "경로 커버리지", "동등 분할", "결정 커버리지"], answer:3 },
    { id:"se_003", question:"소프트웨어 결합도(Coupling)가 가장 낮은 형태는?", options:["내용 결합도", "공통 결합도", "자료 결합도", "제어 결합도"], answer:3 },
    { id:"se_004", question:"나선형(Spiral) 모델의 주요 특징은?", options:["순차적 단계 진행", "위험 분석을 포함한 반복 개발", "문서 중심의 개발", "최초 한 번에 완성"], answer:2 },
    { id:"se_005", question:"소프트웨어 형상 관리(SCM)의 목적으로 가장 적합한 것은?", options:["개발 비용 절감", "소프트웨어 변경을 체계적으로 관리", "테스트 자동화", "사용자 교육 지원"], answer:2 },
    { id:"se_006", question:"소프트웨어공학의 목적으로 가장 적합한 것은?", options:["하드웨어 성능 향상", "소프트웨어 개발의 생산성과 품질 향상", "운영체제 개발 표준화", "네트워크 보안 강화"], answer:2 },
    { id:"se_007", question:"애자일(Agile) 방법론의 특징으로 옳지 않은 것은?", options:["반복적이고 점진적인 개발", "고객과의 지속적인 협력", "변화에 유연하게 대응", "초기에 모든 요구사항을 완벽히 문서화"], answer:4 },
    { id:"se_008", question:"프로토타입(Prototype) 모델의 주요 특징은?", options:["위험 분석을 중심으로 진행", "사용자 요구를 초기에 시제품으로 확인", "순차적 단계를 엄격히 준수", "문서 작성 중심의 개발"], answer:2 },
    { id:"se_009", question:"소프트웨어 응집도(Cohesion)가 가장 높은 형태는?", options:["우연적 응집도", "논리적 응집도", "기능적 응집도", "시간적 응집도"], answer:3 },
    { id:"se_010", question:"UML 구조 다이어그램(Structural Diagram)에 해당하는 것은?", options:["유스케이스 다이어그램", "시퀀스 다이어그램", "클래스 다이어그램", "활동 다이어그램"], answer:3 },
    { id:"se_011", question:"소프트웨어 유지보수 유형 중 사용자의 새로운 기능 요구에 의해 수행되는 것은?", options:["수정(Corrective) 유지보수", "적응(Adaptive) 유지보수", "완전(Perfective) 유지보수", "예방(Preventive) 유지보수"], answer:3 },
    { id:"se_012", question:"화이트박스 테스트(White-box Test)에 해당하는 기법은?", options:["동등 분할", "경계값 분석", "원인-결과 그래프", "구문 커버리지"], answer:4 },
    { id:"se_013", question:"ISO/IEC 25010 소프트웨어 품질 특성에 해당하지 않는 것은?", options:["신뢰성", "사용성", "이식성", "확장성"], answer:4 },
    { id:"se_014", question:"COCOMO 모델에서 규모가 크고 복잡도가 높은 임베디드 시스템에 적용하는 유형은?", options:["Organic", "Semi-detached", "Embedded", "Extreme"], answer:3 },
    { id:"se_015", question:"소프트웨어 재사용(Reuse)의 이점으로 옳지 않은 것은?", options:["개발 생산성 향상", "소프트웨어 품질 향상", "개발 비용 절감", "초기 개발 복잡도 증가로 인한 품질 저하"], answer:4 },
    { id:"se_016", question:"디자인 패턴(Design Pattern) 중 생성(Creational) 패턴에 해당하는 것은?", options:["어댑터(Adapter)", "싱글톤(Singleton)", "옵저버(Observer)", "전략(Strategy)"], answer:2 },
    { id:"se_017", question:"알파 테스트(Alpha Test)에 대한 설명으로 옳은 것은?", options:["개발사 외부 고객이 자신의 환경에서 테스트", "개발사 내부에서 개발자와 함께 수행하는 테스트", "단위 모듈별로 독립적으로 수행하는 테스트", "시스템의 통합 여부를 확인하는 테스트"], answer:2 },
    { id:"se_018", question:"요구사항 중 시스템이 '얼마나 빠르게 응답해야 하는가'는 어떤 요구사항에 해당하는가?", options:["기능적 요구사항", "비기능적 요구사항", "사용자 요구사항", "도메인 요구사항"], answer:2 },
    { id:"se_019", question:"UML 행위 다이어그램(Behavioral Diagram)에 해당하지 않는 것은?", options:["유스케이스 다이어그램", "시퀀스 다이어그램", "컴포넌트 다이어그램", "활동 다이어그램"], answer:3 },
    { id:"se_020", question:"소프트웨어 테스트의 목적으로 가장 적합한 것은?", options:["소프트웨어의 오류를 발견하고 품질을 높임", "소프트웨어 개발 속도를 높임", "요구사항을 새롭게 발굴함", "소프트웨어 설계를 단순화함"], answer:1 },
    { id:"se_021", question:"결합도 강도가 높은 순서로 올바르게 나열된 것은?", options:["내용 > 공통 > 외부 > 제어 > 스탬프 > 자료", "자료 > 스탬프 > 제어 > 외부 > 공통 > 내용", "내용 > 외부 > 공통 > 제어 > 스탬프 > 자료", "공통 > 내용 > 제어 > 외부 > 자료 > 스탬프"], answer:1 },
    { id:"se_022", question:"RAD(Rapid Application Development) 모델의 특징으로 옳은 것은?", options:["장기간에 걸친 점진적 개발", "짧은 개발 주기와 반복적 사용자 참여", "철저한 문서화 중심의 개발", "위험 분석 반복을 핵심으로 함"], answer:2 },
    { id:"se_023", question:"소프트웨어 형상 항목(Configuration Item)에 해당하지 않는 것은?", options:["소스 코드", "설계 문서", "테스트 계획서", "개발자의 업무 일지"], answer:4 },
    { id:"se_024", question:"경계값 분석(Boundary Value Analysis) 기법은 어떤 테스트에 속하는가?", options:["화이트박스 테스트", "블랙박스 테스트", "단위 테스트", "회귀 테스트"], answer:2 },
    { id:"se_025", question:"소프트웨어 결합도 중 두 모듈이 같은 전역 변수를 사용하는 형태는?", options:["자료 결합도", "제어 결합도", "공통 결합도", "내용 결합도"], answer:3 },
    { id:"se_026", question:"응집도 중 모듈 내의 명령어들이 같은 시간대에 실행되는 것들로 구성된 형태는?", options:["논리적 응집도", "시간적 응집도", "순차적 응집도", "절차적 응집도"], answer:2 },
    { id:"se_027", question:"디자인 패턴 중 구조(Structural) 패턴에 해당하는 것은?", options:["팩토리 메소드(Factory Method)", "옵저버(Observer)", "어댑터(Adapter)", "커맨드(Command)"], answer:3 },
    { id:"se_028", question:"베타 테스트(Beta Test)에 대한 설명으로 옳은 것은?", options:["개발사 내부 환경에서 수행하는 테스트", "실제 사용자가 자신의 환경에서 수행하는 테스트", "단위 모듈 간 인터페이스를 확인하는 테스트", "개발자가 코드를 직접 보며 수행하는 테스트"], answer:2 },
    { id:"se_029", question:"소프트웨어 유지보수 유형 중 버그 수정을 위해 수행되는 것은?", options:["수정(Corrective) 유지보수", "적응(Adaptive) 유지보수", "완전(Perfective) 유지보수", "예방(Preventive) 유지보수"], answer:1 },
    { id:"se_030", question:"UML 시퀀스 다이어그램(Sequence Diagram)에 대한 설명으로 옳은 것은?", options:["시스템의 정적 구조를 표현", "객체 간의 메시지 교환 순서를 표현", "시스템의 컴포넌트 간 의존성 표현", "데이터베이스 스키마를 표현"], answer:2 },
    { id:"se_031", question:"소프트웨어 품질 특성 중 주어진 조건에서 명시된 성능 수준을 유지하는 능력은?", options:["기능성", "신뢰성", "사용성", "이식성"], answer:2 },
    { id:"se_032", question:"COCOMO 모델에서 소규모의 단순한 소프트웨어 개발에 적용하는 유형은?", options:["Organic", "Semi-detached", "Embedded", "Prototype"], answer:1 },
    { id:"se_033", question:"소프트웨어 형상 관리에서 '기준선(Baseline)'의 의미로 옳은 것은?", options:["소프트웨어 개발 비용의 기준", "공식적으로 검토되고 승인된 형상 항목의 상태", "테스트 완료 기준을 정의한 문서", "개발자 간 코딩 표준"], answer:2 },
    { id:"se_034", question:"결합도 중 한 모듈이 다른 모듈의 내부 논리를 직접 수정하는 형태는?", options:["자료 결합도", "공통 결합도", "제어 결합도", "내용 결합도"], answer:4 },
    { id:"se_035", question:"동등 분할(Equivalence Partitioning) 기법의 목적으로 옳은 것은?", options:["모든 경로를 테스트하기 위함", "입력 데이터를 동등한 클래스로 나눠 대표값으로 테스트", "경계에 위치한 값들을 집중적으로 테스트", "오류 유발 가능성이 높은 값을 예측하여 테스트"], answer:2 },
    { id:"se_036", question:"UML 유스케이스 다이어그램(Use Case Diagram)에서 시스템과 상호작용하는 외부 존재를 무엇이라 하는가?", options:["클래스(Class)", "액터(Actor)", "노드(Node)", "컴포넌트(Component)"], answer:2 },
    { id:"se_037", question:"소프트웨어 개발 생명주기(SDLC)의 일반적인 단계 순서로 올바른 것은?", options:["설계 → 분석 → 구현 → 테스트 → 유지보수", "분석 → 설계 → 구현 → 테스트 → 유지보수", "구현 → 분석 → 설계 → 테스트 → 유지보수", "분석 → 구현 → 설계 → 테스트 → 유지보수"], answer:2 },
    { id:"se_038", question:"화이트박스 테스트 기법 중 모든 조건식의 참/거짓을 모두 테스트하는 것은?", options:["구문 커버리지", "결정 커버리지", "조건 커버리지", "경로 커버리지"], answer:3 },
    { id:"se_039", question:"응집도 중 하나의 모듈이 서로 관련 없는 기능들의 집합으로 이루어진 형태는?", options:["기능적 응집도", "시간적 응집도", "논리적 응집도", "우연적 응집도"], answer:4 },
    { id:"se_040", question:"소프트웨어 재사용의 형태 중 기존 소프트웨어를 가져다 그대로 활용하는 방식은?", options:["생성에 의한 재사용", "합성에 의한 재사용", "변환에 의한 재사용", "수정에 의한 재사용"], answer:2 },
    { id:"se_041", question:"디자인 패턴 중 행위(Behavioral) 패턴에 해당하는 것은?", options:["싱글톤(Singleton)", "컴포지트(Composite)", "옵저버(Observer)", "퍼사드(Facade)"], answer:3 },
    { id:"se_042", question:"소프트웨어 품질 특성 중 다른 환경으로 이전될 수 있는 능력은?", options:["신뢰성", "유지보수성", "이식성", "효율성"], answer:3 },
    { id:"se_043", question:"나선형 모델(Spiral Model)에서 반복되는 4가지 활동의 순서로 옳은 것은?", options:["계획 → 구현 → 테스트 → 배포", "목표설정 → 위험분석 → 개발 및 검증 → 계획", "분석 → 설계 → 구현 → 테스트", "요구분석 → 설계 → 코딩 → 유지보수"], answer:2 },
    { id:"se_044", question:"UML 배치 다이어그램(Deployment Diagram)이 표현하는 내용으로 옳은 것은?", options:["객체 간의 메시지 흐름", "시스템의 물리적 배치 구조", "클래스 간의 상속 관계", "유스케이스와 액터 관계"], answer:2 },
    { id:"se_045", question:"소프트웨어 유지보수 유형 중 환경 변화(OS, 하드웨어 변경 등)에 대응하기 위한 것은?", options:["수정(Corrective) 유지보수", "적응(Adaptive) 유지보수", "완전(Perfective) 유지보수", "예방(Preventive) 유지보수"], answer:2 },
    { id:"se_046", question:"결합도 중 한 모듈이 다른 모듈로 제어 신호(플래그 등)를 넘겨 실행 흐름을 제어하는 형태는?", options:["자료 결합도", "스탬프 결합도", "제어 결합도", "외부 결합도"], answer:3 },
    { id:"se_047", question:"소프트웨어 테스트에서 오류 예측(Error Guessing) 기법에 대한 설명으로 옳은 것은?", options:["입력값의 경계에 집중하여 테스트", "입력 데이터를 동등한 클래스로 나눠 테스트", "경험을 바탕으로 오류가 발생할 것 같은 곳을 집중 테스트", "모든 분기 조건을 만족하도록 테스트"], answer:3 },
    { id:"se_048", question:"응집도 중 모듈 내 활동들이 동일한 입출력 데이터를 사용하는 형태는?", options:["기능적 응집도", "통신적 응집도", "절차적 응집도", "순차적 응집도"], answer:2 },
    { id:"se_049", question:"소프트웨어 공학에서 '소프트웨어 위기(Software Crisis)'의 주요 원인으로 옳은 것은?", options:["하드웨어 성능 부족", "소프트웨어 복잡도 증가와 체계적 개발 방법 부재", "프로그래밍 언어의 부족", "운영체제의 불안정"], answer:2 },
    { id:"se_050", question:"UML 활동 다이어그램(Activity Diagram)이 주로 표현하는 것은?", options:["클래스 간의 관계", "업무 프로세스나 작업 흐름", "객체 간 메시지 순서", "시스템 물리적 배치"], answer:2 },
    { id:"se_051", question:"화이트박스 테스트 기법 중 프로그램 내의 모든 실행 가능한 경로를 테스트하는 것은?", options:["구문 커버리지", "결정 커버리지", "조건 커버리지", "경로 커버리지"], answer:4 },
    { id:"se_052", question:"소프트웨어 품질 특성 중 사용자가 쉽게 이해하고 사용할 수 있는 능력은?", options:["기능성", "신뢰성", "사용성", "유지보수성"], answer:3 },
    { id:"se_053", question:"COCOMO 모델에서 중간 규모의 복잡도를 가진 소프트웨어에 적용하는 유형은?", options:["Organic", "Semi-detached", "Embedded", "Extreme"], answer:2 },
    { id:"se_054", question:"소프트웨어 유지보수 유형 중 미래의 유지보수성을 높이기 위해 수행하는 것은?", options:["수정(Corrective) 유지보수", "적응(Adaptive) 유지보수", "완전(Perfective) 유지보수", "예방(Preventive) 유지보수"], answer:4 },
    { id:"se_055", question:"결합도 중 두 모듈이 단순한 데이터 파라미터로만 연결된 형태는?", options:["자료 결합도", "스탬프 결합도", "제어 결합도", "공통 결합도"], answer:1 },
    { id:"se_056", question:"디자인 패턴의 개념을 처음 체계화한 저서와 관련된 저자 그룹을 부르는 말은?", options:["애자일 선언문 그룹", "GoF(Gang of Four)", "SWEBOK 위원회", "IEEE 표준화 위원회"], answer:2 },
    { id:"se_057", question:"소프트웨어 요구사항 중 '사용자 로그인 기능을 제공해야 한다'는 어떤 요구사항인가?", options:["비기능적 요구사항", "기능적 요구사항", "성능 요구사항", "보안 요구사항"], answer:2 },
    { id:"se_058", question:"UML 컴포넌트 다이어그램(Component Diagram)이 표현하는 것은?", options:["객체 간 메시지 교환", "시스템의 물리적 노드 배치", "소프트웨어 컴포넌트 간의 의존 관계", "유스케이스와 액터 관계"], answer:3 },
    { id:"se_059", question:"원인-결과 그래프(Cause-Effect Graph) 기법은 어떤 테스트에 속하는가?", options:["화이트박스 테스트", "블랙박스 테스트", "단위 테스트", "통합 테스트"], answer:2 },
    { id:"se_060", question:"응집도 중 모듈 내의 구성 요소들이 순서적으로 실행되어 앞 활동의 출력이 다음 활동의 입력이 되는 형태는?", options:["기능적 응집도", "순차적 응집도", "통신적 응집도", "절차적 응집도"], answer:2 },
    { id:"se_061", question:"소프트웨어 형상 관리에서 형상 항목의 변경 요청을 검토하고 승인하는 역할을 하는 것은?", options:["형상 감사(Configuration Audit)", "형상 식별(Configuration Identification)", "형상 통제위원회(CCB)", "형상 상태 보고(Configuration Status Accounting)"], answer:3 },
    { id:"se_062", question:"폭포수 모델의 단점으로 옳은 것은?", options:["문서 산출물이 없다", "중간에 요구사항 변경이 어렵다", "각 단계의 경계가 불명확하다", "위험 분석이 과도하게 이루어진다"], answer:2 },
    { id:"se_063", question:"소프트웨어 품질 특성 중 자원을 적절히 사용하여 요구된 성능을 제공하는 능력은?", options:["기능성", "신뢰성", "효율성", "유지보수성"], answer:3 },
    { id:"se_064", question:"결합도 중 두 모듈이 자료 구조(레코드, 배열 등)를 공유하는 형태는?", options:["자료 결합도", "스탬프 결합도", "제어 결합도", "공통 결합도"], answer:2 },
    { id:"se_065", question:"애자일 방법론 중 스프린트(Sprint)라는 짧은 개발 주기를 사용하는 것은?", options:["XP(Extreme Programming)", "스크럼(Scrum)", "칸반(Kanban)", "린(Lean)"], answer:2 },
    { id:"se_066", question:"소프트웨어 테스트 단계 중 단위 테스트(Unit Test)에 대한 설명으로 옳은 것은?", options:["전체 시스템이 요구사항을 만족하는지 확인", "모듈 간 인터페이스를 확인", "개별 모듈을 독립적으로 테스트", "사용자 환경에서 수행하는 테스트"], answer:3 },
    { id:"se_067", question:"UML 상태 다이어그램(State Diagram)이 주로 표현하는 것은?", options:["시스템의 물리적 배치", "객체의 상태 변화와 전이", "클래스 간의 상속 관계", "프로세스의 순차적 흐름"], answer:2 },
    { id:"se_068", question:"응집도 중 모듈 내의 구성 요소들이 특정 순서를 따라 실행되지만 순차적 관계는 없는 형태는?", options:["순차적 응집도", "절차적 응집도", "통신적 응집도", "시간적 응집도"], answer:2 },
    { id:"se_069", question:"소프트웨어 품질 특성 중 수정, 개선이 용이한 능력은?", options:["기능성", "신뢰성", "이식성", "유지보수성"], answer:4 },
    { id:"se_070", question:"나선형 모델의 장점으로 옳은 것은?", options:["개발 초기에 완전한 요구사항 명세 가능", "위험 요소를 조기에 발견하고 대응 가능", "소규모 프로젝트에 가장 적합", "문서 없이도 개발 가능"], answer:2 },
    { id:"se_071", question:"화이트박스 테스트 기법 중 프로그램 내의 모든 구문(Statement)이 한 번 이상 실행되도록 하는 것은?", options:["구문 커버리지", "결정 커버리지", "조건 커버리지", "경로 커버리지"], answer:1 },
    { id:"se_072", question:"디자인 패턴 중 객체 생성 인터페이스를 정의하되 하위 클래스에서 어떤 클래스를 생성할지 결정하도록 하는 패턴은?", options:["싱글톤(Singleton)", "팩토리 메소드(Factory Method)", "어댑터(Adapter)", "옵저버(Observer)"], answer:2 },
    { id:"se_073", question:"소프트웨어 요구사항 중 '응답 시간이 3초 이내여야 한다'는 어떤 요구사항인가?", options:["기능적 요구사항", "비기능적 요구사항", "도메인 요구사항", "사용자 요구사항"], answer:2 },
    { id:"se_074", question:"소프트웨어 재사용의 장점으로 옳지 않은 것은?", options:["개발 기간 단축", "소프트웨어 신뢰성 향상", "새로운 요구사항 반영이 쉬워짐", "유지보수 비용 절감"], answer:3 },
    { id:"se_075", question:"UML 클래스 다이어그램(Class Diagram)에서 'is-a' 관계를 나타내는 것은?", options:["연관(Association)", "집합(Aggregation)", "상속(Inheritance/Generalization)", "의존(Dependency)"], answer:3 },
    { id:"se_076", question:"결합도가 높을수록 소프트웨어 모듈에 미치는 영향으로 옳은 것은?", options:["유지보수가 쉬워진다", "독립성이 높아진다", "변경 영향이 넓어져 유지보수가 어려워진다", "재사용성이 높아진다"], answer:3 },
    { id:"se_077", question:"소프트웨어 형상 관리 활동으로 옳지 않은 것은?", options:["형상 식별(Configuration Identification)", "형상 통제(Configuration Control)", "형상 감사(Configuration Audit)", "형상 구현(Configuration Implementation)"], answer:4 },
    { id:"se_078", question:"소프트웨어 테스트 단계 중 통합 테스트(Integration Test)에 대한 설명으로 옳은 것은?", options:["개별 모듈을 독립적으로 테스트", "모듈을 결합하여 인터페이스와 상호작용을 테스트", "전체 시스템이 요구사항을 만족하는지 확인", "사용자 환경에서 수행하는 테스트"], answer:2 },
    { id:"se_079", question:"응집도 중 관련 없는 기능들을 논리적으로 분류만 해서 묶은 형태는?", options:["우연적 응집도", "논리적 응집도", "시간적 응집도", "절차적 응집도"], answer:2 },
    { id:"se_080", question:"프로토타입 모델의 장점으로 옳은 것은?", options:["문서화가 완벽하게 이루어짐", "초기에 사용자의 요구를 명확히 파악 가능", "모든 위험을 미리 분석 가능", "개발 비용이 가장 낮음"], answer:2 },
    { id:"se_081", question:"소프트웨어 품질 특성 중 명시된 조건 하에서 소프트웨어가 요구된 기능을 수행하는 능력은?", options:["기능성", "신뢰성", "사용성", "이식성"], answer:1 },
    { id:"se_082", question:"화이트박스 테스트 기법 중 각 분기(Branch)의 참/거짓 결과를 모두 테스트하는 것은?", options:["구문 커버리지", "결정 커버리지", "조건 커버리지", "경로 커버리지"], answer:2 },
    { id:"se_083", question:"디자인 패턴 중 하나의 객체에 대한 변화를 여러 객체에 자동으로 통보하는 패턴은?", options:["싱글톤(Singleton)", "어댑터(Adapter)", "옵저버(Observer)", "팩토리 메소드(Factory Method)"], answer:3 },
    { id:"se_084", question:"소프트웨어 형상 관리에서 '형상 식별(Configuration Identification)'의 내용으로 옳은 것은?", options:["변경 사항의 승인과 통제", "형상 항목을 선정하고 이름을 부여", "변경 사항의 이력을 기록", "형상 항목의 무결성 검증"], answer:2 },
    { id:"se_085", question:"소프트웨어 테스트 단계 중 인수 테스트(Acceptance Test)에 대한 설명으로 옳은 것은?", options:["개발자가 코드를 직접 보며 테스트", "모듈 간 인터페이스를 테스트", "고객이 시스템을 인수하기 전 요구사항 충족 여부를 확인", "회귀 오류를 찾기 위한 테스트"], answer:3 },
    { id:"se_086", question:"결합도 중 두 모듈이 외부에서 정의된 데이터 형식이나 프로토콜을 공유하는 형태는?", options:["스탬프 결합도", "제어 결합도", "외부 결합도", "공통 결합도"], answer:3 },
    { id:"se_087", question:"소프트웨어 개발에서 '요구사항 명세서(SRS)'의 특징으로 옳지 않은 것은?", options:["완전성", "일관성", "추적 가능성", "구현 방법의 상세 기술"], answer:4 },
    { id:"se_088", question:"애자일 선언문(Agile Manifesto)의 4가지 핵심 가치에 해당하지 않는 것은?", options:["프로세스와 도구보다 개인과 상호작용", "포괄적인 문서보다 작동하는 소프트웨어", "계약 협상보다 고객과의 협력", "변화에 대응하기보다 계획을 따름"], answer:4 },
    { id:"se_089", question:"소프트웨어 테스트에서 회귀 테스트(Regression Test)의 목적으로 옳은 것은?", options:["최초 개발 완료 후 전체 기능을 확인", "변경으로 인해 기존 기능에 결함이 발생하지 않았는지 확인", "사용자가 직접 수행하는 인수 테스트", "모든 경로를 실행하는 경로 커버리지 테스트"], answer:2 },
    { id:"se_090", question:"응집도 순위에서 가장 낮은(나쁜) 응집도는?", options:["논리적 응집도", "시간적 응집도", "우연적 응집도", "절차적 응집도"], answer:3 },
    { id:"se_091", question:"소프트웨어 품질 보증(SQA)의 목적으로 옳은 것은?", options:["개발 기간 단축", "소프트웨어가 정해진 표준과 절차를 따르는지 확인", "요구사항을 새롭게 발굴", "하드웨어 성능 최적화"], answer:2 },
    { id:"se_092", question:"디자인 패턴 중 하나의 인스턴스만 생성되도록 보장하는 패턴은?", options:["팩토리 메소드(Factory Method)", "싱글톤(Singleton)", "옵저버(Observer)", "어댑터(Adapter)"], answer:2 },
    { id:"se_093", question:"소프트웨어 재사용 수준 중 가장 높은 수준의 재사용 형태는?", options:["코드 복사", "함수/모듈 재사용", "컴포넌트 재사용", "프레임워크 재사용"], answer:4 },
    { id:"se_094", question:"UML에서 시스템의 정적 구조를 나타내는 다이어그램에 해당하지 않는 것은?", options:["클래스 다이어그램", "컴포넌트 다이어그램", "배치 다이어그램", "시퀀스 다이어그램"], answer:4 },
    { id:"se_095", question:"소프트웨어 공학에서 모듈화(Modularity)의 장점으로 옳지 않은 것은?", options:["유지보수 용이", "코드 재사용성 향상", "독립적 개발 가능", "실행 속도가 항상 빨라짐"], answer:4 },
    { id:"se_096", question:"소프트웨어 테스트 단계 중 시스템 테스트(System Test)에 대한 설명으로 옳은 것은?", options:["개별 모듈을 독립적으로 테스트", "모듈 간 인터페이스를 테스트", "통합된 전체 시스템이 요구사항을 만족하는지 테스트", "사용자가 직접 수행하는 테스트"], answer:3 },
    { id:"se_097", question:"소프트웨어 위험 관리(Risk Management)에서 위험 대응 전략 중 위험을 아예 제거하는 방법은?", options:["위험 수용(Risk Acceptance)", "위험 완화(Risk Mitigation)", "위험 회피(Risk Avoidance)", "위험 전가(Risk Transfer)"], answer:3 },
    { id:"se_098", question:"소프트웨어 품질 특성(ISO/IEC 25010) 중 보안(Security)은 어떤 대분류에 포함되는가?", options:["신뢰성", "사용성", "기능 적합성", "기능성"], answer:4 },
    { id:"se_099", question:"소프트웨어 개발 방법론 중 XP(Extreme Programming)의 핵심 실천 방법에 해당하는 것은?", options:["위험 분석 반복", "스프린트 백로그", "페어 프로그래밍(Pair Programming)", "칸반 보드"], answer:3 },
    { id:"se_100", question:"소프트웨어 개발에서 하향식 통합 테스트(Top-down Integration Test)의 특징으로 옳은 것은?", options:["하위 모듈부터 테스트를 시작하여 상위로 통합", "상위 모듈부터 테스트를 시작하여 하위로 통합", "모든 모듈을 동시에 통합하여 테스트", "핵심 모듈을 먼저 테스트하고 주변 모듈을 추가"], answer:2 }
  ],
  "데이터통신": [
    { id:"dc_001", question:"OSI 7계층 모델에서 라우팅(Routing) 기능을 담당하는 계층은?", options:["데이터링크 계층", "네트워크 계층", "전송 계층", "세션 계층"], answer:2 },
    { id:"dc_002", question:"TCP와 UDP의 차이점으로 옳은 것은?", options:["TCP는 비연결형이고 UDP는 연결형이다", "TCP는 신뢰성을 보장하고 UDP는 보장하지 않는다", "UDP가 TCP보다 신뢰성이 높다", "TCP는 멀티캐스트를 지원한다"], answer:2 },
    { id:"dc_003", question:"IP 주소 중 클래스 C의 첫 번째 옥텟(Octet) 범위는?", options:["0 ~ 127", "128 ~ 191", "192 ~ 223", "224 ~ 239"], answer:3 },
    { id:"dc_004", question:"HTTP(HyperText Transfer Protocol)의 기본 포트 번호는?", options:["21", "23", "80", "443"], answer:3 },
    { id:"dc_005", question:"CSMA/CD 방식에 대한 설명으로 옳은 것은?", options:["무선 LAN에서 주로 사용한다", "충돌 감지 후 임의 시간 대기 후 재전송한다", "토큰을 이용하여 전송 순서를 제어한다", "전이중(Full-duplex) 방식으로만 동작한다"], answer:2 },
    { id:"dc_006", question:"OSI 7계층 중 물리 계층(Physical Layer)의 역할로 옳은 것은?", options:["데이터 암호화 및 복호화", "비트(Bit)를 전기 신호로 변환하여 전송", "IP 주소를 기반으로 경로 설정", "세그먼트를 패킷으로 캡슐화"], answer:2 },
    { id:"dc_007", question:"이더넷(Ethernet) 프로토콜이 동작하는 OSI 계층은?", options:["물리 계층", "데이터링크 계층", "네트워크 계층", "전송 계층"], answer:2 },
    { id:"dc_008", question:"IP 주소 클래스 A의 첫 번째 옥텟 범위는?", options:["0 ~ 127", "128 ~ 191", "192 ~ 223", "224 ~ 239"], answer:1 },
    { id:"dc_009", question:"DNS(Domain Name System)의 기본 포트 번호는?", options:["21", "25", "53", "110"], answer:3 },
    { id:"dc_010", question:"FTP(File Transfer Protocol)의 제어 연결에 사용하는 포트 번호는?", options:["20", "21", "22", "23"], answer:2 },
    { id:"dc_011", question:"SSH(Secure Shell)의 기본 포트 번호는?", options:["21", "22", "23", "25"], answer:2 },
    { id:"dc_012", question:"SMTP(Simple Mail Transfer Protocol)의 기본 포트 번호는?", options:["21", "23", "25", "110"], answer:3 },
    { id:"dc_013", question:"POP3(Post Office Protocol 3)의 기본 포트 번호는?", options:["25", "53", "80", "110"], answer:4 },
    { id:"dc_014", question:"HTTPS의 기본 포트 번호는?", options:["80", "110", "443", "8080"], answer:3 },
    { id:"dc_015", question:"Telnet의 기본 포트 번호는?", options:["21", "22", "23", "25"], answer:3 },
    { id:"dc_016", question:"OSI 7계층 중 전송 계층(Transport Layer)에서 사용하는 프로토콜이 아닌 것은?", options:["TCP", "UDP", "IP", "SCTP"], answer:3 },
    { id:"dc_017", question:"OSI 7계층 중 응용 계층(Application Layer)에서 동작하는 프로토콜이 아닌 것은?", options:["HTTP", "FTP", "SMTP", "TCP"], answer:4 },
    { id:"dc_018", question:"IPv4 주소는 몇 비트로 구성되는가?", options:["16비트", "32비트", "64비트", "128비트"], answer:2 },
    { id:"dc_019", question:"IPv6 주소는 몇 비트로 구성되는가?", options:["32비트", "64비트", "128비트", "256비트"], answer:3 },
    { id:"dc_020", question:"IPv4와 IPv6의 차이점으로 옳은 것은?", options:["IPv6는 32비트 주소 체계를 사용한다", "IPv4가 IPv6보다 더 많은 주소를 제공한다", "IPv6는 128비트 주소 체계를 사용한다", "IPv4는 보안 기능이 기본 내장되어 있다"], answer:3 },
    { id:"dc_021", question:"전이중(Full-duplex) 통신 방식에 대한 설명으로 옳은 것은?", options:["한 방향으로만 데이터를 전송한다", "양방향으로 동시에 데이터를 전송할 수 있다", "양방향이지만 동시에는 전송할 수 없다", "무선 통신에서만 사용한다"], answer:2 },
    { id:"dc_022", question:"반이중(Half-duplex) 통신 방식의 특징으로 옳은 것은?", options:["동시에 양방향 전송이 가능하다", "한 방향으로만 전송 가능하다", "양방향 전송이 가능하지만 동시에는 불가능하다", "수신만 가능하다"], answer:3 },
    { id:"dc_023", question:"단방향(Simplex) 통신의 예로 가장 적합한 것은?", options:["전화 통화", "무전기", "TV 방송", "채팅"], answer:3 },
    { id:"dc_024", question:"Stop-and-Wait ARQ에 대한 설명으로 옳은 것은?", options:["여러 프레임을 동시에 전송한다", "하나의 프레임을 전송하고 ACK를 받을 때까지 대기한다", "오류가 발생한 프레임부터 이후 프레임 모두를 재전송한다", "오류가 발생한 프레임만 선택적으로 재전송한다"], answer:2 },
    { id:"dc_025", question:"Go-Back-N ARQ에 대한 설명으로 옳은 것은?", options:["오류가 발생한 프레임만 재전송한다", "하나의 프레임을 전송 후 ACK 대기한다", "오류가 발생한 프레임부터 이후 모든 프레임을 재전송한다", "오류 제어를 수신 측에서 담당한다"], answer:3 },
    { id:"dc_026", question:"Selective Repeat ARQ에 대한 설명으로 옳은 것은?", options:["오류가 발생한 프레임부터 모두 재전송한다", "오류가 발생한 프레임만 선택적으로 재전송한다", "ACK를 받기 전까지 전송을 중단한다", "토큰을 이용하여 전송 순서를 제어한다"], answer:2 },
    { id:"dc_027", question:"슬라이딩 윈도우(Sliding Window) 방식은 어떤 기능을 위해 사용하는가?", options:["오류 검출", "흐름 제어", "경로 설정", "암호화"], answer:2 },
    { id:"dc_028", question:"FDM(주파수 분할 다중화)에 대한 설명으로 옳은 것은?", options:["시간을 나누어 각 채널에 할당한다", "서로 다른 주파수 대역을 나누어 각 채널에 할당한다", "코드를 이용하여 채널을 구분한다", "패킷을 분할하여 여러 경로로 전송한다"], answer:2 },
    { id:"dc_029", question:"TDM(시간 분할 다중화)에 대한 설명으로 옳은 것은?", options:["서로 다른 주파수를 각 채널에 할당한다", "코드를 이용하여 채널을 구분한다", "시간을 나누어 각 채널에 할당한다", "파장을 이용하여 채널을 구분한다"], answer:3 },
    { id:"dc_030", question:"CDM(코드 분할 다중화)의 특징으로 옳은 것은?", options:["서로 다른 주파수로 채널을 구분한다", "고유한 코드를 이용하여 채널을 구분한다", "시간 슬롯을 나누어 채널을 구분한다", "광섬유 통신에서만 사용한다"], answer:2 },
    { id:"dc_031", question:"무선 LAN에서 사용하는 매체 접근 방식은?", options:["CSMA/CD", "CSMA/CA", "Token Ring", "FDDI"], answer:2 },
    { id:"dc_032", question:"유선 이더넷 LAN에서 주로 사용하는 매체 접근 방식은?", options:["CSMA/CA", "CSMA/CD", "Token Passing", "TDMA"], answer:2 },
    { id:"dc_033", question:"토큰 링(Token Ring) 방식에 대한 설명으로 옳은 것은?", options:["충돌 감지 후 재전송한다", "토큰을 보유한 노드만 데이터를 전송할 수 있다", "무선 네트워크에서 주로 사용한다", "버스형 토폴로지에서만 사용한다"], answer:2 },
    { id:"dc_034", question:"네트워크 토폴로지 중 버스(Bus)형의 특징으로 옳은 것은?", options:["하나의 노드에 장애가 발생하면 전체 네트워크가 영향을 받는다", "중앙 노드에 모든 단말이 연결된다", "하나의 공통 회선에 모든 노드가 연결된다", "모든 노드가 서로 직접 연결된다"], answer:3 },
    { id:"dc_035", question:"스타(Star)형 토폴로지의 특징으로 옳은 것은?", options:["모든 노드가 하나의 공통 케이블에 연결된다", "중앙 집중식 허브나 스위치에 모든 노드가 연결된다", "노드들이 원형으로 연결된다", "모든 노드가 서로 직접 연결된다"], answer:2 },
    { id:"dc_036", question:"링(Ring)형 토폴로지에 대한 설명으로 옳은 것은?", options:["중앙 허브에 모든 노드가 연결된다", "노드들이 원형으로 연결되어 데이터가 순환한다", "하나의 공통 케이블에 연결된다", "모든 노드가 서로 직접 연결된다"], answer:2 },
    { id:"dc_037", question:"메시(Mesh)형 토폴로지의 특징으로 옳은 것은?", options:["모든 노드가 하나의 케이블에 연결된다", "중앙 집중식 구조이다", "모든 노드가 서로 직접 연결된 완전 연결 구조이다", "데이터가 한 방향으로만 흐른다"], answer:3 },
    { id:"dc_038", question:"허브(Hub)에 대한 설명으로 옳은 것은?", options:["MAC 주소를 기반으로 특정 포트로만 데이터를 전송한다", "IP 주소를 기반으로 경로를 설정한다", "수신된 데이터를 연결된 모든 포트로 브로드캐스트한다", "방화벽 기능을 내장하고 있다"], answer:3 },
    { id:"dc_039", question:"스위치(Switch)에 대한 설명으로 옳은 것은?", options:["연결된 모든 포트로 데이터를 브로드캐스트한다", "IP 주소를 기반으로 경로를 결정한다", "MAC 주소를 학습하여 특정 포트로만 데이터를 전송한다", "OSI 3계층에서 동작한다"], answer:3 },
    { id:"dc_040", question:"라우터(Router)에 대한 설명으로 옳은 것은?", options:["MAC 주소를 기반으로 동작한다", "OSI 1계층에서 동작한다", "IP 주소를 기반으로 서로 다른 네트워크 간의 경로를 설정한다", "동일한 네트워크 내에서만 사용된다"], answer:3 },
    { id:"dc_041", question:"정적 라우팅(Static Routing)의 특징으로 옳은 것은?", options:["네트워크 상태에 따라 자동으로 경로를 변경한다", "관리자가 수동으로 경로를 설정한다", "RIP, OSPF 등의 프로토콜을 사용한다", "네트워크 규모가 클수록 효율적이다"], answer:2 },
    { id:"dc_042", question:"동적 라우팅(Dynamic Routing)의 특징으로 옳은 것은?", options:["관리자가 수동으로 경로를 설정한다", "네트워크 변화에 자동으로 대응하여 경로를 업데이트한다", "소규모 네트워크에서만 사용한다", "라우팅 프로토콜이 필요 없다"], answer:2 },
    { id:"dc_043", question:"RIP(Routing Information Protocol)에 대한 설명으로 옳은 것은?", options:["링크 상태 방식의 라우팅 프로토콜이다", "홉 수(Hop Count)를 메트릭으로 사용하는 거리 벡터 방식이다", "AS 간의 라우팅에 사용된다", "최대 홉 수는 255이다"], answer:2 },
    { id:"dc_044", question:"OSPF(Open Shortest Path First)에 대한 설명으로 옳은 것은?", options:["거리 벡터 라우팅 프로토콜이다", "홉 수를 메트릭으로 사용한다", "링크 상태 라우팅 프로토콜로 SPF 알고리즘을 사용한다", "AS 간 라우팅에만 사용된다"], answer:3 },
    { id:"dc_045", question:"BGP(Border Gateway Protocol)의 주요 특징으로 옳은 것은?", options:["AS 내부의 라우팅에 사용된다", "홉 수를 기반으로 경로를 선택한다", "서로 다른 AS(자율 시스템) 간의 라우팅에 사용된다", "소규모 네트워크 전용 프로토콜이다"], answer:3 },
    { id:"dc_046", question:"IP 주소 클래스 B의 첫 번째 옥텟 범위는?", options:["0 ~ 127", "128 ~ 191", "192 ~ 223", "224 ~ 239"], answer:2 },
    { id:"dc_047", question:"IP 주소 클래스 D는 어떤 용도로 사용되는가?", options:["일반 유니캐스트 통신", "멀티캐스트 통신", "브로드캐스트 통신", "실험적 용도"], answer:2 },
    { id:"dc_048", question:"IP 주소 클래스 E(240~255)의 용도로 옳은 것은?", options:["멀티캐스트", "유니캐스트", "브로드캐스트", "실험적 목적으로 예약"], answer:4 },
    { id:"dc_049", question:"서브넷 마스크(Subnet Mask)의 역할로 옳은 것은?", options:["데이터 암호화에 사용된다", "IP 주소에서 네트워크 부분과 호스트 부분을 구분한다", "MAC 주소를 IP 주소로 변환한다", "라우팅 테이블을 자동으로 갱신한다"], answer:2 },
    { id:"dc_050", question:"클래스 C 네트워크의 기본 서브넷 마스크는?", options:["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], answer:3 },
    { id:"dc_051", question:"클래스 A 네트워크의 기본 서브넷 마스크는?", options:["255.0.0.0", "255.255.0.0", "255.255.255.0", "0.0.0.0"], answer:1 },
    { id:"dc_052", question:"클래스 B 네트워크의 기본 서브넷 마스크는?", options:["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], answer:2 },
    { id:"dc_053", question:"OSI 7계층 중 세션 계층(Session Layer)의 역할로 옳은 것은?", options:["데이터 암호화 및 복호화", "두 응용 프로그램 간의 통신 세션을 관리하고 동기화", "비트를 전기 신호로 변환", "IP 주소 기반 경로 설정"], answer:2 },
    { id:"dc_054", question:"OSI 7계층 중 표현 계층(Presentation Layer)의 역할로 옳은 것은?", options:["경로 설정 및 라우팅", "흐름 제어 및 오류 제어", "데이터 형식 변환, 암호화, 압축", "물리적 연결 및 신호 변환"], answer:3 },
    { id:"dc_055", question:"OSI 7계층 중 데이터링크 계층(Data Link Layer)의 역할로 옳은 것은?", options:["IP 주소를 이용한 경로 설정", "인접 노드 간의 신뢰성 있는 데이터 전송 및 오류 제어", "응용 프로그램 간의 서비스 제공", "데이터 암호화 및 형식 변환"], answer:2 },
    { id:"dc_056", question:"TCP 프로토콜의 특징으로 옳지 않은 것은?", options:["연결 지향형 프로토콜이다", "신뢰성 있는 데이터 전송을 보장한다", "흐름 제어와 오류 제어를 제공한다", "헤더 구조가 UDP보다 간단하다"], answer:4 },
    { id:"dc_057", question:"UDP 프로토콜의 특징으로 옳은 것은?", options:["연결 설정 후 데이터를 전송한다", "데이터 전달 순서를 보장한다", "비연결형으로 빠른 전송이 가능하다", "흐름 제어 기능을 제공한다"], answer:3 },
    { id:"dc_058", question:"실시간 스트리밍이나 VoIP에서 주로 사용하는 전송 계층 프로토콜은?", options:["TCP", "UDP", "IP", "ICMP"], answer:2 },
    { id:"dc_059", question:"대칭키 암호화(Symmetric Key Encryption)의 특징으로 옳은 것은?", options:["암호화 키와 복호화 키가 서로 다르다", "암호화와 복호화에 같은 키를 사용한다", "공개키와 개인키를 쌍으로 사용한다", "키 교환 문제가 없다"], answer:2 },
    { id:"dc_060", question:"공개키 암호화(Public Key Encryption)의 특징으로 옳은 것은?", options:["암호화와 복호화에 동일한 키를 사용한다", "키 관리가 대칭키보다 단순하다", "공개키로 암호화하고 개인키로 복호화한다", "처리 속도가 대칭키 암호화보다 빠르다"], answer:3 },
    { id:"dc_061", question:"방화벽(Firewall)의 주요 기능으로 옳은 것은?", options:["네트워크 속도를 향상시킨다", "설정된 규칙에 따라 트래픽을 허용하거나 차단한다", "데이터를 암호화하여 전송한다", "IP 주소를 자동으로 할당한다"], answer:2 },
    { id:"dc_062", question:"VPN(Virtual Private Network)에 대한 설명으로 옳은 것은?", options:["물리적으로 전용선을 구축하는 기술이다", "공용 네트워크를 통해 사설 네트워크처럼 안전하게 통신하는 기술이다", "LAN 내에서만 사용 가능하다", "암호화를 사용하지 않는다"], answer:2 },
    { id:"dc_063", question:"IEEE 802.11은 어떤 네트워크 표준인가?", options:["유선 이더넷 표준", "무선 LAN(Wi-Fi) 표준", "블루투스 표준", "광섬유 네트워크 표준"], answer:2 },
    { id:"dc_064", question:"IEEE 802.11ac 무선 표준의 특징으로 옳은 것은?", options:["2.4GHz 대역만 사용한다", "5GHz 대역을 사용하며 높은 전송 속도를 지원한다", "최대 속도가 54Mbps이다", "블루투스와 동일한 표준이다"], answer:2 },
    { id:"dc_065", question:"OSI 7계층에서 물리 계층(1계층)의 데이터 단위(PDU)는?", options:["프레임(Frame)", "패킷(Packet)", "세그먼트(Segment)", "비트(Bit)"], answer:4 },
    { id:"dc_066", question:"OSI 7계층에서 데이터링크 계층(2계층)의 데이터 단위(PDU)는?", options:["비트(Bit)", "프레임(Frame)", "패킷(Packet)", "세그먼트(Segment)"], answer:2 },
    { id:"dc_067", question:"OSI 7계층에서 네트워크 계층(3계층)의 데이터 단위(PDU)는?", options:["프레임(Frame)", "세그먼트(Segment)", "패킷(Packet)", "비트(Bit)"], answer:3 },
    { id:"dc_068", question:"OSI 7계층에서 전송 계층(4계층)의 데이터 단위(PDU)는?", options:["프레임(Frame)", "패킷(Packet)", "세그먼트(Segment)", "비트(Bit)"], answer:3 },
    { id:"dc_069", question:"MAC(Media Access Control) 주소는 OSI 몇 계층에서 사용되는가?", options:["1계층 (물리 계층)", "2계층 (데이터링크 계층)", "3계층 (네트워크 계층)", "4계층 (전송 계층)"], answer:2 },
    { id:"dc_070", question:"ARP(Address Resolution Protocol)의 기능으로 옳은 것은?", options:["도메인 이름을 IP 주소로 변환한다", "IP 주소를 MAC 주소로 변환한다", "MAC 주소를 IP 주소로 변환한다", "IP 주소를 도메인 이름으로 변환한다"], answer:2 },
    { id:"dc_071", question:"DHCP(Dynamic Host Configuration Protocol)의 역할로 옳은 것은?", options:["도메인 이름을 IP 주소로 변환한다", "IP 주소를 MAC 주소로 변환한다", "클라이언트에게 IP 주소를 자동으로 할당한다", "네트워크 간의 경로를 설정한다"], answer:3 },
    { id:"dc_072", question:"ICMP(Internet Control Message Protocol)의 주요 용도로 옳은 것은?", options:["파일 전송", "전자 메일 전송", "네트워크 오류 보고 및 진단", "IP 주소 자동 할당"], answer:3 },
    { id:"dc_073", question:"TCP의 3-way Handshake 과정의 순서로 옳은 것은?", options:["SYN → ACK → SYN+ACK", "SYN → SYN+ACK → ACK", "ACK → SYN → SYN+ACK", "SYN+ACK → SYN → ACK"], answer:2 },
    { id:"dc_074", question:"CSMA/CA에서 'CA'가 의미하는 것은?", options:["충돌 감지(Collision Avoidance)", "충돌 분석(Collision Analysis)", "충돌 회피(Collision Avoidance)", "충돌 인증(Collision Authentication)"], answer:3 },
    { id:"dc_075", question:"CSMA/CD에서 'CD'가 의미하는 것은?", options:["충돌 회피(Collision Detection)", "충돌 감지(Collision Detection)", "충돌 분류(Collision Division)", "충돌 제어(Collision Direction)"], answer:2 },
    { id:"dc_076", question:"네트워크에서 브로드캐스트(Broadcast)란 무엇인가?", options:["특정 노드에만 데이터를 전송하는 방식", "여러 특정 노드 그룹에 데이터를 전송하는 방식", "네트워크의 모든 노드에 데이터를 전송하는 방식", "송신자와 수신자 간에만 전송하는 방식"], answer:3 },
    { id:"dc_077", question:"멀티캐스트(Multicast)에 대한 설명으로 옳은 것은?", options:["네트워크의 모든 노드에 전송한다", "특정 그룹에 속한 노드들에게만 데이터를 전송한다", "하나의 특정 노드에만 전송한다", "임의의 가장 가까운 노드에 전송한다"], answer:2 },
    { id:"dc_078", question:"NAT(Network Address Translation)의 주요 기능으로 옳은 것은?", options:["MAC 주소를 IP 주소로 변환한다", "사설 IP 주소를 공인 IP 주소로 변환하여 인터넷 접속을 가능하게 한다", "도메인 이름을 IP 주소로 변환한다", "IPv4 주소를 IPv6 주소로 변환한다"], answer:2 },
    { id:"dc_079", question:"다음 중 사설(Private) IP 주소 범위에 해당하지 않는 것은?", options:["10.0.0.0 ~ 10.255.255.255", "172.16.0.0 ~ 172.31.255.255", "192.168.0.0 ~ 192.168.255.255", "200.0.0.0 ~ 200.255.255.255"], answer:4 },
    { id:"dc_080", question:"OSI 7계층에서 응용 계층(Application Layer)은 몇 계층인가?", options:["5계층", "6계층", "7계층", "4계층"], answer:3 },
    { id:"dc_081", question:"흐름 제어(Flow Control)의 목적으로 옳은 것은?", options:["데이터 암호화", "수신 측이 처리할 수 없을 만큼 빠르게 데이터가 전송되는 것을 방지", "최적 경로 설정", "주파수 간섭 방지"], answer:2 },
    { id:"dc_082", question:"오류 제어(Error Control)의 방법이 아닌 것은?", options:["ARQ(자동 재전송 요청)", "오류 검출 코드 사용", "슬라이딩 윈도우", "패리티 비트"], answer:3 },
    { id:"dc_083", question:"LAN(Local Area Network)의 특징으로 옳은 것은?", options:["광역 네트워크로 국가 간 연결에 사용된다", "제한된 지역 내의 네트워크로 고속 전송이 가능하다", "저속 전송 속도를 가진다", "위성을 통한 통신이 필수적이다"], answer:2 },
    { id:"dc_084", question:"WAN(Wide Area Network)에 대한 설명으로 옳은 것은?", options:["같은 건물이나 캠퍼스 내의 네트워크이다", "도시나 국가, 대륙 간을 연결하는 광역 네트워크이다", "10Gbps 이상의 속도만 지원한다", "무선 통신만을 사용한다"], answer:2 },
    { id:"dc_085", question:"IEEE 802.3 표준이 정의하는 것은?", options:["무선 LAN(Wi-Fi)", "유선 이더넷(Ethernet)", "블루투스", "토큰 링"], answer:2 },
    { id:"dc_086", question:"패킷 교환(Packet Switching) 방식의 특징으로 옳은 것은?", options:["전용 회선을 미리 설정하여 사용한다", "데이터를 패킷으로 분할하여 독립적으로 전송한다", "회선 이용률이 낮다", "실시간 전송에 가장 적합하다"], answer:2 },
    { id:"dc_087", question:"회선 교환(Circuit Switching) 방식의 특징으로 옳은 것은?", options:["데이터를 패킷으로 나누어 전송한다", "전송 전에 전용 회선을 미리 설정하여 사용한다", "경로가 동적으로 변경된다", "회선이 설정되지 않아도 전송 가능하다"], answer:2 },
    { id:"dc_088", question:"다음 중 비연결형 프로토콜에 해당하는 것은?", options:["TCP", "UDP", "FTP", "HTTP"], answer:2 },
    { id:"dc_089", question:"리피터(Repeater)의 역할로 옳은 것은?", options:["MAC 주소를 기반으로 프레임을 전달한다", "IP 주소를 기반으로 경로를 설정한다", "신호를 증폭하여 전송 거리를 연장한다", "여러 프로토콜 간의 변환을 담당한다"], answer:3 },
    { id:"dc_090", question:"게이트웨이(Gateway)의 역할로 옳은 것은?", options:["신호를 물리적으로 증폭한다", "MAC 주소를 기반으로 프레임을 전달한다", "서로 다른 네트워크 프로토콜 간의 변환을 담당한다", "동일 프로토콜을 사용하는 LAN 구간만을 연결한다"], answer:3 },
    { id:"dc_091", question:"IPv6에서 도입된 기능으로 옳지 않은 것은?", options:["128비트 주소 체계", "IPSec 보안 기본 내장", "주소 공간 확장", "체크섬(Checksum) 헤더 필드 추가"], answer:4 },
    { id:"dc_092", question:"WEP, WPA, WPA2는 어떤 분야의 보안 표준인가?", options:["유선 이더넷 보안", "무선 LAN 보안", "VPN 암호화", "방화벽 정책"], answer:2 },
    { id:"dc_093", question:"OSI 모델에서 라우터(Router)가 주로 동작하는 계층은?", options:["1계층 (물리 계층)", "2계층 (데이터링크 계층)", "3계층 (네트워크 계층)", "4계층 (전송 계층)"], answer:3 },
    { id:"dc_094", question:"OSI 모델에서 스위치(Switch)가 주로 동작하는 계층은?", options:["1계층 (물리 계층)", "2계층 (데이터링크 계층)", "3계층 (네트워크 계층)", "4계층 (전송 계층)"], answer:2 },
    { id:"dc_095", question:"아날로그 신호를 디지털 신호로 변환하는 것을 무엇이라 하는가?", options:["변조(Modulation)", "복조(Demodulation)", "부호화(Encoding)", "인코딩과 동시에 디코딩"], answer:3 },
    { id:"dc_096", question:"TCP/IP 모델에서 인터넷 계층(Internet Layer)에 해당하는 OSI 계층은?", options:["물리 계층", "데이터링크 계층", "네트워크 계층", "전송 계층"], answer:3 },
    { id:"dc_097", question:"다음 중 링크 상태(Link State) 라우팅 프로토콜에 해당하는 것은?", options:["RIP", "OSPF", "BGP", "IGRP"], answer:2 },
    { id:"dc_098", question:"다음 중 거리 벡터(Distance Vector) 라우팅 프로토콜에 해당하는 것은?", options:["OSPF", "IS-IS", "RIP", "EIGRP(하이브리드 제외 시)"], answer:3 },
    { id:"dc_099", question:"무선 LAN에서 CSMA/CA 방식이 CSMA/CD 대신 사용되는 이유로 옳은 것은?", options:["무선 환경에서는 전송 속도가 빠르기 때문에", "무선 환경에서는 충돌 감지가 어렵기 때문에", "무선 LAN에서는 토큰 방식을 사용하지 않기 때문에", "무선 LAN 장비가 CSMA/CD를 지원하지 않기 때문에"], answer:2 },
    { id:"dc_100", question:"다음 중 OSI 7계층을 하위 계층부터 올바르게 나열한 것은?", options:["응용-표현-세션-전송-네트워크-데이터링크-물리", "물리-데이터링크-네트워크-전송-세션-표현-응용", "물리-네트워크-데이터링크-전송-세션-표현-응용", "물리-데이터링크-전송-네트워크-세션-표현-응용"], answer:2 }
  ]
};